'use client'
import {ChangeEvent,useMemo,useState} from 'react'
import * as XLSX from 'xlsx'
import {completeStage02,saveStage02} from './actions'

type Row=Record<string,unknown>
type VarInfo={name:string,type:string,missing:number,missingPct:number,unique:number}
const isBlank=(v:unknown)=>v===null||v===undefined||String(v).trim()===''
const num=(v:unknown)=>typeof v==='number'?v:(typeof v==='string'&&v.trim()!==''&&!Number.isNaN(Number(v))?Number(v):null)
function infer(values:unknown[]){const present=values.filter(v=>!isBlank(v));if(!present.length)return'Empty';const numeric=present.filter(v=>num(v)!==null).length;if(numeric/present.length>=.9)return'Numeric';const unique=new Set(present.map(String)).size;if(unique<=Math.min(20,Math.ceil(present.length*.25)))return'Categorical';return'Text'}
function quantile(a:number[],q:number){if(!a.length)return NaN;const s=[...a].sort((x,y)=>x-y),p=(s.length-1)*q,b=Math.floor(p),r=p-b;return s[b+1]!==undefined?s[b]+r*(s[b+1]-s[b]):s[b]}

export default function DataExplorer(){
 const params=typeof window!=='undefined'?new URLSearchParams(window.location.search):new URLSearchParams();const project=params.get('project')??'';const saved=params.get('saved');const pageError=params.get('error')
 const[rows,setRows]=useState<Row[]>([]);const[file,setFile]=useState('');const[sheet,setSheet]=useState('');const[error,setError]=useState('');const[tab,setTab]=useState<'preview'|'variables'|'missing'|'stats'>('preview');const[drag,setDrag]=useState(false);const[qualityNote,setQualityNote]=useState('')
 const columns=useMemo(()=>rows.length?Object.keys(rows.reduce((a,r)=>({...a,...r}),{} as Row)):[],[rows]);
 const variables=useMemo<VarInfo[]>(()=>columns.map(name=>{const values=rows.map(r=>r[name]);const missing=values.filter(isBlank).length;return{name,type:infer(values),missing,missingPct:rows.length?missing/rows.length*100:0,unique:new Set(values.filter(v=>!isBlank(v)).map(String)).size}}),[columns,rows]);
 const stats=useMemo(()=>variables.filter(v=>v.type==='Numeric').map(v=>{const a=rows.map(r=>num(r[v.name])).filter((x):x is number=>x!==null);const mean=a.reduce((s,x)=>s+x,0)/(a.length||1);const variance=a.length>1?a.reduce((s,x)=>s+(x-mean)**2,0)/(a.length-1):0;return{name:v.name,n:a.length,mean,sd:Math.sqrt(variance),min:a.length?Math.min(...a):NaN,q1:quantile(a,.25),median:quantile(a,.5),q3:quantile(a,.75),max:a.length?Math.max(...a):NaN}}),[variables,rows]);
 async function load(f:File){setError('');if(!/\.(csv|xlsx|xls)$/i.test(f.name)){setError('Please select a CSV, XLSX or XLS file.');return}try{const data=await f.arrayBuffer();const wb=XLSX.read(data,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const parsed=XLSX.utils.sheet_to_json<Row>(ws,{defval:null,raw:true});if(!parsed.length)throw new Error('No tabular records were found.');setRows(parsed);setFile(f.name);setSheet(wb.SheetNames[0]);setTab('preview')}catch(e){setError(e instanceof Error?e.message:'Unable to read dataset.')}}
 function choose(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(f)load(f)}
 const missingCells=variables.reduce((s,v)=>s+v.missing,0),totalCells=rows.length*columns.length,quality=totalCells?Math.max(0,100-missingCells/totalCells*100):0;
 const profile=rows.length?JSON.stringify({file_name:file,sheet,rows:rows.length,columns:columns.length,missing_cells:missingCells,completeness_percent:Number(quality.toFixed(1)),variables:variables.map(v=>({name:v.name,type:v.type,missing:v.missing,missing_percent:Number(v.missingPct.toFixed(1)),unique:v.unique}))}):''
 return <main className="explorer-shell"><header className="explorer-top"><div><a href="/cases/001">← Case Study 001</a><span className="eyebrow">DATALYTIQS ANALYTICS LAB</span><h1>Data Explorer</h1></div>{file&&<div className="file-chip"><small>ACTIVE DATASET</small><b>{file}</b><span>{rows.length.toLocaleString()} rows · {columns.length} variables</span></div>}</header>
 <section className="explorer-intro"><div><span className="eyebrow gold">STAGE 02 · INSPECT & PREPARE</span><h2>Know your data before you analyse it.</h2><p>Upload the Case 001 dataset. Profile its structure, variable types and missingness, then document the data-quality issues that matter for analysis.</p></div><div className="privacy-note"><b>Local inspection</b><p>The file remains in your browser. Stage 02 persists only its analytical profile and your data-quality note.</p></div></section>
 {!project&&<div className="data-error">Open Stage 02 from your active Case Study 001 project so the inspection can be saved.</div>}
 {!rows.length?<section className={`dropzone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);const f=e.dataTransfer.files?.[0];if(f)load(f)}}><div className="upload-icon">↑</div><h3>Load a dataset</h3><p>Drag and drop <b>Case_001_Dataset.xlsx</b> here, or select a file from your computer.</p><label>Choose CSV / XLSX<input type="file" accept=".csv,.xlsx,.xls" onChange={choose}/></label>{error&&<div className="data-error">{error}</div>}</section>:
 <><section className="data-metrics"><article><span>OBSERVATIONS</span><strong>{rows.length.toLocaleString()}</strong><small>Rows detected</small></article><article><span>VARIABLES</span><strong>{columns.length}</strong><small>Columns detected</small></article><article><span>MISSING CELLS</span><strong>{missingCells.toLocaleString()}</strong><small>{totalCells?(missingCells/totalCells*100).toFixed(1):0}% of all cells</small></article><article><span>COMPLETENESS</span><strong>{quality.toFixed(1)}%</strong><small>Non-missing data</small></article></section>
 <section className="data-panel"><div className="data-toolbar"><div>{(['preview','variables','missing','stats'] as const).map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t==='preview'?'Data Preview':t==='variables'?'Variables':t==='missing'?'Missingness':'Descriptive Statistics'}</button>)}</div><label className="replace">Replace dataset<input type="file" accept=".csv,.xlsx,.xls" onChange={choose}/></label></div>
 {tab==='preview'&&<div className="table-wrap"><div className="table-meta">Showing first {Math.min(20,rows.length)} of {rows.length.toLocaleString()} rows · Sheet: {sheet}</div><table><thead><tr><th>#</th>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,20).map((r,i)=><tr key={i}><td>{i+1}</td>{columns.map(c=><td className={isBlank(r[c])?'cell-missing':''} key={c}>{isBlank(r[c])?'Missing':String(r[c])}</td>)}</tr>)}</tbody></table></div>}
 {tab==='variables'&&<div className="profile-grid">{variables.map((v,i)=><article key={v.name}><span>{String(i+1).padStart(2,'0')}</span><div><b>{v.name}</b><small>{v.type}</small></div><div><em>Unique</em><strong>{v.unique}</strong></div><div><em>Missing</em><strong>{v.missing} <small>({v.missingPct.toFixed(1)}%)</small></strong></div></article>)}</div>}
 {tab==='missing'&&<div className="missing-view"><div className="quality-summary"><span>DATA COMPLETENESS</span><strong>{quality.toFixed(1)}%</strong><p>{missingCells===0?'No missing cells were detected. Continue checking validity, duplicates and plausible ranges.':'Missing values require review before modelling. Document how you will handle them.'}</p></div></div>}
 {tab==='stats'&&<div className="table-wrap">{stats.length?<table><thead><tr><th>Variable</th><th>N</th><th>Mean</th><th>Std. Dev.</th><th>Min</th><th>Q1</th><th>Median</th><th>Q3</th><th>Max</th></tr></thead><tbody>{stats.map(s=><tr key={s.name}><td><b>{s.name}</b></td><td>{s.n}</td>{[s.mean,s.sd,s.min,s.q1,s.median,s.q3,s.max].map((x,i)=><td key={i}>{Number.isFinite(x)?x.toFixed(2):'—'}</td>)}</tr>)}</tbody></table>:<div className="empty-state">No variables were inferred as numeric.</div>}</div>}</section>
 <section className="explorer-next"><div><span className="eyebrow">STAGE 02 DELIVERABLE</span><h3>Data-quality assessment</h3><p>Record missingness, unusual values, coding issues, duplicates, implausible ranges or other limitations you identified.</p></div></section>
 {project&&<><form action={saveStage02} style={{display:'grid',gap:16,margin:'24px 0'}}><input type="hidden" name="project_id" value={project}/><input type="hidden" name="dataset_profile" value={profile}/><textarea name="data_quality_note" required rows={7} value={qualityNote} onChange={e=>setQualityNote(e.target.value)} placeholder="Summarise the dataset quality and any preparation required before analysis."/>{saved==='1'&&<p role="status"><b>Stage 02 draft saved.</b> Dataset profile and quality assessment have been persisted.</p>}<button type="submit">Save Stage 02 Draft</button></form>{pageError==='incomplete'&&<p role="alert"><b>Stage 02 is incomplete.</b> Save the dataset profile and data-quality assessment first.</p>}<form action={completeStage02}><input type="hidden" name="project_id" value={project}/><button type="submit">Complete Stage 02 →</button></form>{saved==='completed'&&<p role="status"><b>Stage 02 completed.</b> Stage 03 is now unlocked and project progress is 33%.</p>}</>}
 </>}
 </main>}
