'use client'

import {useMemo,useState} from 'react'

type Lesson='1'|'2'|'3'
type Check={prompt:string;options:string[];answer:number;feedback:string}
const content={
 '1':{title:'Populations, Frames and Units',duration:'45–55 minutes',outcomes:['Define the target and accessible populations precisely.','Distinguish observation, sampling and analysis units.','Diagnose coverage, duplication and eligibility defects in a sampling frame.']},
 '2':{title:'Probability and Purposive Strategies',duration:'50–60 minutes',outcomes:['Match probability designs to inference requirements.','Use purposive strategies transparently for learning and qualitative enquiry.','Explain design limitations without overstating representativeness.']},
 '3':{title:'Calculate, Document and Defend a Sample',duration:'55–70 minutes',outcomes:['Calculate and adjust a practical sample size.','Document stratification, selection, replacement and non-response rules.','Produce an auditable sampling plan linked to the evaluation question.']},
} as const
const checks:Record<Lesson,Check[]>={
 '1':[
  {prompt:'A programme wants to estimate employment among all graduates. Its contact list excludes graduates who changed phone numbers. What is the main risk?',options:['Sampling error only','Frame undercoverage','Interviewer bias','Perfect precision'],answer:1,feedback:'Eligible graduates missing from the frame have no selection chance, so estimates may be biased if they differ from listed graduates.'},
  {prompt:'In a household survey where one adult answers questions about the household, what is the sampling unit?',options:['The selected household','The questionnaire','Every adult nationally','The final indicator'],answer:0,feedback:'The household is selected from the frame; the respondent supplies information and the unit of analysis depends on each measure.'},
 ],
 '2':[
  {prompt:'Which design best supports a known, non-zero selection probability for every listed graduate?',options:['Convenience sampling','Simple random sampling','Volunteer recruitment','Key-informant selection'],answer:1,feedback:'Simple random sampling assigns each frame member a known and equal probability, provided the frame is adequate.'},
  {prompt:'When is purposive selection defensible?',options:['When estimating a national prevalence without weights','When deliberately selecting information-rich cases and clearly limiting claims','Whenever fieldwork is late','When representativeness must be guaranteed'],answer:1,feedback:'Purposive designs can answer learning and mechanism questions, but their analytical claims must match the selection logic.'},
 ],
 '3':[
  {prompt:'A minimum completed sample is 240 and expected response is 80%. How many cases should be issued?',options:['192','240','300','320'],answer:2,feedback:'Issue 240 ÷ 0.80 = 300 cases. The adjustment should be based on credible response evidence, not optimism.'},
  {prompt:'What is the best replacement rule?',options:['Interview any convenient person','Predefine whether replacement is allowed and use controlled reserve selections','Let enumerators decide','Replace every refusal with a neighbour'],answer:1,feedback:'Uncontrolled substitution changes selection probabilities and can introduce systematic bias.'},
 ],
}
const designs=[
 ['Simple random','Complete frame; relatively homogeneous population','Transparent selection and analysis','Weak subgroup precision when small groups matter'],
 ['Systematic','Ordered frame without harmful periodicity','Operationally efficient','Hidden ordering patterns can bias selection'],
 ['Stratified','Important subgroups known in advance','Improves subgroup coverage and sometimes precision','Requires correct weights when allocation is disproportionate'],
 ['Cluster / multistage','Population geographically dispersed','Reduces travel and listing cost','Usually increases variance; account for design effect'],
 ['Purposive','Information-rich cases needed','Supports depth and mechanism learning','Does not support population prevalence claims'],
]

export default function LessonExperience({lesson}:{lesson:Lesson}){
 const info=content[lesson]
 const[selected,setSelected]=useState<Record<number,number>>({})
 const score=useMemo(()=>checks[lesson].filter((item,index)=>selected[index]===item.answer).length,[lesson,selected])
 return <main className="lesson-shell">
  <nav aria-label="Breadcrumb"><a href="/merl/applied">MERL Level 2</a><span aria-hidden="true"> / </span><span>Module 08</span><span aria-hidden="true"> / </span><span>Lesson 08.{lesson}</span></nav>
  <header><div><p>LESSON 08.{lesson} · {info.duration}</p><h1>{info.title}</h1><span>County Youth Employment Programme · select evidence sources that can support the claim being made.</span></div><aside><b>MODULE 08</b><span>Lesson {lesson} of 3</span></aside></header>
  <div className="layout"><article>
   <section className="card"><h2>Learning outcomes</h2><ul>{info.outcomes.map(outcome=><li key={outcome}>{outcome}</li>)}</ul></section>
   {lesson==='1'&&<><section><h2>Begin with the population, not the formula</h2><p>The target population is the full group about which a decision is required. The accessible population is the group operationally reachable, while the sampling frame is the actual list or mechanism used for selection. Differences among them are sources of coverage error, not administrative footnotes.</p><div className="concept-grid"><div><h3>Sampling unit</h3><p>The unit selected at a stage, such as a ward, training centre, household or graduate.</p></div><div><h3>Observation unit</h3><p>The source from which measurements are obtained, such as a respondent or record.</p></div><div><h3>Analysis unit</h3><p>The entity represented by the result, such as a learner, enterprise or facility.</p></div></div></section><section className="principle"><b>Frame audit</b><p>Check eligibility dates, omissions, duplicates, stale contacts and unequal selection chances. A random draw from a defective list is still a defective sample.</p></section></>}
   {lesson==='2'&&<><section><h2>Match design to the intended inference</h2><p>Probability sampling supports statistical inference when selection probabilities are known and the frame and response process are defensible. Non-probability approaches support targeted learning when their purpose and limits are explicit.</p><div className="table-wrap"><table><thead><tr><th>Design</th><th>Use when</th><th>Strength</th><th>Watch</th></tr></thead><tbody>{designs.map(row=><tr key={row[0]}>{row.map((cell,index)=>index===0?<th key={cell}>{cell}</th>:<td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></section><section className="principle"><b>Claims discipline</b><p>Selection method, response patterns and weighting determine what can be generalised. A large convenience sample does not become representative through enthusiasm or decimal places.</p></section></>}
   {lesson==='3'&&<><section><h2>Sample size is a documented judgement</h2><p>For a proportion under simple random sampling, an initial planning value is n₀ = z²p(1−p)/e². Adjust it for a finite population where appropriate, then account for design effect, subgroup precision and expected non-response. Software calculates; professionals justify the assumptions.</p><div className="practice"><h3>Worked example</h3><p>At 95% confidence, p=0.50 and ±5 percentage points, n₀≈385. For a population of 2,000, the finite-population adjustment gives about 323 completed cases. At 80% expected response, issue at least 404 selections before any justified design-effect adjustment.</p></div></section><section className="principle"><b>No silent replacement</b><p>Document reserve selection, callbacks, refusal treatment and non-response analysis before fieldwork. Convenience substitution protects the target count while quietly damaging the inference.</p></section></>}
   <section className="practice"><h2>Guided knowledge check</h2>{checks[lesson].map((item,index)=><fieldset key={item.prompt}><legend>{index+1}. {item.prompt}</legend>{item.options.map((option,optionIndex)=><label key={option}><input type="radio" name={`check-${index}`} checked={selected[index]===optionIndex} onChange={()=>setSelected(current=>({...current,[index]:optionIndex}))}/><span>{option}</span></label>)}{selected[index]!==undefined&&<p role="status" aria-live="polite" className={selected[index]===item.answer?'correct':'incorrect'}>{selected[index]===item.answer?'Correct. ':'Review this. '}{item.feedback}</p>}</fieldset>)}<p><b>Current score: {score}/{checks[lesson].length}</b></p></section>
   {lesson==='3'&&<section className="download"><h2>Professional submission standard</h2><p>Submit the population and frame definitions, design rationale, sample calculation, allocation, selection procedure, non-response rules, weighting plan and limitations. Keep selection identifiers protected and use synthetic examples for practice.</p><a href="/api/merl/level2/sampling-plan-template" download>Download sampling-plan template (.csv)</a></section>}
   <section className="reflection"><h2>Reflection for practice</h2><p>{lesson==='1'?'Who is systematically absent from a sampling frame you currently use, and how could that affect a decision?':lesson==='2'?'Which inference would become invalid if your current recruitment process were described honestly?':"Which assumption—response rate, prevalence, design effect or frame quality—most threatens your proposed sample, and what evidence will you use?"}</p></section>
   <footer><a href={lesson==='1'?'/merl/applied':`/merl/applied/08/${Number(lesson)-1}`}>← {lesson==='1'?'Level 2 overview':'Previous lesson'}</a><a className="next" href={lesson==='3'?'/merl/applied':`/merl/applied/08/${Number(lesson)+1}`}>{lesson==='3'?'Return to Module 08':'Continue to next lesson'} →</a></footer>
  </article><aside className="rail"><b>Progression standard</b><ol><li>Define population and units.</li><li>Audit the sampling frame.</li><li>Match design to inference.</li><li>Calculate and document selection.</li></ol><p>Module 08 feedback is formative until persistent Level 2 competency gates are deployed.</p></aside></div>
  <style jsx global>{`
   .lesson-shell{max-width:1160px;margin:auto;padding:32px 24px 60px;color:#0b2c4d;font-family:system-ui}.lesson-shell a{color:#1565c0}.lesson-shell a:focus-visible,.lesson-shell input:focus-visible{outline:3px solid #f4a261;outline-offset:3px}.lesson-shell>header{margin:24px 0 30px;padding:36px;background:#0b2c4d;color:white;display:grid;grid-template-columns:1fr auto;gap:30px;border-radius:14px}.lesson-shell>header p{color:#f4a261;font-size:12px;font-weight:800;letter-spacing:1.4px}.lesson-shell>header h1{font:700 42px/1.08 Georgia,serif;margin:10px 0}.lesson-shell>header span{color:#d7e0e8;line-height:1.5}.lesson-shell>header aside{border-left:1px solid #ffffff35;padding-left:24px;display:flex;flex-direction:column;justify-content:center}.lesson-shell>header aside span{margin-top:8px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:30px}.layout article>section{margin-bottom:25px}.card,.practice,.download,.reflection,.principle{padding:22px;border:1px solid #d7dee7;border-radius:12px}.card,.reflection{background:#f6f8fb}.principle{border-left:5px solid #f4a261;background:#fff4e8}.lesson-shell h2{font:700 28px Georgia,serif}.lesson-shell p,.lesson-shell li,.lesson-shell td{line-height:1.65}.concept-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.concept-grid>div{padding:18px;border-top:4px solid #f4a261;background:#f6f8fb}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border:1px solid #d7dee7;text-align:left;vertical-align:top}thead th{background:#0b2c4d;color:white}.practice fieldset{margin:16px 0;padding:16px;border:1px solid #d7dee7;border-radius:10px}.practice legend{font-weight:700}.practice label{display:flex;gap:9px;min-height:44px;align-items:center}.correct,.incorrect{padding:12px;border-radius:8px}.correct{background:#e8f5ee;color:#175d43}.incorrect{background:#fff4e8;color:#7a430d}.download a,.next{display:inline-flex;min-height:44px;align-items:center;padding:9px 14px;border-radius:6px;background:#f4a261;color:#081f33!important;font-weight:800;text-decoration:none}.rail{height:max-content;position:sticky;top:24px;padding:22px;border-radius:12px;background:#0b2c4d;color:white}.rail li,.rail p{color:#d7e0e8}.lesson-shell footer{display:flex;justify-content:space-between;gap:18px;padding-top:20px;border-top:1px solid #d7dee7}.lesson-shell footer a{min-height:44px;display:flex;align-items:center}
   @media(max-width:800px){.layout{grid-template-columns:1fr}.rail{position:static}.concept-grid{grid-template-columns:1fr}.lesson-shell>header{grid-template-columns:1fr}.lesson-shell>header aside{border-left:0;border-top:1px solid #ffffff35;padding:18px 0 0}}
   @media(max-width:520px){.lesson-shell{padding:20px 14px}.lesson-shell>header{padding:24px 18px}.lesson-shell>header h1{font-size:31px}.card,.practice,.download,.reflection,.principle{padding:16px}.lesson-shell footer{flex-direction:column}.lesson-shell footer a{justify-content:center}}
  `}</style>
 </main>
}
