'use server'
import {redirect} from 'next/navigation'
import {revalidatePath} from 'next/cache'
import {createClient} from '../../../lib/supabase/server'
const validModules=new Set(['06','07','08','09','10'])
async function authenticated(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login?next=%2Fmerl%2Fapplied');return{supabase,user}}
export async function getMerlLevel2State(){const{supabase}=await authenticated();const{data,error}=await supabase.rpc('get_merl_level2_progress');if(error)throw new Error(error.message);return data??[]}
export async function markLevel2Lesson(moduleId:string,lessonIndex:number){if(!validModules.has(moduleId)||lessonIndex<0||lessonIndex>2)throw new Error('Invalid lesson.');const{supabase}=await authenticated();const{error}=await supabase.rpc('mark_merl_level2_lesson',{p_module_id:moduleId,p_lesson_index:lessonIndex});if(error)throw new Error(error.message);revalidatePath('/merl/applied');return{ok:true}}
export async function submitLevel2Evidence(moduleId:string,evidenceType:string,content:string){if(!validModules.has(moduleId))throw new Error('Invalid module.');if(content.trim().length<20)throw new Error('Professional evidence must contain at least 20 characters.');const{supabase}=await authenticated();const{data,error}=await supabase.rpc('submit_merl_level2_evidence',{p_module_id:moduleId,p_evidence_type:evidenceType,p_content:content.trim()});if(error)throw new Error(error.message);revalidatePath('/merl/applied');return{ok:true,id:data}}
export async function getLevel2Quiz(moduleId:string){if(!validModules.has(moduleId))throw new Error('Invalid module.');const{supabase}=await authenticated();const{data,error}=await supabase.rpc('get_merl_level2_quiz',{p_module_id:moduleId});if(error)throw new Error(error.message);return data??[]}
export async function gradeLevel2Quiz(moduleId:string,answers:Record<string,string>){if(!validModules.has(moduleId))return{ok:false as const,error:'Invalid module.'};const{supabase}=await authenticated();const{data,error}=await supabase.rpc('grade_merl_level2_quiz',{p_module_id:moduleId,p_answers:answers});if(error)return{ok:false as const,error:error.message};const result=Array.isArray(data)?data[0]:data;if(!result)return{ok:false as const,error:'Quiz grading returned no result.'};const{data:rows,error:verifyError}=await supabase.rpc('get_merl_level2_progress');if(verifyError)return{ok:false as const,error:`Graded but persistence could not be verified: ${verifyError.message}`};const persisted=rows?.find((row:{module_id:string})=>row.module_id===moduleId);if(!persisted||Number(persisted.quiz_attempts)<Number(result.attempts))return{ok:false as const,error:'Quiz result did not persist.'};revalidatePath('/merl/applied');return{ok:true as const,score:Number(result.score),passed:Boolean(result.passed),attempts:Number(result.attempts)}}
