'use client'
import {useEffect,useState} from 'react'
import {getLevel2Quiz,getMerlLevel2State,gradeLevel2Quiz,markLevel2Lesson,submitLevel2Evidence} from './actions'
type Module={id:string;title:string;output:string;lessons:string[]}
type Progress={module_id:string;lesson_evidence:Record<string,boolean>;evidence_submission:{id:number;status:string}|null;quiz_score:number|null;quiz_passed:boolean;quiz_attempts:number;module_completed_at:string|null}
type QuizItem={question_id:string;question_order:number;stem:string;options:string[]}
const modules:Module[]=[
 {id:'06',title:'Data Collection Planning',output:'Operational data-collection plan',lessons:['From Indicator to Data Requirement','Select Sources, Methods and Frequency','Build and Review a Data-Collection Plan']},
 {id:'07',title:'Tools, Protocols and Fieldwork',output:'Tested collection tool and field protocol',lessons:['Question and Tool Design','Field Protocols and Enumerator Preparation','Pilot, Revise and Release a Tool']},
 {id:'08',title:'Sampling for MERL Practice',output:'Defensible sampling plan',lessons:['Populations, Frames and Units','Probability and Purposive Strategies','Calculate, Document and Defend a Sample']},
 {id:'09',title:'Data Quality Assurance',output:'Data-quality assurance plan',lessons:['Quality Dimensions and Risk','Verification, Validation and Correction','Design a Data-Quality Review']},
 {id:'10',title:'Monitoring Systems and Dashboards',output:'Decision-oriented monitoring specification',lessons:['System Architecture and Data Flow','Reporting, Visualisation and Access','Specify a Useful Monitoring System']},
]
export default function AppliedExperience({isTestAccount}:{isTestAccount:boolean}){
 const[open,setOpen]=useState('06'),[progress,setProgress]=useState<Record<string,Progress>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
 const[evidence,setEvidence]=useState<Record<string,string>>({}),[quiz,setQuiz]=useState<Record<string,QuizItem[]>>({}),[answers,setAnswers]=useState<Record<string,Record<string,string>>>({})
 async function refresh(){const rows=await getMerlLevel2State();const map:Record<string,Progress>={};rows.forEach((row:Progress)=>map[row.module_id]=row);setProgress(map);setLoading(false)}
 useEffect(()=>{refresh().catch(error=>{setMessage(error.message);setLoading(false)})},[])
 const done=(id:string)=>!!progress[id]?.module_completed_at
 const lessonsDone=(m:Module)=>m.lessons.every((_,i)=>progress[m.id]?.lesson_evidence?.[`${m.id}-${i}`])
 const completed=modules.filter(m=>done(m.id)).length
 const gates=modules.reduce((n,m)=>n+m.lessons.filter((_,i)=>progress[m.id]?.lesson_evidence?.[`${m.id}-${i}`]).length+(progress[m.id]?.evidence_submission?1:0)+(progress[m.id]?.quiz_passed?1:0),0)
 async function run(key:string,fn:()=>Promise<unknown>){setBusy(key);setMessage('');try{await fn();await refresh()}catch(error){setMessage(error instanceof Error?error.message:'Action failed.')}finally{setBusy('')}}
 return <main className="applied-shell" aria-busy={loading||!!busy}>
  <a className="skip-link" href="#modules">Skip to Level 2 modules</a><nav><a href="/merl/foundations">MERL Level 1</a> / Level 2</nav>
  <header><p>MERL PROFESSIONAL PATHWAY · LEVEL 2</p><h1>Applied Monitoring Systems</h1><span>Build governed evidence systems that move reliably from collection to decision and learning.</span></header>
  {isTestAccount&&<aside className="test-note" role="note"><b>ACCEPTANCE-TEST LEARNER</b><br/>This progress is synthetic and must not enter certification or real learner analytics.</aside>}
  {message&&<p className="message" role="status" aria-live="polite">{message}</p>}
  <section className="progress"><b>Level 2 progress {loading?'…':`${Math.round(completed/5*100)}%`}</b><span>{gates}/25 competency gates</span><div role="progressbar" aria-label="Level 2 competency progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={loading?undefined:Math.round(completed/5*100)}><i style={{width:`${completed/5*100}%`}}/></div></section>
  <section id="modules" className="modules" aria-label="Level 2 modules">{modules.map((m,index)=>{const p=progress[m.id],locked=index>0&&!done(modules[index-1].id),expanded=open===m.id,complete=done(m.id);return <article key={m.id} className={locked?'locked':''}>
   <button className="toggle" disabled={locked||loading} aria-expanded={!locked&&expanded} aria-controls={`panel-${m.id}`} onClick={()=>setOpen(expanded?'':m.id)}><b>{m.id}</b><span><strong>{m.title}</strong><small>Professional output: {m.output}</small></span><strong>{locked?'LOCKED':complete?'COMPETENT ✓':expanded?'CLOSE':'OPEN'}</strong></button>
   {expanded&&!locked&&<div id={`panel-${m.id}`} className="panel"><h3>Learning sequence</h3>{m.lessons.map((lesson,i)=>{const key=`${m.id}-${i}`,recorded=!!p?.lesson_evidence?.[key];return <div className="lesson" key={key}><span><a href={`/merl/applied/${m.id}/${i+1}`}><b>{m.id}.{i+1} {lesson}</b></a><small>Complete the lesson and guided practice, then record the gate.</small></span><button disabled={recorded||!!busy} onClick={()=>run(key,()=>markLevel2Lesson(m.id,i))}>{recorded?'Recorded ✓':busy===key?'Saving…':'Record lesson evidence'}</button></div>})}
    <section className="card"><label htmlFor={`evidence-${m.id}`}><b>Professional evidence submission</b></label><p>Submit the actual {m.output.toLowerCase()}. Remove confidential and personal information.</p><textarea id={`evidence-${m.id}`} rows={5} value={evidence[m.id]||''} disabled={!!p?.evidence_submission} onChange={e=>setEvidence(v=>({...v,[m.id]:e.target.value}))}/><button disabled={!lessonsDone(m)||!!p?.evidence_submission||!!busy} onClick={()=>run(`ev-${m.id}`,()=>submitLevel2Evidence(m.id,m.output,evidence[m.id]||''))}>{p?.evidence_submission?'Submitted ✓':busy===`ev-${m.id}`?'Submitting…':'Submit professional evidence'}</button></section>
    <section className="card"><b>Scored module quiz</b><p>Pass mark 70%; maximum two attempts. The answer key remains server-side.</p>{p?.quiz_score!=null&&<p><b>Best score: {p.quiz_score}% · Attempts: {p.quiz_attempts}/2 {p.quiz_passed?'· PASSED':''}</b></p>}
     {!p?.quiz_passed&&p?.evidence_submission&&!quiz[m.id]&&<button disabled={!!busy||p.quiz_attempts>=2} onClick={()=>run(`quiz-${m.id}`,async()=>{const items=await getLevel2Quiz(m.id);setQuiz(v=>({...v,[m.id]:items}))})}>Load quiz</button>}
     {quiz[m.id]?.map(q=><fieldset key={q.question_id}><legend><b>{q.stem}</b></legend>{q.options.map((option,i)=><label key={option}><input type="radio" name={q.question_id} checked={answers[m.id]?.[q.question_id]===String(i)} onChange={()=>setAnswers(v=>({...v,[m.id]:{...(v[m.id]||{}),[q.question_id]:String(i)}}))}/>{option}</label>)}</fieldset>)}
     {quiz[m.id]?.length>0&&!p?.quiz_passed&&<button disabled={!!busy||quiz[m.id].some(q=>answers[m.id]?.[q.question_id]===undefined)} onClick={()=>run(`grade-${m.id}`,async()=>{const result=await gradeLevel2Quiz(m.id,answers[m.id]||{});if(!result.ok)throw new Error(result.error);setMessage(`Quiz score: ${result.score}% · Attempt ${result.attempts}/2`);setQuiz(v=>({...v,[m.id]:[]}));setAnswers(v=>({...v,[m.id]:{}}))})}>Submit quiz</button>}
    </section><p><b>{complete?'COMPLETE — next module unlocked':'Required: 3 lesson gates + evidence + quiz pass.'}</b></p>
   </div>}
  </article>})}</section>
  {completed===5&&<section className="credential"><h2>Level 2 competency gate passed</h2><p>All 25 persistent gates are complete. The integrated portfolio is ready for final human review.</p><a className="portfolio-link" href="/merl/applied/portfolio">Open Level 2 competency portfolio →</a></section>}
  <style jsx global>{`
   .applied-shell{max-width:1100px;margin:auto;padding:36px 24px 64px;color:#0b2c4d;font-family:system-ui}.applied-shell a{color:#1565c0}.skip-link{position:absolute;left:-9999px}.skip-link:focus{left:12px;top:8px;background:white;padding:10px;z-index:2}.applied-shell>header{margin:24px 0;padding:36px;background:#0b2c4d;color:white;border-radius:14px}.applied-shell>header p{color:#f4a261;font-size:12px;font-weight:800;letter-spacing:1.4px}.applied-shell h1{font:700 42px Georgia,serif;margin:8px 0}.applied-shell>header span{color:#d7e0e8}.test-note,.message,.progress,.credential{padding:18px;margin:18px 0;border:1px solid #d7dee7;border-radius:10px}.test-note{background:#fff4e8;border:2px solid #a65300}.progress{background:#f6f8fb}.progress>span{float:right}.progress>div{height:8px;background:#ddd;margin-top:12px;border-radius:5px}.progress i{display:block;height:8px;background:#1565c0;border-radius:5px}.modules{display:grid;gap:14px}.modules article{border:1px solid #d7dee7;border-radius:12px;overflow:hidden}.modules article.locked{opacity:.58}.toggle{width:100%;padding:20px;border:0;background:white;display:grid;grid-template-columns:55px 1fr auto;text-align:left;gap:14px;align-items:center;color:#0b2c4d}.toggle>b{font-size:24px}.toggle span{display:grid;gap:5px}.panel{padding:0 22px 22px}.lesson{display:grid;grid-template-columns:1fr auto;gap:12px;padding:10px 0}.lesson span,.lesson small{display:block}.card{padding:17px;margin:14px 0;border:1px solid #d7dee7;border-radius:10px}.card textarea{width:100%;box-sizing:border-box;padding:10px}.card fieldset{margin:12px 0;padding:12px}.card fieldset label{display:flex;gap:8px;min-height:40px;align-items:center}.applied-shell button,.applied-shell a{min-height:44px}.applied-shell button{font:inherit}.applied-shell button:focus-visible,.applied-shell a:focus-visible,.applied-shell textarea:focus-visible,.applied-shell input:focus-visible{outline:3px solid #f4a261;outline-offset:3px}.credential{background:#eef8f1}.portfolio-link{display:inline-flex;align-items:center;padding:8px 14px;border-radius:6px;background:#175d43;color:white!important;text-decoration:none;font-weight:800}
   @media(max-width:640px){.applied-shell{padding:24px 14px}.applied-shell h1{font-size:32px}.toggle{grid-template-columns:42px 1fr;padding:16px}.toggle>strong{grid-column:1/-1}.lesson{grid-template-columns:1fr}.lesson button,.card button{width:100%}.panel{padding:0 16px 18px}.progress>span{float:none;display:block;margin-top:7px}}
  `}</style>
 </main>
}
