'use client'
import {useMemo,useState} from 'react'

type Lesson='1'|'2'|'3'
type Check={prompt:string;options:string[];answer:number;feedback:string}
const content={
 '1':{title:'Quality Dimensions and Risk',duration:'45–55 minutes',outcomes:['Assess accuracy, completeness, timeliness, consistency, validity and integrity.','Identify quality risks across the data lifecycle.','Prioritise controls by likelihood, consequence and detectability.']},
 '2':{title:'Verification, Validation and Correction',duration:'50–60 minutes',outcomes:['Distinguish verification from validation.','Design traceable queries and correction rules.','Preserve original values, reasons and approvals in an audit trail.']},
 '3':{title:'Design a Data-Quality Review',duration:'55–70 minutes',outcomes:['Specify review indicators, thresholds and responsibilities.','Triangulate records, aggregates and field evidence.','Convert findings into corrective and preventive action.']},
} as const
const checks:Record<Lesson,Check[]>={
 '1':[
  {prompt:'A monthly report arrives six weeks after the management decision. Which quality dimension is primarily affected?',options:['Timeliness','Uniqueness','Precision','Confidentiality'],answer:0,feedback:'The values may be accurate, but late evidence cannot inform the intended decision.'},
  {prompt:'Which risk deserves the earliest control?',options:['Rare typo with no decision effect','Likely duplicate payments with high financial consequence','Cosmetic formatting difference','A documented blank optional field'],answer:1,feedback:'Risk-based assurance prioritises errors that are likely, consequential and difficult to detect later.'},
 ],
 '2':[
  {prompt:'What does source verification ask?',options:['Does the value obey a format rule?','Does the entered value match the authorised source?','Is the dashboard attractive?','Can missing data be invented?'],answer:1,feedback:'Verification compares captured data to an authoritative source; validation tests rules, ranges and relationships.'},
  {prompt:'How should a confirmed error be corrected?',options:['Overwrite it silently','Retain the original value and record the new value, reason, actor and time','Delete the entire dataset','Ask each analyst to remember the change'],answer:1,feedback:'A correction must remain reconstructable and attributable.'},
 ],
 '3':[
  {prompt:'What is the strongest completeness indicator?',options:['The report looks complete','Required valid records received ÷ expected eligible records','Number of spreadsheet columns','Total file size'],answer:1,feedback:'The denominator must reflect expected eligible records and the numerator must apply the agreed validity rule.'},
  {prompt:'What should follow a repeated quality failure?',options:['Correct the current values only','Analyse root causes and assign corrective and preventive actions','Lower the threshold quietly','Remove the finding'],answer:1,feedback:'Correction repairs affected records; preventive action changes the process that produced the error.'},
 ],
}
const dimensions=[
 ['Accuracy','Values represent the real condition','Recheck a sample against authorised sources'],
 ['Completeness','Required eligible records and fields are present','Compare valid records with the expected denominator'],
 ['Timeliness','Data arrive within the decision window','Measure lateness from due date to accepted submission'],
 ['Consistency','Definitions and relationships agree across time and systems','Reconcile linked totals, periods and identifiers'],
 ['Validity','Values satisfy formats, ranges and permitted logic','Apply automated and reviewed validation rules'],
 ['Integrity','Data remain protected from unauthorised change','Review access, approvals, hashes and audit logs'],
]
export default function LessonExperience({lesson}:{lesson:Lesson}){
 const info=content[lesson], [selected,setSelected]=useState<Record<number,number>>({})
 const score=useMemo(()=>checks[lesson].filter((item,index)=>selected[index]===item.answer).length,[lesson,selected])
 return <main className="lesson-shell">
  <nav aria-label="Breadcrumb"><a href="/merl/applied">MERL Level 2</a><span aria-hidden="true"> / </span><span>Module 09</span><span aria-hidden="true"> / </span><span>Lesson 09.{lesson}</span></nav>
  <header><div><p>LESSON 09.{lesson} · {info.duration}</p><h1>{info.title}</h1><span>County Youth Employment Programme · make quality measurable, traceable and proportionate to decision risk.</span></div><aside><b>MODULE 09</b><span>Lesson {lesson} of 3</span></aside></header>
  <div className="layout"><article>
   <section className="card"><h2>Learning outcomes</h2><ul>{info.outcomes.map(outcome=><li key={outcome}>{outcome}</li>)}</ul></section>
   {lesson==='1'&&<><section><h2>Quality is fitness for an intended decision</h2><p>A dataset can be complete but inaccurate, accurate but late, or valid in format while conceptually wrong. Define each quality dimension against the indicator, decision deadline and consequence of error.</p><div className="table-wrap"><table><thead><tr><th>Dimension</th><th>Question</th><th>Test</th></tr></thead><tbody>{dimensions.map(row=><tr key={row[0]}><th>{row[0]}</th><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div></section><section className="principle"><b>Risk before ritual</b><p>Score likely failure, consequence and detectability; strengthen controls where harm is material. Checking every cell equally is not thoroughness—it is an expensive refusal to prioritise.</p></section></>}
   {lesson==='2'&&<><section><h2>Build a controlled query trail</h2><p>Automated validation should flag impossible ranges, missing required values, duplicates and inconsistent relationships. A reviewer then determines whether a flag is a genuine error, documents the source check and authorises any correction.</p><div className="concept-grid"><div><h3>Detect</h3><p>Run versioned rules and record the affected record, field and rule.</p></div><div><h3>Resolve</h3><p>Query the authorised owner; do not infer a convenient replacement.</p></div><div><h3>Audit</h3><p>Retain original value, correction, evidence, reason, actor and timestamp.</p></div></div></section><section className="principle"><b>Missing is information</b><p>Use explicit missing-value codes and analyse patterns. Zero, not applicable, refused and unavailable are not synonyms.</p></section></>}
   {lesson==='3'&&<><section><h2>A review must end in action</h2><p>Define scope, indicators, thresholds, samples, evidence sources, reviewers and escalation routes before opening the data. Report both the defect rate and its operational cause, then track corrective and preventive actions to closure.</p><div className="practice"><h3>Worked review</h3><p>Of 1,200 expected eligible records, 1,140 arrived and 1,092 passed mandatory checks. Submission completeness is 95.0%; valid completeness is 91.0%. Reporting only “95% received” hides 48 unusable records.</p></div></section><section className="principle"><b>Independent challenge</b><p>Where decisions affect funding, safety or public claims, the person who produced the data should not be the only person who certifies its quality.</p></section></>}
   <section className="practice"><h2>Guided knowledge check</h2>{checks[lesson].map((item,index)=><fieldset key={item.prompt}><legend>{index+1}. {item.prompt}</legend>{item.options.map((option,optionIndex)=><label key={option}><input type="radio" name={`check-${index}`} checked={selected[index]===optionIndex} onChange={()=>setSelected(current=>({...current,[index]:optionIndex}))}/><span>{option}</span></label>)}{selected[index]!==undefined&&<p role="status" aria-live="polite" className={selected[index]===item.answer?'correct':'incorrect'}>{selected[index]===item.answer?'Correct. ':'Review this. '}{item.feedback}</p>}</fieldset>)}<p><b>Current score: {score}/{checks[lesson].length}</b></p></section>
   {lesson==='3'&&<section className="download"><h2>Professional submission standard</h2><p>Submit a risk-based review plan, measurable rules and thresholds, a query-and-correction log, findings and assigned corrective actions. Use synthetic or de-identified practice records.</p><a href="/api/merl/level2/data-quality-plan-template" download>Download data-quality plan (.csv)</a></section>}
   <section className="reflection"><h2>Reflection for practice</h2><p>{lesson==='1'?'Which quality failure could most seriously distort a current decision, and why?':lesson==='2'?'Can your current correction process reconstruct the original value and explain every change?':"Which repeated defect needs a process change rather than another round of spreadsheet cleaning?"}</p></section>
   <footer><a href={lesson==='1'?'/merl/applied':`/merl/applied/09/${Number(lesson)-1}`}>← {lesson==='1'?'Level 2 overview':'Previous lesson'}</a><a className="next" href={lesson==='3'?'/merl/applied':`/merl/applied/09/${Number(lesson)+1}`}>{lesson==='3'?'Return to Module 09':'Continue to next lesson'} →</a></footer>
  </article><aside className="rail"><b>Progression standard</b><ol><li>Define quality dimensions.</li><li>Prioritise decision risks.</li><li>Control queries and corrections.</li><li>Close corrective actions.</li></ol><p>Module 09 feedback is formative until persistent Level 2 competency gates are deployed.</p></aside></div>
  <style jsx global>{`
   .lesson-shell{max-width:1160px;margin:auto;padding:32px 24px 60px;color:#0b2c4d;font-family:system-ui}.lesson-shell a{color:#1565c0}.lesson-shell a:focus-visible,.lesson-shell input:focus-visible{outline:3px solid #f4a261;outline-offset:3px}.lesson-shell>header{margin:24px 0 30px;padding:36px;background:#0b2c4d;color:white;display:grid;grid-template-columns:1fr auto;gap:30px;border-radius:14px}.lesson-shell>header p{color:#f4a261;font-size:12px;font-weight:800;letter-spacing:1.4px}.lesson-shell>header h1{font:700 42px/1.08 Georgia,serif;margin:10px 0}.lesson-shell>header span{color:#d7e0e8;line-height:1.5}.lesson-shell>header aside{border-left:1px solid #ffffff35;padding-left:24px;display:flex;flex-direction:column;justify-content:center}.lesson-shell>header aside span{margin-top:8px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:30px}.layout article>section{margin-bottom:25px}.card,.practice,.download,.reflection,.principle{padding:22px;border:1px solid #d7dee7;border-radius:12px}.card,.reflection{background:#f6f8fb}.principle{border-left:5px solid #f4a261;background:#fff4e8}.lesson-shell h2{font:700 28px Georgia,serif}.lesson-shell p,.lesson-shell li,.lesson-shell td{line-height:1.65}.concept-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.concept-grid>div{padding:18px;border-top:4px solid #f4a261;background:#f6f8fb}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border:1px solid #d7dee7;text-align:left;vertical-align:top}thead th{background:#0b2c4d;color:white}.practice fieldset{margin:16px 0;padding:16px;border:1px solid #d7dee7;border-radius:10px}.practice legend{font-weight:700}.practice label{display:flex;gap:9px;min-height:44px;align-items:center}.correct,.incorrect{padding:12px;border-radius:8px}.correct{background:#e8f5ee;color:#175d43}.incorrect{background:#fff4e8;color:#7a430d}.download a,.next{display:inline-flex;min-height:44px;align-items:center;padding:9px 14px;border-radius:6px;background:#f4a261;color:#081f33!important;font-weight:800;text-decoration:none}.rail{height:max-content;position:sticky;top:24px;padding:22px;border-radius:12px;background:#0b2c4d;color:white}.rail li,.rail p{color:#d7e0e8}.lesson-shell footer{display:flex;justify-content:space-between;gap:18px;padding-top:20px;border-top:1px solid #d7dee7}.lesson-shell footer a{min-height:44px;display:flex;align-items:center}
   @media(max-width:800px){.layout{grid-template-columns:1fr}.rail{position:static}.concept-grid{grid-template-columns:1fr}.lesson-shell>header{grid-template-columns:1fr}.lesson-shell>header aside{border-left:0;border-top:1px solid #ffffff35;padding:18px 0 0}}
   @media(max-width:520px){.lesson-shell{padding:20px 14px}.lesson-shell>header{padding:24px 18px}.lesson-shell>header h1{font-size:31px}.card,.practice,.download,.reflection,.principle{padding:16px}.lesson-shell footer{flex-direction:column}.lesson-shell footer a{justify-content:center}}
  `}</style>
 </main>
}
