'use client'
import Link from 'next/link'
import {useCallback,useEffect,useState} from 'react'
import {getDataScienceModuleFourQuiz,getDataScienceModuleFourState,gradeDataScienceModuleFourQuiz,markDataScienceModuleFourLesson,submitDataScienceModuleFourEvidence} from '../actions'

const lessons=[['1','Profile Distributions and Missingness','Use descriptive statistics and visual summaries that respect variable type, skewness and missing-data structure.'],['2','Explore Relationships, Groups and Time','Compare groups, examine associations and diagnose temporal patterns without confusing exploration with causal proof.'],['3','Detect Anomalies and Communicate Findings','Investigate unusual values, validate explanations and produce a reproducible EDA report with limitations and next steps.']]
type State={lesson_records:Record<string,boolean>;evidence_submission:{content:string}|null;quiz_score:number|null;quiz_passed:boolean;quiz_attempts:number;module_completed_at:string|null;module_05_unlocked:boolean};type Quiz={question_id:string;question_order:number;stem:string;options:string[]}
export default function ModuleFourExperience(){
 const[state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[evidence,setEvidence]=useState(''),[quiz,setQuiz]=useState<Quiz[]>([]),[answers,setAnswers]=useState<Record<string,string>>({})
 const refresh=useCallback(async()=>{const next=await getDataScienceModuleFourState() as State;setState(next);setEvidence(next?.evidence_submission?.content??'');setLoading(false)},[]);useEffect(()=>{refresh().catch(e=>{setError(e instanceof Error?e.message:'Unable to load progress.');setLoading(false)})},[refresh])
 async function run(key:string,fn:()=>Promise<unknown>,success:string){setBusy(key);setError('');setMessage('');try{await fn();await refresh();setMessage(success)}catch(e){setError(e instanceof Error?e.message:'The request failed.')}finally{setBusy('')}}
 const lessonsDone=lessons.every((_,i)=>!!state?.lesson_records?.[`04-${i}`]),competent=!!state?.module_completed_at,gates=lessons.filter((_,i)=>state?.lesson_records?.[`04-${i}`]).length+(state?.evidence_submission?1:0)+(state?.quiz_passed?1:0)
 return <main className="ds04" aria-busy={loading||!!busy}><a className="ds04-skip" href="#ds04-lessons">Skip to lessons</a><nav aria-label="Breadcrumb"><Link href="/data-science">Data Science</Link> / <Link href="/data-science/foundations/03">Module 03</Link> / Module 04</nav>
  <header><div><p>BEGINNER · MODULE 04</p><h1>Exploratory Data Analysis</h1><span>Interrogate distributions, relationships, missingness and anomalies before formal inference or modelling.</span></div><aside><b>{loading?'…':`${gates}/5`}</b><span>competency gates</span><b>{competent?'100%':state?.quiz_score==null?'—':`${state.quiz_score}%`}</b><span>{competent?'COMPETENT':'best quiz score'}</span></aside></header>
  <div className="ds04-live" role="status" aria-live="polite">{busy?'Saving your progress…':message}</div>{error&&<div className="ds04-error" role="alert">{error}</div>}
  <section className="ds04-standard"><div><p>MODULE OUTCOME</p><h2>Produce a reproducible exploratory analysis that directs—and constrains—what happens next.</h2></div><p>The learner should profile structure and missingness, select type-appropriate summaries, compare groups and time periods, investigate anomalies and distinguish observed patterns from causal claims.</p></section>
  <section id="ds04-lessons" className="ds04-lessons"><div><p>LEARNING SEQUENCE</p><h2>Complete and record all three lessons</h2></div><ol>{lessons.map(([id,title,description],i)=>{const done=!!state?.lesson_records?.[`04-${i}`];return <li key={id}><b>04.{id}</b><div><h3>{title}</h3><p>{description}</p></div><div className="ds04-actions"><Link href={`/data-science/foundations/04/${id}`}>Open lesson →</Link><button disabled={loading||done||!!busy} onClick={()=>run(`lesson-${id}`,()=>markDataScienceModuleFourLesson(i),`Lesson 04.${id} recorded.`)}>{done?'Recorded ✓':busy===`lesson-${id}`?'Saving…':'Record lesson'}</button></div></li>})}</ol></section>
  <section className="ds04-output"><div><p>PROFESSIONAL OUTPUT</p><h2>Exploratory Data Analysis Report</h2><span>Document a genuine dataset’s provenance, analysis grain, quality findings, distributions, comparisons, anomalies, limitations and recommended next analysis.</span></div><a href="/api/data-science/module-04/eda-report-template" download>Download template (.csv)</a></section>
  <section className="ds04-submission"><h2>Professional-evidence submission</h2><label htmlFor="ds04-evidence">Paste the completed EDA report (100–20,000 characters).</label><textarea id="ds04-evidence" rows={9} value={evidence} disabled={!!state?.evidence_submission} onChange={e=>setEvidence(e.target.value)} aria-describedby="ds04-help"/><small id="ds04-help">{evidence.trim().length.toLocaleString()} characters · Opens after all lesson records.</small><button disabled={!lessonsDone||!!state?.evidence_submission||!!busy||evidence.trim().length<100} onClick={()=>run('evidence',()=>submitDataScienceModuleFourEvidence(evidence),'EDA evidence submitted and saved.')}>{state?.evidence_submission?'Submitted ✓':busy==='evidence'?'Submitting…':'Submit professional evidence'}</button></section>
  <section className="ds04-gate"><p>PROTECTED ASSESSMENT GATE</p><h2>{competent?'Module 04 competency achieved':'Pass the protected module quiz'}</h2><div><span><b>{lessons.filter((_,i)=>state?.lesson_records?.[`04-${i}`]).length}/3</b> lessons</span><span><b>{state?.evidence_submission?'1/1':'0/1'}</b> EDA report</span><span><b>{state?.quiz_score==null?'—':`${state.quiz_score}%`}</b> best score</span><span><b>{state?.quiz_attempts??0}/2</b> attempts</span></div><small>Pass mark 70%. The answer key remains server-side; grading, attempt recording and progression occur in one protected transaction.</small>
   {!competent&&state?.evidence_submission&&!quiz.length&&<button disabled={!!busy||(state?.quiz_attempts??0)>=2} onClick={()=>run('load',async()=>setQuiz(await getDataScienceModuleFourQuiz()),'Quiz loaded.')}>{busy==='load'?'Loading…':'Load Module 04 quiz'}</button>}
   {quiz.map(q=><fieldset key={q.question_id}><legend>{q.question_order}. {q.stem}</legend>{q.options.map((o,i)=><label key={o}><input type="radio" name={q.question_id} checked={answers[q.question_id]===String(i)} onChange={()=>setAnswers(v=>({...v,[q.question_id]:String(i)}))}/><span>{o}</span></label>)}</fieldset>)}
   {!!quiz.length&&!competent&&<button disabled={!!busy||quiz.some(q=>answers[q.question_id]===undefined)} onClick={()=>run('grade',async()=>{const r=await gradeDataScienceModuleFourQuiz(answers);if(!r.ok)throw new Error(r.error);setQuiz([]);setAnswers({});setMessage(`Quiz score ${r.score}% · Attempt ${r.attempts}/2${r.passed?' · Module 05 unlocked.':''}`)},'Quiz graded and persisted.')}>{busy==='grade'?'Grading securely…':'Submit quiz for grading'}</button>}
  </section><section className={`ds04-next ${state?.module_05_unlocked?'unlocked':'locked'}`}><p>BEGINNER · MODULE 05</p><h2>{state?.module_05_unlocked?'UNLOCKED':'LOCKED'} — Statistical Reasoning and Inference</h2><span>{state?.module_05_unlocked?'All Module 04 gates passed. Module 05 will be developed next.':'Complete all Module 04 competency gates to unlock Module 05.'}</span></section>
  <footer><Link href="/data-science/foundations/03">← Module 03</Link><Link href="/data-science/foundations/04/1">Open Lesson 04.1 →</Link></footer></main>
}
