import {notFound} from 'next/navigation'
import {createAdminClient} from '../../../lib/supabase/admin'
import {createClient} from '../../../lib/supabase/server'
import {setSubtopicProgress,startCa35p} from '../actions'
import '../exam-hub.css'
import '../topic-workspace.css'

const briefs:Record<string,{question:string;workflow:string[];output:string}>={
 '1.0':{question:'How can an analyst build a faster, auditable and decision-ready Excel workbook?',workflow:['Structure and label the workbook','Apply suitable formulas and analytical tables','Validate calculations and document assumptions'],output:'Controlled Excel analytical workbook'},
 '2.0':{question:'How should an analytics engagement move from a business problem to defensible evidence?',workflow:['Frame the decision problem using CRISP','Map the data lifecycle and requirements','Select suitable tools and visualisations'],output:'Analytics engagement design brief'},
 '3.0':{question:'What do the financial data reveal, and how sensitive is the decision to key assumptions?',workflow:['Prepare and analyse statements','Build forecast and investment models','Run sensitivity and scenario analysis'],output:'Financial analytics decision pack'},
 '4.0':{question:'How can specialised analytics strengthen management accounting, audit, tax and public-finance decisions?',workflow:['Select the specialised decision context','Apply appropriate analytical tests','Communicate exceptions, risks and action'],output:'Specialised analytics case file'},
 '5.0':{question:'Which ethical, security and operational constraints could invalidate an analytical conclusion?',workflow:['Identify adoption and ethics risks','Assess data-protection and security controls','Document tool limitations and mitigations'],output:'Responsible analytics assurance note'},
}

export default async function ExamTopicPage({params,searchParams}:{params:Promise<{topicCode:string}>;searchParams:Promise<{state?:string}>}){
 const[{topicCode},query]=await Promise.all([params,searchParams]);if(!/^[1-5]\.0$/.test(topicCode))notFound()
 const admin=createAdminClient();const{data:topic}=await admin.from('exam_topics').select('id,code,title,description,sequence_no,learning_outcomes,exam_subtopics(id,code,title,description,sequence_no,learning_outcomes)').eq('code',topicCode).eq('active',true).single();if(!topic)notFound()
 const subtopics=[...(topic.exam_subtopics||[])].sort((a:any,b:any)=>a.sequence_no-b.sequence_no),supabase=await createClient(),{data:{user}}=await supabase.auth.getUser()
 let enrollment:any=null,grants:any[]=[],subProgress:any[]=[]
 if(user){const{data:programme}=await supabase.from('exam_programmes').select('id').eq('code','CA35P').single();if(programme){const[{data:e},{data:g}]=await Promise.all([supabase.from('exam_enrollments').select('id,status').eq('programme_id',programme.id).eq('user_id',user.id).maybeSingle(),supabase.from('exam_access_grants').select('access_level,topic_id,expires_at').eq('programme_id',programme.id).eq('user_id',user.id).is('revoked_at',null)]);enrollment=e;grants=g||[];if(e){const{data}=await supabase.from('exam_subtopic_progress').select('subtopic_id,status,completed_at').eq('enrollment_id',e.id);subProgress=data||[]}}}
 const activeGrant=grants.some(g=>(g.access_level==='full'||g.topic_id===topic.id)&&(!g.expires_at||new Date(g.expires_at)>new Date())),accessible=topic.sequence_no<=3||activeGrant,progressMap=new Map(subProgress.map(r=>[r.subtopic_id,r])),completed=subProgress.filter(r=>r.status==='completed').length,brief=briefs[topicCode]
 const message=user&&enrollment&&query.state==='progress-saved'?'Subtopic progress saved.':query.state==='action-error'?'The requested update could not be completed.':''
 const unlockUrl=`https://datalytiqsacademy.com/contact/?subject=${encodeURIComponent('Unlock CA35P Exam Competency Hub')}`
 return <main className="exam-hub topic-workspace"><header className="exam-header"><a className="exam-brand" href="/exam-hub"><span>D</span><b>DatalytIQs</b><small>CA35P Topic Workspace</small></a><nav aria-label="Topic navigation"><a href="/exam-hub">Dashboard</a><a href="#learning-sequence">Learning sequence</a><a href="#practical-brief">Practical brief</a></nav>{user?<span className="account-chip">Signed in</span>:<a className="nav-cta" href={`/login?next=${encodeURIComponent(`/exam-hub/${topicCode}`)}`}>Sign in</a>}</header>
 <section className="topic-hero"><div><a href="/exam-hub">← CA35P dashboard</a><span className="exam-kicker">TOPIC {String(topic.sequence_no).padStart(2,'0')} · {topic.sequence_no<=3?'FREE ACCESS':'PREMIUM'}</span><h1>{topic.title}</h1><p>{topic.description}</p></div><aside><span>TOPIC PROGRESS</span><b>{Math.round(completed/Math.max(subtopics.length,1)*100)}%</b><small>{completed}/{subtopics.length} subtopics completed</small></aside></section>
 {message&&<div className={`exam-notice ${query.state==='action-error'?'error':''}`} role="status">{message}</div>}
 {!accessible?<section className="locked-workspace"><span className="exam-kicker">SUBSCRIPTION REQUIRED</span><h2>This topic is included in full CA35P access.</h2><p>You can review its outline on the dashboard. Guided activities and progress recording unlock after a verified grant is applied.</p><a className="exam-button primary" href={unlockUrl}>Request full access</a></section>:<><section className="exam-section" id="learning-sequence"><div className="exam-section-head"><div><span className="exam-kicker">GUIDED LEARNING</span><h2>Complete the subtopic sequence</h2></div><p>Each evidence gate contributes to the topic and programme progress shown on your dashboard.</p></div><div className="subtopic-list">{subtopics.map((sub:any)=>{const p:any=progressMap.get(sub.id);return <article key={sub.id}><div><span>{sub.code}</span><h3>{sub.title}</h3><p>{sub.description}</p>{sub.learning_outcomes?.length>0&&<ul>{sub.learning_outcomes.map((o:string)=><li key={o}>{o}</li>)}</ul>}</div><div className="subtopic-control"><b className={`topic-badge ${p?.status||'available'}`}>{p?.status?.replace('_',' ')||'not started'}</b>{!user?<a href={`/login?next=${encodeURIComponent(`/exam-hub/${topicCode}`)}`}>Sign in to record</a>:!enrollment?<form action={startCa35p}><button type="submit">Start free access</button></form>:<form action={setSubtopicProgress}><input type="hidden" name="subtopic_id" value={sub.id}/><input type="hidden" name="topic_code" value={topicCode}/><input type="hidden" name="status" value={p?.status==='in_progress'?'completed':'in_progress'}/><button type="submit">{p?.status==='completed'?'Completed ✓':p?.status==='in_progress'?'Mark complete':'Begin subtopic'}</button></form>}</div></article>})}</div></section><section className="practical-panel" id="practical-brief"><div><span className="exam-kicker">PRACTICAL EVIDENCE BRIEF</span><h2>{brief.question}</h2><ol>{brief.workflow.map(step=><li key={step}>{step}</li>)}</ol></div><aside><span>EXPECTED OUTPUT</span><b>{brief.output}</b><small>Retain the workbook or evidence file for assessment and portfolio review.</small></aside></section></>}
 <footer><span>DatalytIQs Academy · CA35P</span><a href="/exam-hub">Exam Hub</a><a href="/">Analytics Lab</a></footer></main>
}
