'use client'

import {useMemo,useState} from 'react'

type Lesson='1'|'2'|'3'
type Check={prompt:string;options:string[];answer:number;feedback:string}

const content={
 '1':{title:'Question and Tool Design',duration:'45–60 minutes',outcomes:['Translate data requirements into concise, answerable questions and fields.','Select response formats and constraints that support valid analysis.','Identify leading, double-barrelled, ambiguous and unnecessarily sensitive items.']},
 '2':{title:'Field Protocols and Enumerator Preparation',duration:'45–55 minutes',outcomes:['Document standard procedures from consent through secure transfer.','Prepare field teams to apply definitions and escalation rules consistently.','Protect respondents, staff and records during collection.']},
 '3':{title:'Pilot, Revise and Release a Tool',duration:'50–65 minutes',outcomes:['Design a pilot that tests comprehension, flow, timing and data behaviour.','Convert pilot evidence into controlled revisions.','Release a versioned tool and protocol ready for authorised use.']},
} as const

const checks:Record<Lesson,Check[]>={
 '1':[
  {prompt:'Which item is double-barrelled?',options:['What is your age in completed years?','Was the training relevant and well facilitated?','Which county do you currently live in?','Did you complete the programme?'],answer:1,feedback:'Relevance and facilitation are separate constructs; one response cannot show which judgement the respondent intended.'},
  {prompt:'What is the strongest employment-status item?',options:['You found a good job, didn’t you?','Are you successful?','During the last seven days, did you perform any work for pay or profit?','Tell us everything about your work'],answer:2,feedback:'The item defines a reference period and observable condition without leading the respondent.'},
 ],
 '2':[
  {prompt:'What should an enumerator do when a respondent withdraws consent?',options:['Continue because the survey already started','Stop collection and follow the documented withdrawal procedure','Offer money until they agree','Ask a colleague to complete the answers'],answer:1,feedback:'Consent is voluntary and continuing. Withdrawal must stop collection and trigger the approved record-handling procedure.'},
  {prompt:'Why use a field escalation protocol?',options:['To hide difficult cases','To standardise safe responses to safeguarding, distress, fraud or technical incidents','To let every enumerator improvise','To replace training'],answer:1,feedback:'Escalation rules protect respondents and staff and ensure serious incidents reach authorised decision-makers promptly.'},
 ],
 '3':[
  {prompt:'What is the main purpose of a pilot?',options:['To create publishable programme findings','To test whether the tool and protocol work as intended','To maximise the sample','To avoid documenting changes'],answer:1,feedback:'Pilot data diagnose the collection process; they should not normally be combined with the final study dataset.'},
  {prompt:'How should a released tool be revised?',options:['Quietly overwrite the file','Use controlled versioning, approvals and a change log','Allow each enumerator to edit it','Change labels after analysis'],answer:1,feedback:'Version control protects comparability, accountability and the ability to explain when and why definitions changed.'},
 ],
}

const defects=[
 {item:'How satisfied are you with the relevant and affordable training?',defect:'Leading and double-barrelled',repair:'Ask relevance and affordability separately using balanced response scales.'},
 {item:'What is your disability?',defect:'Potentially insensitive and underspecified',repair:'Explain the analytical need, make disclosure voluntary and use an approved functioning-question set.'},
 {item:'Did you get a job after training?',defect:'Undefined condition and reference period',repair:'Define work, pay/profit and a specific observation period; capture timing separately.'},
 {item:'County',defect:'Ambiguous variable',repair:'Specify whether this means residence, training location, workplace or employer location.'},
]

export default function LessonExperience({lesson}:{lesson:Lesson}){
 const info=content[lesson]
 const[selected,setSelected]=useState<Record<number,number>>({})
 const score=useMemo(()=>checks[lesson].filter((item,index)=>selected[index]===item.answer).length,[lesson,selected])
 return <main className="lesson-shell">
  <nav aria-label="Breadcrumb"><a href="/merl/applied">MERL Level 2</a><span aria-hidden="true"> / </span><span>Module 07</span><span aria-hidden="true"> / </span><span>Lesson 07.{lesson}</span></nav>
  <header><div><p>LESSON 07.{lesson} · {info.duration}</p><h1>{info.title}</h1><span>County Youth Employment Programme · collect consistent evidence without sacrificing dignity or safety.</span></div><aside><b>MODULE 07</b><span>Lesson {lesson} of 3</span></aside></header>
  <div className="layout"><article>
   <section className="card"><h2>Learning outcomes</h2><ul>{info.outcomes.map(outcome=><li key={outcome}>{outcome}</li>)}</ul></section>
   {lesson==='1'&&<><section><h2>A tool operationalises the plan</h2><p>Every question or field should trace to a defined variable and decision. Wording, response options, validation constraints and skip logic determine what the resulting data can support. A beautifully digitised ambiguous question merely produces bad data more efficiently.</p><div className="table-wrap"><table><thead><tr><th>Weak item</th><th>Defect</th><th>Repair</th></tr></thead><tbody>{defects.map(item=><tr key={item.item}><th>{item.item}</th><td>{item.defect}</td><td>{item.repair}</td></tr>)}</tbody></table></div></section><section className="principle"><b>Minimum necessary data</b><p>Do not collect names, identity numbers, phone numbers, precise locations or health information merely because the software permits another column. Document necessity, access, retention and deletion before collection.</p></section></>}
   {lesson==='2'&&<><section><h2>The protocol is part of the instrument</h2><p>Two enumerators using the same questionnaire can produce different evidence unless they share procedures for introductions, consent, probing, observation, non-response, corrections, safeguarding and secure transfer.</p><div className="concept-grid"><div><h3>Before collection</h3><p>Confirm authorisation, assignments, devices, language versions, sampling lists and secure credentials.</p></div><div><h3>During collection</h3><p>Apply consent, neutral probing, privacy, observation, validation and incident-escalation rules.</p></div><div><h3>After collection</h3><p>Synchronise securely, review completeness, resolve documented queries and remove temporary local copies.</p></div></div></section><section className="principle"><b>Training evidence</b><p>Preparation should include role-play, certification checks and observed practice—not attendance alone. Signing a register proves presence, not competence.</p></section></>}
   {lesson==='3'&&<><section><h2>Pilot the entire workflow</h2><p>Test the tool with people similar to the intended respondents and test the operational chain: recruitment, consent, interview conditions, duration, skip logic, validation, synchronisation, review and escalation.</p><div className="table-wrap"><table><thead><tr><th>Pilot signal</th><th>Possible response</th></tr></thead><tbody><tr><th>Frequent “other” responses</th><td>Review whether categories omit common realities; retain an auditable coding rule.</td></tr><tr><th>High item non-response</th><td>Investigate sensitivity, comprehension, sequencing and whether the item is necessary.</td></tr><tr><th>Interviews much longer than planned</th><td>Remove low-value items, repair flow and revise staffing assumptions.</td></tr><tr><th>Different interpretations across enumerators</th><td>Clarify definitions, examples and training; retest before release.</td></tr></tbody></table></div></section><section className="practice"><h2>Release checklist</h2><ol><li>Approve the final question-to-variable map.</li><li>Record pilot findings and every accepted or rejected revision.</li><li>Assign a version number, owner, effective date and authorised languages.</li><li>Freeze the production form and archive the approved source.</li><li>Publish support, incident and controlled-change procedures.</li></ol></section></>}
   <section className="practice"><h2>Guided knowledge check</h2>{checks[lesson].map((item,index)=><fieldset key={item.prompt}><legend>{index+1}. {item.prompt}</legend>{item.options.map((option,optionIndex)=><label key={option}><input type="radio" name={`check-${index}`} checked={selected[index]===optionIndex} onChange={()=>setSelected(current=>({...current,[index]:optionIndex}))}/><span>{option}</span></label>)}{selected[index]!==undefined&&<p role="status" aria-live="polite" className={selected[index]===item.answer?'correct':'incorrect'}>{selected[index]===item.answer?'Correct. ':'Review this. '}{item.feedback}</p>}</fieldset>)}<p><b>Current score: {score}/{checks[lesson].length}</b></p></section>
   {lesson==='3'&&<section className="download"><h2>Professional submission standard</h2><p>Submit a tool specification, field protocol, pilot log and release record. Show how every field supports a variable, how consent and incidents are handled, and how revisions were governed. Use synthetic or de-identified examples only.</p><a href="/api/merl/level2/fieldwork-package-template" download>Download fieldwork package template (.csv)</a></section>}
   <section className="reflection"><h2>Reflection for practice</h2><p>{lesson==='1'?'Which current question produces answers that analysts routinely struggle to interpret? Rewrite it.':lesson==='2'?'Which field decision is currently left to individual judgement but should be standardised?':"What is the smallest pilot finding that should prevent a tool’s release? Explain the risk."}</p></section>
   <footer><a href={lesson==='1'?'/merl/applied':`/merl/applied/07/${Number(lesson)-1}`}>← {lesson==='1'?'Level 2 overview':'Previous lesson'}</a><a className="next" href={lesson==='3'?'/merl/applied':`/merl/applied/07/${Number(lesson)+1}`}>{lesson==='3'?'Return to Module 07':'Continue to next lesson'} →</a></footer>
  </article><aside className="rail"><b>Progression standard</b><ol><li>Trace fields to requirements.</li><li>Apply ethical question design.</li><li>Standardise field procedures.</li><li>Pilot and control release.</li></ol><p>Module 07 feedback is formative until persistent Level 2 competency gates are deployed.</p></aside></div>
  <style jsx global>{`
   .lesson-shell{max-width:1160px;margin:auto;padding:32px 24px 60px;color:#0b2c4d;font-family:system-ui}.lesson-shell a{color:#1565c0}.lesson-shell a:focus-visible,.lesson-shell input:focus-visible{outline:3px solid #f4a261;outline-offset:3px}.lesson-shell>header{margin:24px 0 30px;padding:36px;background:#0b2c4d;color:white;display:grid;grid-template-columns:1fr auto;gap:30px;border-radius:14px}.lesson-shell>header p{color:#f4a261;font-size:12px;font-weight:800;letter-spacing:1.4px}.lesson-shell>header h1{font:700 42px/1.08 Georgia,serif;margin:10px 0}.lesson-shell>header span{color:#d7e0e8;line-height:1.5}.lesson-shell>header aside{border-left:1px solid #ffffff35;padding-left:24px;display:flex;flex-direction:column;justify-content:center}.lesson-shell>header aside span{margin-top:8px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:30px}.layout article>section{margin-bottom:25px}.card,.practice,.download,.reflection,.principle{padding:22px;border:1px solid #d7dee7;border-radius:12px}.card,.reflection{background:#f6f8fb}.principle{border-left:5px solid #f4a261;background:#fff4e8}.lesson-shell h2{font:700 28px Georgia,serif}.lesson-shell p,.lesson-shell li,.lesson-shell td{line-height:1.65}.concept-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.concept-grid>div{padding:18px;border-top:4px solid #f4a261;background:#f6f8fb}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border:1px solid #d7dee7;text-align:left;vertical-align:top}thead th{background:#0b2c4d;color:white}.practice fieldset{margin:16px 0;padding:16px;border:1px solid #d7dee7;border-radius:10px}.practice legend{font-weight:700}.practice label{display:flex;gap:9px;min-height:44px;align-items:center}.correct,.incorrect{padding:12px;border-radius:8px}.correct{background:#e8f5ee;color:#175d43}.incorrect{background:#fff4e8;color:#7a430d}.download a,.next{display:inline-flex;min-height:44px;align-items:center;padding:9px 14px;border-radius:6px;background:#f4a261;color:#081f33!important;font-weight:800;text-decoration:none}.rail{height:max-content;position:sticky;top:24px;padding:22px;border-radius:12px;background:#0b2c4d;color:white}.rail li,.rail p{color:#d7e0e8}.lesson-shell footer{display:flex;justify-content:space-between;gap:18px;padding-top:20px;border-top:1px solid #d7dee7}.lesson-shell footer a{min-height:44px;display:flex;align-items:center}
   @media(max-width:800px){.layout{grid-template-columns:1fr}.rail{position:static}.concept-grid{grid-template-columns:1fr}.lesson-shell>header{grid-template-columns:1fr}.lesson-shell>header aside{border-left:0;border-top:1px solid #ffffff35;padding:18px 0 0}}
   @media(max-width:520px){.lesson-shell{padding:20px 14px}.lesson-shell>header{padding:24px 18px}.lesson-shell>header h1{font-size:31px}.card,.practice,.download,.reflection,.principle{padding:16px}.lesson-shell footer{flex-direction:column}.lesson-shell footer a{justify-content:center}}
  `}</style>
 </main>
}
