import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { createClient } from '../../../lib/supabase/server'
import { getLesson, lessons } from '../content'
import CodingWorkspace from '../coding-workspace'
import '../python-kids.css'

export async function generateMetadata({params}:{params:Promise<{lessonCode:string}>}):Promise<Metadata>{const{lessonCode}=await params;const lesson=getLesson(lessonCode);return{title:lesson?`${lesson.code} ${lesson.title} | Python for Kids`:'Lesson not found',description:lesson?.hook}}
export default async function LessonPage({params}:{params:Promise<{lessonCode:string}>}){const{lessonCode}=await params;const lesson=getLesson(lessonCode);if(!lesson)notFound();const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();let enrolled=false;if(user){const programme=await supabase.from('learning_programmes').select('id').eq('code','PY-KIDS').maybeSingle();if(programme.data){const e=await supabase.from('learning_enrollments').select('id').eq('user_id',user.id).eq('programme_id',programme.data.id).eq('status','active').maybeSingle();enrolled=Boolean(e.data)}}const index=lessons.findIndex(l=>l.code===lesson.code);const next=lessons[index+1]
return <main className="kids-shell"><header className="kids-nav"><a href="/python-for-kids" className="kids-brand"><b>D</b><span><strong>Python for Kids</strong><small>Module {lesson.module} · Lesson {lesson.code}</small></span></a><nav><a href="/python-for-kids">Dashboard</a><a href="#challenge">Challenge</a><a href="#check">Quick check</a></nav></header><article className="kids-lesson"><header><span className="kids-kicker">LESSON {lesson.code} · {lesson.minutes} MINUTES</span><h1>{lesson.title}</h1><p>{lesson.hook}</p></header><section><h2>Discover</h2><ul>{lesson.discover.map(point=><li key={point}>{point}</li>)}</ul></section><section id="challenge"><h2>Try, explain and change</h2><p><strong>Try:</strong> {lesson.challenge}</p><p><strong>Change:</strong> {lesson.change}</p></section><CodingWorkspace lesson={lesson} enrolled={enrolled}/><section className="kids-debug"><span className="kids-kicker">DEBUG DETECTIVE</span><h2>Find the bug</h2><pre>{lesson.debugCode}</pre><details><summary>Show debugging clue</summary><p>{lesson.debugHint}</p></details></section><section id="check"><span className="kids-kicker">QUICK CHECK</span><h2>{lesson.check.question}</h2>{lesson.check.options.map((option,i)=><details className="kids-answer" key={option}><summary>{option}</summary><p>{i===lesson.check.answer?'Correct — well reasoned.':'Not this time. Review Discover and try again.'}</p></details>)}</section><section><h2>Create and reflect</h2><p><strong>Create:</strong> {lesson.create}</p><p><strong>Reflect:</strong> {lesson.reflection}</p></section><footer>{next&&<a className="kids-button" href={`/python-for-kids/${next.code}`}>Next lesson: {next.title} →</a>}</footer></article></main>}
