import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { createClient } from '../../../lib/supabase/server'
import { getLesson, lessons } from '../content'
import { submitPythonKidsProject } from '../actions'
import CodingWorkspace from '../coding-workspace'
import '../python-kids.css'

export async function generateMetadata({params}:{params:Promise<{lessonCode:string}>}):Promise<Metadata>{
  const{lessonCode}=await params;const lesson=getLesson(lessonCode)
  return{title:lesson?`${lesson.code} ${lesson.title} | Python for Kids`:'Lesson not found',description:lesson?.hook}
}

export default async function LessonPage({params,searchParams}:{params:Promise<{lessonCode:string}>;searchParams:Promise<{state?:string}>}){
  const[{lessonCode},{state}]=await Promise.all([params,searchParams]);const lesson=getLesson(lessonCode);if(!lesson)notFound()
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();let enrolled=false,fullAccess=false
  if(user){const programme=await supabase.from('learning_programmes').select('id').eq('code','PY-KIDS').maybeSingle();if(programme.data){const[e,g]=await Promise.all([supabase.from('learning_enrollments').select('id').eq('user_id',user.id).eq('programme_id',programme.data.id).eq('status','active').maybeSingle(),supabase.from('learning_access_grants').select('starts_at,expires_at').eq('user_id',user.id).eq('programme_id',programme.data.id).is('revoked_at',null)]);enrolled=Boolean(e.data);const now=Date.now();fullAccess=Boolean(g.data?.some((grant:any)=>new Date(grant.starts_at).getTime()<=now&&(!grant.expires_at||new Date(grant.expires_at).getTime()>now)))}}
  if(lesson.module>3&&!fullAccess)return <main className="kids-shell"><header className="kids-nav"><a href="/python-for-kids" className="kids-brand"><b>D</b><span><strong>Python for Kids</strong><small>Academy programme · Lab practice</small></span></a></header><section className="kids-gate"><span className="kids-kicker">MODULE {lesson.module} · SUBSCRIPTION ACCESS</span><h1>{lesson.title}</h1><p>This lesson is published and ready. Enrol through DatalytIQs Academy to unlock Modules 4–10 while retaining the same learner identity, progress and competency evidence.</p><a className="kids-button" href="https://datalytiqsacademy.com/courses/">View Academy enrolment ↗</a><a className="kids-back" href="/python-for-kids">Return to programme map</a></section></main>
  const index=lessons.findIndex(item=>item.code===lesson.code),candidate=lessons[index+1],next=candidate&&(candidate.module<=3||fullAccess)?candidate:null
  return <main className="kids-shell"><header className="kids-nav"><a href="/python-for-kids" className="kids-brand"><b>D</b><span><strong>Python for Kids</strong><small>Module {lesson.module} · Lesson {lesson.code}</small></span></a><nav><a href="/python-for-kids">Dashboard</a><a href="#challenge">Challenge</a><a href="#check">Quick check</a></nav></header><article className="kids-lesson"><header><span className="kids-kicker">LESSON {lesson.code} · {lesson.minutes} MINUTES</span><h1>{lesson.title}</h1><p>{lesson.hook}</p></header><section><h2>Discover</h2><ul>{lesson.discover.map(point=><li key={point}>{point}</li>)}</ul></section><section id="challenge"><h2>Try, explain and change</h2><p><strong>Try:</strong> {lesson.challenge}</p><p><strong>Change:</strong> {lesson.change}</p></section><CodingWorkspace lesson={lesson} enrolled={enrolled}/><section className="kids-debug"><span className="kids-kicker">DEBUG DETECTIVE</span><h2>Find the bug</h2><pre>{lesson.debugCode}</pre><details><summary>Show debugging clue</summary><p>{lesson.debugHint}</p></details></section><section id="check"><span className="kids-kicker">QUICK CHECK</span><h2>{lesson.check.question}</h2>{lesson.check.options.map((option,i)=><details className="kids-answer" key={option}><summary>{option}</summary><p>{i===lesson.check.answer?'Correct — well reasoned.':'Not this time. Review Discover and try again.'}</p></details>)}</section><section><h2>Create and reflect</h2><p><strong>Create:</strong> {lesson.create}</p><p><strong>Reflect:</strong> {lesson.reflection}</p>{lesson.practice&&<div className="kids-practice"><strong>Stretch practice · self check</strong><p>{lesson.practice}</p><small>Edit and run your code again to explore this variation. It does not change lesson completion.</small></div>}</section>{lesson.code==='10.3'&&<section id="project-submission" className="kids-project"><span className="kids-kicker">FINAL PROJECT EVIDENCE</span><h2>Submit for review</h2>{state==='project-submitted'&&<p className="kids-notice success">Project evidence submitted successfully.</p>}{state==='project-incomplete'&&<p className="kids-notice error">Complete the title, code and reflection before submitting.</p>}<form action={submitPythonKidsProject}><label>Project title<input name="title" minLength={3} maxLength={120} required/></label><label>Final Python code<textarea name="code" minLength={20} maxLength={10000} required defaultValue={lesson.starter}/></label><label>Reflection<textarea name="reflection" minLength={20} maxLength={2000} required placeholder="Explain what works, what you tested and what you would improve."/></label><button className="kids-button" type="submit">Submit private evidence</button></form></section>}<footer>{next?<a className="kids-button" href={`/python-for-kids/${next.code}`}>Next lesson: {next.title} →</a>:<a className="kids-button" href="/python-for-kids">Back to programme map →</a>}</footer></article></main>
}
