export type KidLesson = {
  code: string; module: number; title: string; minutes: number; hook: string; discover: string[]
  starter: string; challenge: string; change: string; debugCode: string; debugHint: string
  check: { question: string; options: string[]; answer: number }
  create: string; reflection: string; hints: string[]; expected: string[]; required: string[]; inputs?: string[]
}

export const modules = [
  ['01','Welcome to Coding','Give clear instructions and run a first program.'],
  ['02','Talking to Python','Print messages and use Python as a calculator.'],
  ['03','Variables and User Input','Store information and build an interactive program.'],
  ['04','Making Decisions','Use if, else and elif.'],['05','Loops and Repetition','Repeat instructions efficiently.'],
  ['06','Lists and Collections','Keep and change groups of values.'],['07','Functions','Build reusable code.'],
  ['08','Games and Creative Coding','Plan, build and improve a game.'],['09','Data for Young Analysts','Find meaning in numbers.'],
  ['10','My Python Project','Plan, test and present an original project.'],
] as const

export const lessons: KidLesson[] = [
  {code:'1.1',module:1,title:'What Is Coding?',minutes:25,hook:'A computer is fast, but it needs exact instructions—like a robot following a recipe.',discover:['An algorithm is an ordered set of steps.','Code turns those steps into instructions a computer can follow.','Small spelling and order changes can change the result.'],starter:'print("Step 1: Open the book")\nprint("Step 2: Read one page")',challenge:'Print two ordered steps for getting ready for school.',change:'Swap the order. Does the algorithm still make sense?',debugCode:'print("Step 1: Pack my bag"\nprint("Step 2: Leave home")',debugHint:'The first print instruction is missing its closing parenthesis.',check:{question:'What is an algorithm?',options:['A computer game','An ordered set of steps','A Python error'],answer:1},create:'Write a three-step algorithm for a task you know well.',reflection:'Why must instructions be in the correct order?',hints:['Start each line with print(','Put each message inside quotes.','Close every print with a right parenthesis.'],expected:['Step 1','Step 2'],required:['print']},
  {code:'1.2',module:1,title:'Meet Python',minutes:25,hook:'Python reads your instructions from top to bottom.',discover:['Python is a programming language.','Text inside quotes is called a string.','The output area shows what your program says.'],starter:'print("Hello, Python!")',challenge:'Make Python print “I am learning to code!”',change:'Change the message to include something you enjoy creating.',debugCode:'Print("Hello, Python!")',debugHint:'Python is case-sensitive: use lowercase print.',check:{question:'Which is a Python string?',options:['hello','"hello"','print'],answer:1},create:'Print a friendly two-line welcome message.',reflection:'What happened when you changed the words inside the quotes?',hints:['Use lowercase print.','Put the sentence in quotes.','Your output should include “learning to code”.'],expected:['I am learning to code!'],required:['print']},
  {code:'1.3',module:1,title:'My First Python Challenge',minutes:30,hook:'Now you will combine exact instructions into a tiny digital poster.',discover:['Programs can contain several instructions.','Each print instruction starts a new output line.','Testing helps you spot and fix mistakes.'],starter:'print("=== MY CODE CARD ===")\nprint("Name: Ada")',challenge:'Create a three-line code card with a title, a name and “Future coder”.',change:'Decorate the title using safe keyboard symbols.',debugCode:'print("=== MY CODE CARD ===")\nprint(Name: Ada)\nprint("Future coder")',debugHint:'Text such as Name: Ada must be inside quotes.',check:{question:'Why do programmers test code?',options:['To make typing slower','To find and fix problems','To delete the program'],answer:1},create:'Personalise the card without sharing private information—use a nickname or character name.',reflection:'Which mistake did you find and how did you fix it?',hints:['Use three print lines.','Include a title and Name:.','Finish with Future coder.'],expected:['MY CODE CARD','Name:','Future coder'],required:['print']},
  {code:'2.1',module:2,title:'Printing Messages',minutes:30,hook:'Programs use output to guide, inform and encourage people.',discover:['print() displays output.','Commas can combine values with a space.','Clear messages help people understand a program.'],starter:'print("Welcome!")\nprint("Today we will create with Python.")',challenge:'Print a welcome line and a second line that says “Choose a challenge”.',change:'Make the tone more encouraging.',debugCode:'print("Welcome!)\nprint("Choose a challenge")',debugHint:'The first message needs a closing quotation mark.',check:{question:'What does print() do?',options:['Stores a password','Shows output','Closes Python'],answer:1},create:'Write a three-line menu for a learning game.',reflection:'What makes an instruction easy for a user to understand?',hints:['Use two print instructions.','Include Welcome in the first line.','Include Choose a challenge in the second.'],expected:['Welcome','Choose a challenge'],required:['print']},
  {code:'2.2',module:2,title:'Numbers and Calculations',minutes:35,hook:'Python can check calculations quickly while you focus on the problem.',discover:['Numbers do not need quotes.','Use +, -, * and / for arithmetic.','Parentheses make the intended order clear.'],starter:'print(8 + 4)\nprint(6 * 3)',challenge:'Calculate and print the total points: 12 points plus 8 points.',change:'Add a bonus of 5 points.',debugCode:'print("12" + 8)',debugHint:'Quoted 12 is text, but 8 is a number. Remove the quotes.',check:{question:'Which operator multiplies numbers?',options:['+','*','/'],answer:1},create:'Make a three-line score calculator using addition, subtraction and multiplication.',reflection:'How are numbers different from text in Python?',hints:['Put the calculation inside print().','Use the + operator.','Your program should calculate 12 + 8.'],expected:['20'],required:['print','+']},
  {code:'2.3',module:2,title:'Make Python Calculate',minutes:35,hook:'A useful program stores a result, then explains what that number means.',discover:['A variable can remember a calculated value.','Use = to assign a value.','Good variable names describe the information.'],starter:'stars = 7 + 5\nprint("Total stars:", stars)',challenge:'Store 24 + 18 in a variable named total, then print “Total:” and the result.',change:'Change one number and predict the output before running.',debugCode:'total = 24 + 18\nprint("Total:" total)',debugHint:'Add a comma between the message and the variable.',check:{question:'What does = do here?',options:['Compares two games','Stores a value in a variable','Prints a value'],answer:1},create:'Build a small shopping-total calculator with two item prices.',reflection:'Why is total a clearer name than x?',hints:['Begin with total =','Use 24 + 18.','Print the label and total separated by a comma.'],expected:['Total: 42'],required:['total','=','+','print']},
  {code:'3.1',module:3,title:'Variables as Storage Boxes',minutes:35,hook:'A variable is a labelled storage box your program can use again.',discover:['Names can store text or numbers.','Variable names should be meaningful.','Changing a stored value changes later output.'],starter:'character = "Nova"\nscore = 10\nprint(character, score)',challenge:'Store “Python” in language and 3 in lessons, then print both.',change:'Increase lessons to 4 and run again.',debugCode:'favourite language = "Python"\nprint(favourite language)',debugHint:'Variable names cannot contain spaces; try favourite_language.',check:{question:'Which is a valid variable name?',options:['my score','my_score','3score'],answer:1},create:'Make a character profile with a name, power and score.',reflection:'How do meaningful variable names help a programmer?',hints:['Create language = "Python".','Create lessons = 3.','Print language and lessons.'],expected:['Python 3'],required:['language','lessons','=','print']},
  {code:'3.2',module:3,title:'Asking the User Questions',minutes:40,hook:'Interactive programs listen before they respond.',discover:['input() asks a question and returns text.','Store the answer in a variable.','Never ask for private details such as a full name, address or password.'],starter:'colour = input("Choose a colour: ")\nprint("You chose", colour)',challenge:'Ask “What should we build?” and store the answer in project, then print “Let us build” and the answer.',change:'Change the question while keeping it safe and general.',debugCode:'project = input("What should we build? ")\nprint("Let us build", Project)',debugHint:'Variable names are case-sensitive: project and Project are different.',check:{question:'Which question is safest?',options:['What is your home address?','What is your password?','What should we build?'],answer:2},create:'Build a two-question idea generator without collecting personal information.',reflection:'Why should a program collect only the information it needs?',hints:['Use project = input(...).','Use the exact safe question.','Print Let us build and project.'],expected:['Let us build space game'],required:['project','input','print'],inputs:['space game']},
  {code:'3.3',module:3,title:'Build an Interactive Program',minutes:45,hook:'Combine input, variables and output into your first interactive creation.',discover:['Plan what your program asks, stores and displays.','Test with more than one safe answer.','Helpful output repeats the choice clearly.'],starter:'hero = input("Choose a hero name: ")\npower = input("Choose a superpower: ")\nprint(hero, "uses", power)',challenge:'Ask for a character and a mission, then print “Adventure:” followed by both answers.',change:'Add a safe third choice such as a setting.',debugCode:'character = input("Choose a character: ")\nmission = input("Choose a mission: ")\nprint("Adventure:", character mission)',debugHint:'Separate character and mission with a comma.',check:{question:'What should you do before sharing a program?',options:['Test different answers','Add private details','Remove all instructions'],answer:0},create:'Create and test a short interactive story starter.',reflection:'What did your test reveal about your program?',hints:['Create character and mission inputs.','Print a line beginning Adventure:.','Separate the stored answers with commas.'],expected:['Adventure: Luna find the map'],required:['character','mission','input','print'],inputs:['Luna','find the map']},
]

import { advancedLessons } from './advanced-content'
lessons.push(...advancedLessons)

export function getLesson(code: string) { return lessons.find((lesson) => lesson.code === code) }
