import type { Metadata } from 'next'
import { createClient } from '../../lib/supabase/server'
import { lessons, modules } from './content'
import { startPythonKidsPilot } from './actions'
import './python-kids.css'

export const metadata:Metadata={title:'Python for Kids | Free Coding Foundations | DatalytIQs Academy',description:'A safeguarded Python pathway for ages 10–16. Start Modules 1–3 free and keep one competency record across DatalytIQs Academy and Analytics Lab.'}

export default async function PythonKidsPage(){
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();let enrollment:any=null;let progress:any[]=[];let awards:any[]=[]
  if(user){const programme=await supabase.from('learning_programmes').select('id').eq('code','PY-KIDS').maybeSingle();if(programme.data){const e=await supabase.from('learning_enrollments').select('id,status').eq('user_id',user.id).eq('programme_id',programme.data.id).maybeSingle();enrollment=e.data;if(e.data){const p=await supabase.from('learning_lesson_progress').select('status,learning_lessons(code)').eq('enrollment_id',e.data.id);progress=p.data||[]}const b=await supabase.from('learning_badge_awards').select('awarded_at,learning_badges(title,description)').eq('user_id',user.id);awards=b.data||[]}}
  const completed=new Set(progress.filter((p:any)=>p.status==='completed').map((p:any)=>p.learning_lessons?.code));const percent=Math.round(completed.size/9*100)
  return <main className="kids-shell"><header className="kids-nav"><a href="/" className="kids-brand"><b>D</b><span><strong>DatalytIQs Academy</strong><small>Analytics Lab practice workspace</small></span></a><nav><a href="#modules">Modules</a><a href="#pathway">Pathway</a><a href={user?'/':'/login?next=/python-for-kids'}>{user?'Lab home':'Sign in'}</a></nav></header>
    <section className="kids-hero"><div><span className="kids-kicker">PYTHON FOR KIDS · AGES 10–16</span><h1>Code, create<br/>and solve.</h1><p>Learn Python through short explanations, safe experiments and creative challenges. Modules 1–3 are free.</p>{enrollment?<a className="kids-button" href={`/python-for-kids/${lessons.find(l=>!completed.has(l.code))?.code||'3.3'}`}>Continue learning →</a>:<form action={startPythonKidsPilot}><button className="kids-button" type="submit">{user?'Start free pathway':'Sign in to start free'}</button></form>}</div><div className="kids-principle"><span>ONE LEARNER JOURNEY</span><b>Academy content</b><i>↓</i><b>Lab practice</b><i>↓</i><b>Private evidence</b><i>↓</i><b>Future pathways</b></div></section>
    {enrollment&&<section className="kids-progress" aria-label="Your progress"><div><span>FOUNDATIONS PROGRESS</span><strong>{percent}%</strong><small>{completed.size} of 9 lessons complete</small></div><div className="progress-bar"><i style={{width:`${percent}%`}}/></div><div><span>BADGES EARNED</span><strong>{awards.length}</strong><small>Based on completed evidence</small></div></section>}
    <section id="modules" className="kids-section"><div className="kids-section-title"><div><span className="kids-kicker">PROGRAMME MAP</span><h2>One pathway, built in stages</h2></div><p>Theory stays in the Academy. Interactive practice and competency evidence connect through the same learner identity.</p></div><div className="kids-modules">{modules.map(([code,title,description],index)=>{const free=index<3;const moduleLessons=lessons.filter(l=>l.module===index+1);return <article key={code} className={free?'available':'locked'}><div><span>MODULE {code}</span><b>{free?'FREE':'PLANNED'}</b></div><h3>{title}</h3><p>{description}</p>{free?<ul>{moduleLessons.map(l=><li key={l.code}><a href={`/python-for-kids/${l.code}`}><span>{completed.has(l.code)?'✓':l.code}</span>{l.title}</a></li>)}</ul>:<p className="kids-lock">Builds on the foundations milestone.</p>}</article>})}</div></section>
    <section id="pathway" className="kids-path"><span className="kids-kicker">LONGITUDINAL PATHWAY</span><h2>Your work travels with you.</h2><p>Python for Kids → Python for Teens → Data Analytics for Teens → Python for Data Science → Analytics Lab professional pathways</p><div className="kids-safety"><b>Private by design</b><span>No public child profiles, no direct messages, no birth-date collection and no unrestricted code execution.</span></div></section>
  </main>
}
