import {redirect} from 'next/navigation'
import {createClient} from '../../../../../lib/supabase/server'

export default async function DataRequirementsLesson(){
 const supabase=await createClient()
 const {data:{user}}=await supabase.auth.getUser()
 if(!user) redirect('/login?next=%2Fmerl%2Fapplied%2F06%2F1')
 const {data,error}=await supabase.rpc('get_merl_level1_progress')
 const foundationsComplete=!error&&['01','02','03','04','05'].every(moduleId=>data?.some((row:{module_id:string;module_completed_at:string|null})=>row.module_id===moduleId&&row.module_completed_at))
 if(!foundationsComplete) redirect('/merl/applied')

 return <main className="lesson-shell">
  <nav aria-label="Breadcrumb"><a href="/merl/applied">MERL Level 2</a><span aria-hidden="true"> / </span><span>Module 06</span><span aria-hidden="true"> / </span><span>Lesson 06.1</span></nav>
  <header><div><p>LESSON 06.1 · 40–50 MINUTES</p><h1>From Indicator to Data Requirement</h1><span>County Youth Employment Programme · specify what must be observed before choosing a tool.</span></div><aside><b>MODULE 06</b><span>Lesson 1 of 3</span></aside></header>
  <div className="layout"><article>
   <section className="card"><h2>Learning outcomes</h2><ul><li>Decompose an indicator into the variables, population, unit and reference period required for measurement.</li><li>Distinguish a data requirement from a source, tool or reporting product.</li><li>Document disaggregation, verification and protection requirements before collection begins.</li></ul></section>
   <section><h2>Begin with the decision—not the questionnaire</h2><p>A data requirement states exactly what information is needed, about whom or what, for which period and decision. A source identifies where that information may exist. A method explains how it will be obtained. A tool records it. Starting with the tool encourages unnecessary questions and produces data that are plentiful but unusable.</p><div className="principle"><b>Indicator → decision → required variables → source → method → tool → quality control</b></div></section>
   <section><h2>Worked decomposition</h2><p>For the indicator <b>“Percentage of programme graduates in decent employment six months after completion, by sex, disability and county”</b>, the data plan must define the denominator, employment criteria, observation point and disaggregation rules.</p><div className="table-wrap"><table><thead><tr><th>Requirement</th><th>Operational decision</th></tr></thead><tbody><tr><th>Population</th><td>All verified programme graduates in the eligible completion cohort.</td></tr><tr><th>Numerator</th><td>Graduates meeting every documented decent-employment criterion at follow-up.</td></tr><tr><th>Denominator</th><td>Eligible graduates whose status can be validly established; non-response is reported separately.</td></tr><tr><th>Reference period</th><td>Status measured six months after each learner’s verified completion date.</td></tr><tr><th>Disaggregation</th><td>Sex, disability and county, with small-cell suppression where disclosure risk exists.</td></tr><tr><th>Verification</th><td>Standard tracer interview plus proportionate documentary or employer confirmation.</td></tr></tbody></table></div></section>
   <section className="practice"><h2>Guided practice</h2><ol><li>Select one outcome indicator from the Level 1 portfolio.</li><li>Write the management decision it should inform.</li><li>List every variable required to calculate and interpret it.</li><li>Define the population, unit, reference period and necessary disaggregation.</li><li>Identify one likely source and one quality or protection risk.</li></ol><p><b>Quality check:</b> Another practitioner should be able to understand what must be observed without seeing your questionnaire.</p></section>
   <section className="download"><h2>Professional working template</h2><p>Use the template to translate at least five indicators into explicit data requirements. Do not enter names, identity numbers, phone numbers or other personal records in the learning copy.</p><a href="/api/merl/level2/data-requirements-template" download>Download data-requirements template (.csv)</a></section>
   <section className="reflection"><h2>Reflection for practice</h2><p>Which variable in your current reporting system is collected routinely but rarely informs a decision? What cost or risk would be reduced by discontinuing or redesigning it?</p></section>
   <footer><a href="/merl/applied">← Level 2 overview</a><span>Next: 06.2 Select Sources, Methods and Frequency</span></footer>
  </article><aside className="rail"><b>Progression standard</b><ol><li>Define the decision.</li><li>Decompose the indicator.</li><li>Specify the population and period.</li><li>Document disaggregation and safeguards.</li></ol><p>Lesson 06.1 is formative until persistent Level 2 competency gates are deployed.</p></aside></div>
  <style>{`
   .lesson-shell{max-width:1160px;margin:auto;padding:32px 24px 60px;color:#0b2c4d;font-family:system-ui}.lesson-shell a{color:#1565c0}.lesson-shell a:focus-visible{outline:3px solid #f4a261;outline-offset:3px}.lesson-shell>header{margin:24px 0 30px;padding:36px;background:#0b2c4d;color:white;display:grid;grid-template-columns:1fr auto;gap:30px;border-radius:14px}.lesson-shell>header p{color:#f4a261;font-size:12px;font-weight:800;letter-spacing:1.4px}.lesson-shell>header h1{font:700 42px/1.08 Georgia,serif;margin:10px 0}.lesson-shell>header span{color:#d7e0e8;line-height:1.5}.lesson-shell>header aside{border-left:1px solid #ffffff35;padding-left:24px;display:flex;flex-direction:column;justify-content:center}.lesson-shell>header aside span{margin-top:8px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:30px}.layout article>section{margin-bottom:25px}.card,.practice,.download,.reflection{padding:22px;border:1px solid #d7dee7;border-radius:12px}.card,.reflection{background:#f6f8fb}.lesson-shell h2{font:700 28px Georgia,serif}.lesson-shell p,.lesson-shell li,.lesson-shell td{line-height:1.65}.principle{padding:18px;border-left:5px solid #f4a261;background:#fff4e8}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border:1px solid #d7dee7;text-align:left;vertical-align:top}thead th{background:#0b2c4d;color:white}.download a{display:inline-flex;min-height:44px;align-items:center;padding:9px 14px;border-radius:6px;background:#f4a261;color:#081f33;font-weight:800;text-decoration:none}.rail{height:max-content;position:sticky;top:24px;padding:22px;border-radius:12px;background:#0b2c4d;color:white}.rail li,.rail p{color:#d7e0e8}.lesson-shell footer{display:flex;justify-content:space-between;gap:18px;padding-top:20px;border-top:1px solid #d7dee7}.lesson-shell footer a{min-height:44px;display:flex;align-items:center}
   @media(max-width:800px){.layout{grid-template-columns:1fr}.rail{position:static}.lesson-shell>header{grid-template-columns:1fr}.lesson-shell>header aside{border-left:0;border-top:1px solid #ffffff35;padding:18px 0 0}}
   @media(max-width:520px){.lesson-shell{padding:20px 14px}.lesson-shell>header{padding:24px 18px}.lesson-shell>header h1{font-size:31px}.card,.practice,.download,.reflection{padding:16px}.lesson-shell footer{flex-direction:column}}
  `}</style>
 </main>
}
