'use client'

import Link from 'next/link'
import {useCallback,useEffect,useState} from 'react'
import {getDataScienceModuleOneState,getDataScienceQuiz,gradeDataScienceQuiz,markDataScienceLesson,submitDataScienceEvidence} from './actions'

const lessons=[
 ['1','What Data Science Is—and What It Is Not','Understand data science as a disciplined route from a consequential question to a defensible decision.'],
 ['2','Frame the Decision and Analytical Question','Translate an ambiguous management concern into measurable questions, outcomes and decision criteria.'],
 ['3','Navigate the Data Science Workflow','Plan an ethical, reproducible workflow from data acquisition through communication and learning.'],
]
type State={module_id:string;lesson_records:Record<string,boolean>;evidence_submission:{content:string;status:string;submitted_at:string}|null;quiz_score:number|null;quiz_passed:boolean;quiz_attempts:number;module_completed_at:string|null;module_02_unlocked:boolean}
type Quiz={question_id:string;question_order:number;stem:string;options:string[]}

export default function FoundationsExperience(){
 const[state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[evidence,setEvidence]=useState(''),[quiz,setQuiz]=useState<Quiz[]>([]),[answers,setAnswers]=useState<Record<string,string>>({})
 const refresh=useCallback(async()=>{const next=await getDataScienceModuleOneState();setState(next);setEvidence(next?.evidence_submission?.content??'');setLoading(false)},[])
 useEffect(()=>{refresh().catch(e=>{setError(e instanceof Error?e.message:'Unable to load progress.');setLoading(false)})},[refresh])
 async function run(key:string,fn:()=>Promise<unknown>,success:string){setBusy(key);setError('');setMessage('');try{await fn();await refresh();setMessage(success)}catch(e){setError(e instanceof Error?e.message:'The request failed.')}finally{setBusy('')}}
 const lessonsDone=lessons.every((_,i)=>!!state?.lesson_records?.[`01-${i}`]),competent=!!state?.module_completed_at
 const gateCount=lessons.filter((_,i)=>state?.lesson_records?.[`01-${i}`]).length+(state?.evidence_submission?1:0)+(state?.quiz_passed?1:0)
 return <main className="ds01-overview" aria-busy={loading||!!busy}>
  <a className="ds01-skip" href="#lesson-list">Skip to lessons</a><nav aria-label="Breadcrumb"><Link href="/data-science">Data Science pathway</Link><span aria-hidden="true"> / </span><span>Beginner</span><span aria-hidden="true"> / </span><span>Module 01</span></nav>
  <header><div><p>BEGINNER · MODULE 01</p><h1>Data, Decisions and the Data Science Workflow</h1><span>Learn to begin with a decision, translate it into an analytical question and follow a reproducible path from raw data to responsible action.</span></div><aside><b>{loading?'…':`${gateCount}/5`}</b><span>competency gates</span><b>{competent?'100%':state?.quiz_score===null||state?.quiz_score===undefined?'—':`${state.quiz_score}%`}</b><span>{competent?'COMPETENT':'best quiz score'}</span></aside></header>
  <div className="ds01-live" role="status" aria-live="polite">{busy?'Saving your progress…':message}</div>{error&&<div className="ds01-error" role="alert">{error}</div>}
  <section className="ds01-standard" aria-labelledby="module-outcome"><div><p>MODULE OUTCOME</p><h2 id="module-outcome">Frame a data science assignment before touching the software.</h2></div><p>By the end of this module, the learner should be able to produce a concise problem-framing brief that identifies the decision, users, analytical questions, evidence requirements, risks, limitations and success criteria.</p></section>
  <section id="lesson-list" className="ds01-lessons" aria-labelledby="lesson-heading"><div><p>LEARNING SEQUENCE</p><h2 id="lesson-heading">Complete and record all three lessons</h2></div><ol>{lessons.map(([id,title,description],i)=>{const done=!!state?.lesson_records?.[`01-${i}`];return <li key={id}><b>01.{id}</b><div><h3>{title}</h3><p>{description}</p></div><div className="ds01-lesson-actions"><Link href={`/data-science/foundations/01/${id}`}>Open lesson <span aria-hidden="true">→</span></Link><button type="button" disabled={loading||done||!!busy} onClick={()=>run(`lesson-${id}`,()=>markDataScienceLesson(i),`Lesson 01.${id} recorded.`)}>{done?'Recorded ✓':busy===`lesson-${id}`?'Saving…':'Record lesson'}</button></div></li>})}</ol></section>
  <section className="ds01-output"><div><p>PROFESSIONAL OUTPUT</p><h2>Data Science Problem-Framing Brief</h2><span>Submit a genuine professional brief after removing personal, confidential and restricted information. Your submission and timestamp persist with your learner record.</span></div><a href="/api/data-science/module-01/problem-framing-template" download>Download template (.csv)</a></section>
  <section className="ds01-submission" aria-labelledby="evidence-heading"><h2 id="evidence-heading">Professional-evidence submission</h2><label htmlFor="professional-evidence">Paste the completed problem-framing brief (100–20,000 characters).</label><textarea id="professional-evidence" rows={8} value={evidence} disabled={!!state?.evidence_submission} onChange={e=>setEvidence(e.target.value)} aria-describedby="evidence-help"/><small id="evidence-help">{evidence.trim().length.toLocaleString()} characters · Submit only after all lesson records are complete.</small><button type="button" disabled={!lessonsDone||!!state?.evidence_submission||!!busy||evidence.trim().length<100} onClick={()=>run('evidence',()=>submitDataScienceEvidence(evidence),'Professional evidence submitted and saved.')}>{state?.evidence_submission?'Submitted ✓':busy==='evidence'?'Submitting…':'Submit professional evidence'}</button></section>
  <section className="ds01-gate"><p>PROTECTED ASSESSMENT GATE</p><h2>{competent?'Module 01 competency achieved':'Pass the protected module quiz'}</h2><div><span><b>{lessons.filter((_,i)=>state?.lesson_records?.[`01-${i}`]).length}/3</b> lesson records</span><span><b>{state?.evidence_submission?'1/1':'0/1'}</b> professional brief</span><span><b>{state?.quiz_score===null||state?.quiz_score===undefined?'—':`${state.quiz_score}%`}</b> best score</span><span><b>{state?.quiz_attempts??0}/2</b> attempts</span></div><small>Pass mark 70%. Questions are sent without the answer key; grading and competency decisions occur in one protected database transaction.</small>
   {!competent&&state?.evidence_submission&&!quiz.length&&<button type="button" disabled={!!busy||(state?.quiz_attempts??0)>=2} onClick={()=>run('load-quiz',async()=>setQuiz(await getDataScienceQuiz()),'Quiz loaded. Select one answer for every question.')}>{busy==='load-quiz'?'Loading…':'Load Module 01 quiz'}</button>}
   {quiz.map(q=><fieldset key={q.question_id}><legend>{q.question_order}. {q.stem}</legend>{q.options.map((option,i)=><label key={option}><input type="radio" name={q.question_id} checked={answers[q.question_id]===String(i)} onChange={()=>setAnswers(v=>({...v,[q.question_id]:String(i)}))}/><span>{option}</span></label>)}</fieldset>)}
   {!!quiz.length&&!competent&&<button type="button" disabled={!!busy||quiz.some(q=>answers[q.question_id]===undefined)} onClick={()=>run('grade',async()=>{const result=await gradeDataScienceQuiz(answers);if(!result.ok)throw new Error(result.error);setQuiz([]);setAnswers({});setMessage(`Quiz score ${result.score}% · Attempt ${result.attempts}/2${result.passed?' · Module 02 unlocked.':''}`)},'Quiz graded and persisted.')}>{busy==='grade'?'Grading securely…':'Submit quiz for grading'}</button>}
  </section>
  <section className={`ds01-module-two ${state?.module_02_unlocked?'unlocked':'locked'}`} aria-labelledby="module-two-heading"><p>BEGINNER · MODULE 02</p><h2 id="module-two-heading">{state?.module_02_unlocked?'UNLOCKED':'LOCKED'} — Data Types, Structures and Quality</h2><span>{state?.module_02_unlocked?'All Module 01 competency gates have passed. Module 02 is ready.':'Complete all three lesson records, submit professional evidence and pass the protected quiz to unlock Module 02.'}</span>{state?.module_02_unlocked&&<Link className="ds01-open-next" href="/data-science/foundations/02">Open Module 02 <span aria-hidden="true">→</span></Link>}</section>
  <footer><Link href="/data-science">← Programme pathway</Link><Link href="/data-science/foundations/01/1">Open Lesson 01.1 →</Link></footer>
 </main>
}
