'use client'
import {useMemo,useState} from 'react'

type Out={kind:string;sequence:number;text?:string;table?:{columns:string[];rows:unknown[][]};chart?:{data?:string;url?:string;format?:string}}
const starter=`import pandas as pd\nimport io\n\n# MERL Foundations Lab — dataset is loaded as df\nprint("Rows:", len(df))\nprint("Enrolled:", int(df['enrolled'].sum()))\n\nenrolled = df[df['enrolled'] == 1]\ncompletion_rate = enrolled['completed_training'].mean()\ncompleters = df[df['completed_training'] == 1]\nemployment_rate = completers['employed_6m'].mean()\n\nsummary = pd.DataFrame({\n    'indicator': ['Training completion rate', '6-month employment rate among completers'],\n    'value': [completion_rate, employment_rate]\n})\nprint(summary)\nsummary\n`
export default function MerlLab(){
 const[code,setCode]=useState(starter),[outputs,setOutputs]=useState<Out[]>([]),[status,setStatus]=useState('Not run'),[running,setRunning]=useState(false),[error,setError]=useState('')
 const tables=useMemo(()=>outputs.filter(x=>x.kind==='table'&&x.table),[outputs]); const consoleText=useMemo(()=>outputs.filter(x=>['stdout','stderr','error'].includes(x.kind)).map(x=>x.text||'').join('\n'),[outputs])
 async function run(){setRunning(true);setError('');setOutputs([]);try{const csv=await (await fetch('/api/merl/level1/dataset')).text();const b64=btoa(unescape(encodeURIComponent(csv)));const r=await fetch('/api/executions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),caseId:'merl-foundations-001',language:'python',code,datasets:[{name:'MERL-DS-001-youth-employment.csv',contentBase64:b64}],limits:{timeoutMs:30000,memoryMb:512,cpuSeconds:20,maxOutputBytes:2000000,network:'disabled'}})});const a=await r.json();if(!r.ok)throw new Error(a?.error?.message||'Submission failed');setStatus(a.status||'queued');for(let i=0;i<30;i++){await new Promise(x=>setTimeout(x,500));const q=await fetch('/api/executions/'+encodeURIComponent(a.executionId),{cache:'no-store'});const z=await q.json();setStatus(z.status);if(z.outputs)setOutputs([...z.outputs].sort((x:Out,y:Out)=>x.sequence-y.sequence));if(['succeeded','failed','timed_out','cancelled'].includes(z.status)){if(z.status!=='succeeded')setError(z?.error?.message||z.status);return}}throw new Error('Execution polling timed out')}catch(e){setError(e instanceof Error?e.message:'Execution failed');setStatus('failed')}finally{setRunning(false)}}
 return <main style={{maxWidth:1200,margin:'0 auto',padding:24,fontFamily:'system-ui'}}><a href="/merl/foundations">← M&E Foundations</a><p style={{letterSpacing:2,fontSize:12,marginTop:24}}>DATALYTIQS ANALYTICS LAB · MERL-L1</p><h1>Youth Employment Results Lab</h1><p>Dataset: <b>MERL-DS-001</b> · privacy-safe synthetic records · automatically supplied to the isolated execution engine as <code>df</code>.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:18}}><section><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>analysis.py</h2><button onClick={run} disabled={running} style={{padding:'10px 16px'}}>{running?'Running…':'▶ Run Analysis'}</button></div><textarea value={code} onChange={e=>setCode(e.target.value)} spellCheck={false} style={{width:'100%',minHeight:520,fontFamily:'monospace',fontSize:14,padding:14}}/></section><section><h2>Results · {status}</h2>{error&&<pre style={{whiteSpace:'pre-wrap'}}>{error}</pre>}<h3>Console</h3><pre style={{minHeight:120,whiteSpace:'pre-wrap',padding:12,border:'1px solid #ddd'}}>{consoleText||'Run the analysis to inspect the programme.'}</pre><h3>Structured tables</h3>{tables.length?tables.map((o,i)=><div key={i} style={{overflowX:'auto'}}><table style={{borderCollapse:'collapse',width:'100%'}}><thead><tr>{o.table!.columns.map(c=><th key={c} style={{border:'1px solid #ddd',padding:6}}>{c}</th>)}</tr></thead><tbody>{o.table!.rows.map((r,j)=><tr key={j}>{r.map((v,k)=><td key={k} style={{border:'1px solid #ddd',padding:6}}>{String(v??'')}</td>)}</tr>)}</tbody></table></div>):<p>No structured table yet. Leave a DataFrame as the final expression.</p>}</section></div><section style={{marginTop:24,padding:20,border:'1px solid #ddd'}}><h2>Evidence task</h2><p>Calculate completion and six-month employment indicators. Then compare by sex and county. Record what the data show, what they do not establish, and which management question should be investigated next.</p></section></main>
}
