'use client'
import Link from 'next/link'
import {useMemo,useState} from 'react'
import './lesson.css'
type Lesson='1'|'2'|'3';type Check={prompt:string;options:string[];answer:number;feedback:string}
const info={
 '1':{title:'Profile Distributions and Missingness',duration:'50–65 minutes',outcomes:['Select summaries and plots appropriate to variable type and distribution.','Interpret centre, spread, shape and missingness together.','Recognise when the mean or complete-case summary is misleading.']},
 '2':{title:'Explore Relationships, Groups and Time',duration:'55–70 minutes',outcomes:['Compare groups using effect sizes, distributions and denominators.','Explore numerical and categorical relationships without asserting causation.','Identify seasonality, trend, structural breaks and time-dependent missingness.']},
 '3':{title:'Detect Anomalies and Communicate Findings',duration:'55–70 minutes',outcomes:['Distinguish data errors from valid rare observations.','Investigate anomalies using domain, source and temporal context.','Produce a reproducible EDA narrative that states uncertainty, limitations and next steps.']},
} as const
const checks:Record<Lesson,Check[]>={
 '1':[{prompt:'Income is strongly right-skewed with several legitimate high values. Which pair usually describes its typical value and spread most robustly?',options:['Mean and standard deviation','Median and interquartile range','Mode and file size','Minimum and maximum only'],answer:1,feedback:'Median and IQR are less dominated by extreme values; the full distribution should still be shown.'},{prompt:'Overall missingness is 4%, but one county has 31% missing. What should be reported?',options:['Only 4%','Both overall and disaggregated missingness, with implications','Replace all missing values with zero','Exclude the county silently'],answer:1,feedback:'Aggregate completeness can conceal systematic gaps that affect fairness and validity.'}],
 '2':[{prompt:'Two groups have different means, but one is much older. What is the most defensible exploratory conclusion?',options:['Group membership caused the difference','The observed difference may be confounded and requires adjusted analysis','Age is irrelevant','The larger mean proves programme impact'],answer:1,feedback:'EDA identifies patterns and plausible confounding; it does not establish causal effects.'},{prompt:'What should accompany a group percentage?',options:['A decorative icon','The numerator, denominator and relevant uncertainty or coverage information','Only two decimal places','A causal explanation'],answer:1,feedback:'Denominators expose small groups, missing cases and changing population composition.'}],
 '3':[{prompt:'A single extreme value is detected. What should happen first?',options:['Delete it automatically','Check source records, units, context and influence before deciding','Winsorise every variable','Call it fraud'],answer:1,feedback:'An anomaly may be an error, a rare valid event or an important signal; investigation precedes treatment.'},{prompt:'Which statement belongs in a defensible EDA conclusion?',options:['The correlation proves causation','Observed patterns, data limitations, alternative explanations and next tests','Only statistically significant findings','The preferred policy decision'],answer:1,feedback:'EDA should guide subsequent analysis while preserving uncertainty and competing explanations.'}],
}
const profiles=[['Categorical','Frequency, percentage and missing category','Bar chart; ordered when meaningful'],['Numerical symmetric','Mean, standard deviation, quantiles','Histogram, density and box plot'],['Numerical skewed','Median, IQR, quantiles and tail values','Histogram on appropriate scale; box or violin plot'],['Temporal','Coverage, frequency, gaps and lags','Time series with honest intervals'],['Identifier','Uniqueness, format and duplication','Exception table—not an average']]
export default function ModuleFourLesson({lesson}:{lesson:Lesson}){const[selected,setSelected]=useState<Record<number,number>>({});const score=useMemo(()=>checks[lesson].filter((q,i)=>selected[i]===q.answer).length,[lesson,selected]),current=info[lesson];return <main className="ds4-lesson"><nav aria-label="Breadcrumb"><Link href="/data-science">Data Science</Link> / <Link href="/data-science/foundations/04">Module 04</Link> / Lesson 04.{lesson}</nav><header><div><p>LESSON 04.{lesson} · {current.duration}</p><h1>{current.title}</h1><span>Beginner pathway · disciplined exploration before explanation.</span></div><aside><b>MODULE 04</b><span>Lesson {lesson} of 3</span></aside></header><div className="ds4-layout"><article><section className="ds4-card"><h2>Learning outcomes</h2><ul>{current.outcomes.map(x=><li key={x}>{x}</li>)}</ul></section>
 {lesson==='1'&&<><section><h2>Begin with structure, grain and coverage</h2><p>Confirm row and column counts, observational grain, key uniqueness, field types, periods and populations before calculating summaries. Then profile missingness by variable and by decision-relevant subgroup—not merely across the entire file.</p><div className="ds4-grid">{profiles.map(([type,summary,visual])=><div key={type}><h3>{type}</h3><p>{summary}</p><small>{visual}</small></div>)}</div></section><section className="ds4-callout"><h2>Centre without shape is incomplete</h2><p>Two datasets can share the same mean and have radically different distributions. Report spread, skewness, multimodality, floor or ceiling effects and influential tails. Averages are useful servants and terrible witnesses when called alone.</p></section><section><h2>Missingness is an analytical result</h2><p>Separate structurally inapplicable values from refusals, system failures and unknowns. Plot missingness across fields, groups and time. Before imputation, explain the mechanism you assume and test whether conclusions depend on that assumption.</p></section></>}
 {lesson==='2'&&<><section><h2>Compare distributions, not isolated averages</h2><p>For every group comparison, show sample size, denominator, centre, spread and the distribution where practical. Consider baseline differences, selection, missingness and unequal exposure. A visible difference may be important without being causal—or statistically precise without being useful.</p><div className="ds4-grid"><div><h3>Numeric × numeric</h3><p>Scatterplots, correlations and smoothers; examine nonlinearity and influential points.</p></div><div><h3>Categorical × numeric</h3><p>Grouped distributions, medians or means with denominators and uncertainty.</p></div><div><h3>Categorical × categorical</h3><p>Contingency tables, row or column percentages and residual patterns.</p></div><div><h3>Time × outcome</h3><p>Trend, seasonality, gaps, shocks and changing composition.</p></div></div></section><section className="ds4-callout"><h2>Association is not an intervention effect</h2><p>Confounding, reverse direction, selection and measurement can generate persuasive patterns. Phrase findings as observed associations and state which design or model would be needed to test the stronger claim.</p></section><section><h2>Time changes the rules</h2><ul><li>Sort records by a validated timestamp and define the reporting interval.</li><li>Mark policy changes, outages and collection redesigns.</li><li>Compare like periods and account for seasonality.</li><li>Do not randomly split time-dependent data for later prediction.</li><li>Check whether denominators and population composition changed.</li></ul></section></>}
 {lesson==='3'&&<><section><h2>Anomalies require investigation, not reflex deletion</h2><p>Use range rules, robust statistics, visual inspection and domain thresholds to identify candidates. Then inspect units, duplicates, source documents, data-entry history, neighbouring observations and real-world events. Record the decision to retain, correct, cap or exclude—and its effect on conclusions.</p><div className="ds4-process">{[['1','Detect','Use transparent rules and visuals.'],['2','Verify','Check source, unit, context and lineage.'],['3','Assess','Measure influence on summaries and decisions.'],['4','Treat','Retain or remediate with documented justification.']].map(([n,t,x])=><div key={n}><b>{n}</b><h3>{t}</h3><p>{x}</p></div>)}</div></section><section><h2>A professional EDA narrative</h2><ol><li>State the question, source, grain, population and period.</li><li>Document reproducible quality and missingness findings.</li><li>Present type-appropriate univariate profiles.</li><li>Explore planned relationships, groups and time.</li><li>Investigate anomalies and perform sensitivity checks.</li><li>Separate observations from interpretations and causal claims.</li><li>Recommend the next analysis, data repair or collection decision.</li></ol></section><section className="ds4-callout"><h2>Reproducibility standard</h2><p>Every table and figure should trace to a versioned source and executable transformation. Record software, code, filters, group definitions and exclusions.</p><a className="ds4-download" href="/api/data-science/module-04/eda-report-template" download>Download EDA report template (.csv)</a></section></>}
 <section className="ds4-practice"><h2>Guided knowledge check</h2>{checks[lesson].map((q,i)=><fieldset key={q.prompt}><legend>{i+1}. {q.prompt}</legend>{q.options.map((o,j)=><label key={o}><input type="radio" name={`q-${i}`} checked={selected[i]===j} onChange={()=>setSelected(v=>({...v,[i]:j}))}/><span>{o}</span></label>)}{selected[i]!==undefined&&<p role="status" className={selected[i]===q.answer?'correct':'review'}>{selected[i]===q.answer?'Correct. ':'Review this. '}{q.feedback}</p>}</fieldset>)}<p><b>Current score: {score}/{checks[lesson].length}</b></p></section><section className="ds4-apply"><h2>Apply it</h2><p>{lesson==='1'?'Profile five fields from a genuine dataset, including type, valid count, missingness, centre, spread, shape and the most appropriate visual.':lesson==='2'?'Explore one planned relationship across groups and time. Report denominators, potential confounders and at least two plausible explanations.':'Investigate three anomalies, record the evidence used to classify them and compare results before and after any justified treatment.'}</p></section><footer><Link href={lesson==='1'?'/data-science/foundations/04':`/data-science/foundations/04/${Number(lesson)-1}`}>← {lesson==='1'?'Module overview':'Previous lesson'}</Link><Link className="ds4-next" href={lesson==='3'?'/data-science/foundations/04':`/data-science/foundations/04/${Number(lesson)+1}`}>{lesson==='3'?'Return and record Lesson 04.3':'Continue to next lesson'} →</Link></footer></article><aside className="ds4-rail"><b>Progression standard</b><ol><li>Profile before modelling.</li><li>Show distributions and denominators.</li><li>Investigate anomalies.</li><li>State limitations and next tests.</li></ol><p>Return to the module overview to record the persistent lesson gate.</p></aside></div></main>}
