import '../../exam-hub.css'
const domains=[
['01','Prepare the data','Connect and profile analytical data; clean, transform and load with Power Query.'],
['02','Model the data','Design a semantic model; create DAX calculations and optimise the model.'],
['03','Visualize and analyze the data','Design usable analytical reports; analyse patterns and communicate insights.'],
['04','Manage and secure Power BI','Manage workspaces, assets and refresh; implement model and row-level security.']
]
export default function PL300Preview(){
 return <main className="exam-hub"><header className="exam-header"><a className="exam-brand" href="/exam-hub"><span>D</span><b>DatalytIQs</b><small>Exam Hub 2.0 Preview</small></a><nav><a href="#domains">Theory</a><a href="#practice">Practice</a><a href="#mock">Mock</a><a href="#readiness">Readiness</a></nav></header>
 <section className="topic-hero"><div><span className="exam-kicker">MICROSOFT · PL-300 · REFERENCE IMPLEMENTATION</span><h1>Power BI Data Analyst — complete preparation lifecycle</h1><p>Preview of the reusable DatalytIQs lifecycle: Learn → Quiz → Assignment → Practical → Question Bank → Timed Mock → Result → Evidence → Readiness → Remediation.</p></div><aside><span>IMPLEMENTATION</span><b>EXAM HUB 2.0</b><small>Original DatalytIQs preparation content</small></aside></section>
 <section className="exam-status"><article><span>THEORY</span><b>8 lessons</b><small>2 per verified domain</small></article><article><span>DOMAIN QUIZZES</span><b>4</b><small>16 original questions</small></article><article><span>PRACTICAL</span><b>4 + 4</b><small>Assignments + Lab activities</small></article><article><span>TIMED MOCK</span><b>100 min</b><small>Server-scored · 70% DatalytIQs threshold</small></article></section>
 <section className="exam-section" id="domains"><div className="exam-section-head"><div><span className="exam-kicker">SUBSTANTIVE THEORY</span><h2>Four-domain learning spine</h2></div><p>Each domain contains instruction, worked application, exam focus and a theory check.</p></div><div className="topic-list">{domains.map(d=><article className="topic-card" key={d[0]}><div className="topic-number">{d[0]}</div><div className="topic-content"><h3>{d[1]}</h3><p>{d[2]}</p><small>Theory → worked application → 4-item domain quiz → mapped practical evidence</small></div></article>)}</div></section>
 <section className="assessment-band" id="practice"><div className="exam-section-head inverse"><div><span className="exam-kicker">EVIDENCE PATH</span><h2>Theory is not treated as competence</h2></div><p>Each domain hands off to an existing assignment and Analytics Lab practical. Reviewed evidence contributes to readiness.</p></div><div className="assessment-grid"><article><span>LEARN</span><h3>Theory + Quiz</h3><p>Domain instruction and formative verification.</p></article><article><span>DEMONSTRATE</span><h3>Assignment + Practical</h3><p>Evidence-generating Power BI work.</p></article><article><span>VERIFY</span><h3>Review + Evidence</h3><p>Competency evidence is recorded only from assessed activity.</p></article></div></section>
 <section className="exam-section" id="mock"><div className="exam-section-head"><div><span className="exam-kicker">TIMED MOCK</span><h2>100-minute authenticated assessment</h2></div><p>16 original DatalytIQs exam-style items. Answer keys remain server-side in the private schema.</p></div><div className="exam-notice"><strong>Timer behaviour</strong><p>The attempt is server-timed, limited to three attempts, and automatically submits saved answers when time expires. Results include overall percentage and domain scores.</p></div></section>
 <section className="exam-section" id="readiness"><div className="exam-section-head"><div><span className="exam-kicker">READINESS ENGINE</span><h2>Evidence → diagnosis → targeted remediation</h2></div><p>Readiness combines available quiz coverage, reviewed practical performance, competency evidence and the latest timed mock.</p></div><div className="topic-list"><article className="topic-card"><div className="topic-number">R</div><div className="topic-content"><h3>Targeted remediation</h3><p>A mock domain below the 70% DatalytIQs threshold generates a recommendation to revisit its theory, repeat the domain quiz and complete or review the mapped practical before the next mock.</p></div></article></div></section>
 <section className="unlock-panel"><div><span className="exam-kicker">REUSABLE STANDARD</span><h2>One lifecycle, multiple professional papers</h2><p>The same architecture is designed for CA35P, DD31, DD32, DD24, CA15 and subsequent verified providers.</p></div><a className="exam-button primary" href="/exam-hub">Exam Hub catalogue</a></section></main>
}