import {redirect} from 'next/navigation'
import Link from 'next/link'
import {createClient} from '../../../lib/supabase/server'
import {confirmMinutesItem,delegateAction,reviewEvidence,submitActionEvidence} from '../minutes-actions'
import MinutesProcessForm from './minutes-process-form'
import '../ceo.css'
export const metadata={title:'Minutes Intelligence | DatalytIQs Executive Workspace',description:'Turn meeting minutes into executive briefs, confirmed decisions, delegated actions and evidence.'}
export default async function MinutesPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login?next=%2Fceo%2Fminutes')
 const{data:legacy}=await supabase.from('ceo_memberships').select('organisation_id,role,display_name').eq('user_id',user.id).eq('active',true).maybeSingle();if(!legacy)return <main className="ceo-access"><Link href="/ceo">← CEO Workspace</Link><h1>Executive access required.</h1></main>
 const{data:link}=await supabase.from('organization_legacy_links').select('organization_id').eq('legacy_ceo_organisation_id',legacy.organisation_id).maybeSingle();if(!link)return <main className="ceo-access"><Link href="/ceo">← CEO Workspace</Link><h1>Canonical organization link is not configured.</h1></main>
 const oid=link.organization_id
 const[{data:jobs},{data:items},{data:actions},{data:evidence},{data:members}]=await Promise.all([
  supabase.from('ceo_ai_jobs').select('id,created_at,result,source_document_id').eq('organization_id',oid).eq('job_type','minutes_intelligence').order('created_at',{ascending:false}).limit(5),
  supabase.from('ceo_decisions').select('id,title,decision_text,record_type,workflow_state,due_at,evidence_considered').eq('organization_id',oid).order('created_at',{ascending:false}).limit(30),
  supabase.from('ceo_actions').select('id,title,description,status,assigned_to,due_at').eq('organization_id',oid).order('created_at',{ascending:false}).limit(30),
  supabase.from('ceo_action_evidence').select('id,action_id,summary,external_url,review_status,created_at').eq('organization_id',oid).order('created_at',{ascending:false}).limit(30),
  supabase.from('organization_members').select('user_id,role,job_title,profiles:user_id(full_name,email)').eq('organization_id',oid).eq('status','active')
 ])
 const canLead=['ceo','executive'].includes(legacy.role);const myActions=(actions??[]).filter((a:any)=>a.assigned_to===user.id)
 return <main className="ceo"><section style={{maxWidth:1200,margin:'0 auto',padding:'32px'}}>
  <p>EXECUTIVE INTELLIGENCE WORKSPACE</p><h1>Minutes Intelligence</h1><p><Link href="/ceo">← Command Centre</Link></p><section className="ceo-panel"><MinutesProcessForm/></section>
  {canLead&&<section className="ceo-panel"><div className="ceo-heading"><p>UPLOAD MINUTES</p><h2>Turn meeting records into accountable execution</h2></div><MinutesProcessForm expanded/></section>}
  <section className="ceo-panel"><div className="ceo-heading"><p>EXECUTIVE BRIEF</p><h2>30-second and 2-minute views</h2></div>{jobs?.length?jobs.map((j:any)=><article key={j.id}><h3>{new Date(j.created_at).toLocaleString('en-KE')}</h3><b>30 seconds</b><p>{j.result?.brief_30_seconds||'No brief.'}</p><b>2 minutes</b><p>{j.result?.brief_2_minutes||'No extended brief.'}</p><small>{j.result?.decision_count??0} proposed decisions · {j.result?.action_count??0} proposed actions · {j.result?.fallback_used?'Deterministic fallback used':'Structured AI extraction'}</small></article>):<p>No minutes processed yet.</p>}</section>
  {canLead&&<section className="ceo-panel"><div className="ceo-heading"><p>HUMAN CONFIRMATION</p><h2>Proposed decisions and actions</h2></div>{items?.filter((x:any)=>x.workflow_state==='ai_generated').map((x:any)=><article key={x.id}><span>{x.record_type.replace('_',' ').toUpperCase()}</span><h3>{x.title}</h3><p>{x.decision_text}</p>{Array.isArray(x.evidence_considered)&&x.evidence_considered.length>0&&<small>Source: {x.evidence_considered.map((s:any)=>s.section||s.page||'document').join(', ')} · {x.evidence_considered[0]?.quote||''}</small>}<form action={confirmMinutesItem}><input type="hidden" name="item_id" value={x.id}/>{x.record_type==='proposed_action'&&<><label>Responsible officer<select name="assignee_id"><option value="">Confirm without assignee</option>{members?.map((m:any)=><option key={m.user_id} value={m.user_id}>{m.profiles?.full_name||m.profiles?.email||m.job_title||m.role} · {m.job_title||m.role}</option>)}</select></label><label>Due date<input name="due_at" type="datetime-local"/></label></>}<button type="submit">Confirm as organizational record</button></form></article>)}</section>}
  <section className="ceo-panel"><div className="ceo-heading"><p>DECISION REGISTER</p><h2>Approved organizational decisions</h2></div>{items?.filter((x:any)=>x.record_type==='decision'&&x.workflow_state==='approved').map((x:any)=><article key={x.id}><span>APPROVED</span><h3>{x.title}</h3><p>{x.decision_text}</p>{Array.isArray(x.evidence_considered)&&x.evidence_considered.length>0&&<small>Source: {x.evidence_considered.map((s:any)=>s.section||s.page||'document').join(', ')} · {x.evidence_considered[0]?.quote||''}</small>}{x.due_at&&<small>Due {new Date(x.due_at).toLocaleString('en-KE')}</small>}</article>)}</section>\n  {canLead&&<section className="ceo-panel"><div className="ceo-heading"><p>DELEGATION</p><h2>Assign confirmed actions</h2></div>{actions?.filter((a:any)=>!a.assigned_to).map((a:any)=><article key={a.id}><h3>{a.title}</h3><p>{a.description}</p><form action={delegateAction}><input type="hidden" name="action_id" value={a.id}/><label>Officer<select name="user_id" required><option value="">Select officer</option>{members?.map((m:any)=><option key={m.user_id} value={m.user_id}>{m.profiles?.full_name||m.profiles?.email||m.job_title||m.role} · {m.job_title||m.role}</option>)}</select></label><label>Due<input name="due_at" type="datetime-local"/></label><label>Delegation note<input name="note"/></label><button type="submit">Delegate</button></form></article>)}</section>}
  <section className="ceo-panel"><div className="ceo-heading"><p>MY ACTIONS</p><h2>Submit completion evidence</h2></div>{myActions.map((a:any)=><article key={a.id}><span>{a.status.toUpperCase()}</span><h3>{a.title}</h3><p>{a.description}</p>{!['approved','closed'].includes(a.status)&&<form action={submitActionEvidence}><input type="hidden" name="action_id" value={a.id}/><label>Evidence summary<textarea name="summary" minLength={10} required rows={3}/></label><label>Evidence link (optional)<input name="external_url" type="url"/></label><button type="submit">Submit evidence</button></form>}</article>)}</section>
  {canLead&&<section className="ceo-panel"><div className="ceo-heading"><p>CEO REVIEW</p><h2>Evidence awaiting judgement</h2></div>{evidence?.filter((e:any)=>e.review_status==='submitted').map((e:any)=><article key={e.id}><p>{e.summary}</p>{e.external_url&&<p>Evidence link recorded.</p>}<form action={reviewEvidence}><input type="hidden" name="evidence_id" value={e.id}/><input type="hidden" name="action_id" value={e.action_id}/><button name="verdict" value="accepted" type="submit">Accept evidence</button><button name="verdict" value="returned" type="submit">Return for action</button></form></article>)}</section>}
 </section></main>
}
