'use client'

import Link from 'next/link'
import {useCallback,useEffect,useState} from 'react'
import {getDataScienceModuleThreeQuiz,getDataScienceModuleThreeState,gradeDataScienceModuleThreeQuiz,markDataScienceModuleThreeLesson,submitDataScienceModuleThreeEvidence} from '../actions'

const lessons=[
 ['1','Choose Data Sources and Establish Provenance','Evaluate primary, secondary, administrative and open data against the decision and record their lineage.'],
 ['2','Design Collection Instruments and Field Controls','Translate variables into clear questions, identifiers, validation rules, sampling procedures and field protocols.'],
 ['3','Govern Privacy, Ethics, Security and Data Use','Apply lawful purpose, minimisation, access control, retention, consent and accountable sharing throughout the lifecycle.'],
]
type State={lesson_records:Record<string,boolean>;evidence_submission:{content:string;status:string;submitted_at:string}|null;quiz_score:number|null;quiz_passed:boolean;quiz_attempts:number;module_completed_at:string|null;module_04_unlocked:boolean}
type Quiz={question_id:string;question_order:number;stem:string;options:string[]}

export default function ModuleThreeExperience(){
 const[state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[evidence,setEvidence]=useState(''),[quiz,setQuiz]=useState<Quiz[]>([]),[answers,setAnswers]=useState<Record<string,string>>({})
 const refresh=useCallback(async()=>{const next=await getDataScienceModuleThreeState() as State;setState(next);setEvidence(next?.evidence_submission?.content??'');setLoading(false)},[])
 useEffect(()=>{refresh().catch(e=>{setError(e instanceof Error?e.message:'Unable to load progress.');setLoading(false)})},[refresh])
 async function run(key:string,fn:()=>Promise<unknown>,success:string){setBusy(key);setError('');setMessage('');try{await fn();await refresh();setMessage(success)}catch(e){setError(e instanceof Error?e.message:'The request failed.')}finally{setBusy('')}}
 const lessonsDone=lessons.every((_,i)=>!!state?.lesson_records?.[`03-${i}`]),competent=!!state?.module_completed_at,gates=lessons.filter((_,i)=>state?.lesson_records?.[`03-${i}`]).length+(state?.evidence_submission?1:0)+(state?.quiz_passed?1:0)
 return <main className="ds03" aria-busy={loading||!!busy}>
  <a className="ds03-skip" href="#ds03-lessons">Skip to lessons</a><nav aria-label="Breadcrumb"><Link href="/data-science">Data Science pathway</Link><span aria-hidden="true"> / </span><Link href="/data-science/foundations/02">Module 02</Link><span aria-hidden="true"> / </span><span>Module 03</span></nav>
  <header><div><p>BEGINNER · MODULE 03</p><h1>Data Collection, Sources and Governance</h1><span>Acquire the right data lawfully, document where it came from, and build controls that preserve meaning, quality and public trust.</span></div><aside><b>{loading?'…':`${gates}/5`}</b><span>competency gates</span><b>{competent?'100%':state?.quiz_score==null?'—':`${state.quiz_score}%`}</b><span>{competent?'COMPETENT':'best quiz score'}</span></aside></header>
  <div className="ds03-live" role="status" aria-live="polite">{busy?'Saving your progress…':message}</div>{error&&<div className="ds03-error" role="alert">{error}</div>}
  <section className="ds03-standard"><div><p>MODULE OUTCOME</p><h2>Produce a defensible Data Acquisition and Governance Plan.</h2></div><p>The completed plan should connect every requested field to a defined purpose, source, collection method, quality control, lawful basis, security classification, retention rule and accountable owner.</p></section>
  <section id="ds03-lessons" className="ds03-lessons"><div><p>LEARNING SEQUENCE</p><h2>Complete and record all three lessons</h2></div><ol>{lessons.map(([id,title,description],i)=>{const done=!!state?.lesson_records?.[`03-${i}`];return <li key={id}><b>03.{id}</b><div><h3>{title}</h3><p>{description}</p></div><div className="ds03-actions"><Link href={`/data-science/foundations/03/${id}`}>Open lesson →</Link><button type="button" disabled={loading||done||!!busy} onClick={()=>run(`lesson-${id}`,()=>markDataScienceModuleThreeLesson(i),`Lesson 03.${id} recorded.`)}>{done?'Recorded ✓':busy===`lesson-${id}`?'Saving…':'Record lesson'}</button></div></li>})}</ol></section>
  <section className="ds03-output"><div><p>PROFESSIONAL OUTPUT</p><h2>Data Acquisition and Governance Plan</h2><span>Use a genuine or supplied assignment, but remove personal, confidential and restricted information before submitting the plan.</span></div><a href="/api/data-science/module-03/data-acquisition-governance-template" download>Download template (.csv)</a></section>
  <section className="ds03-submission"><h2>Professional-evidence submission</h2><label htmlFor="ds03-evidence">Paste the completed plan (100–20,000 characters).</label><textarea id="ds03-evidence" rows={9} value={evidence} disabled={!!state?.evidence_submission} onChange={e=>setEvidence(e.target.value)} aria-describedby="ds03-help"/><small id="ds03-help">{evidence.trim().length.toLocaleString()} characters · Submission opens after all three lesson records.</small><button type="button" disabled={!lessonsDone||!!state?.evidence_submission||!!busy||evidence.trim().length<100} onClick={()=>run('evidence',()=>submitDataScienceModuleThreeEvidence(evidence),'Professional evidence submitted and saved.')}>{state?.evidence_submission?'Submitted ✓':busy==='evidence'?'Submitting…':'Submit professional evidence'}</button></section>
  <section className="ds03-gate"><p>PROTECTED ASSESSMENT GATE</p><h2>{competent?'Module 03 competency achieved':'Pass the protected module quiz'}</h2><div><span><b>{lessons.filter((_,i)=>state?.lesson_records?.[`03-${i}`]).length}/3</b> lessons</span><span><b>{state?.evidence_submission?'1/1':'0/1'}</b> governance plan</span><span><b>{state?.quiz_score==null?'—':`${state.quiz_score}%`}</b> best score</span><span><b>{state?.quiz_attempts??0}/2</b> attempts</span></div><small>Pass mark 70%. Questions are delivered without the answer key; grading and progression occur atomically in the protected database layer.</small>
   {!competent&&state?.evidence_submission&&!quiz.length&&<button type="button" disabled={!!busy||(state?.quiz_attempts??0)>=2} onClick={()=>run('load',async()=>setQuiz(await getDataScienceModuleThreeQuiz()),'Quiz loaded. Select one answer for every question.')}>{busy==='load'?'Loading…':'Load Module 03 quiz'}</button>}
   {quiz.map(q=><fieldset key={q.question_id}><legend>{q.question_order}. {q.stem}</legend>{q.options.map((option,i)=><label key={option}><input type="radio" name={q.question_id} checked={answers[q.question_id]===String(i)} onChange={()=>setAnswers(v=>({...v,[q.question_id]:String(i)}))}/><span>{option}</span></label>)}</fieldset>)}
   {!!quiz.length&&!competent&&<button type="button" disabled={!!busy||quiz.some(q=>answers[q.question_id]===undefined)} onClick={()=>run('grade',async()=>{const result=await gradeDataScienceModuleThreeQuiz(answers);if(!result.ok)throw new Error(result.error);setQuiz([]);setAnswers({});setMessage(`Quiz score ${result.score}% · Attempt ${result.attempts}/2${result.passed?' · Module 04 unlocked.':''}`)},'Quiz graded and persisted.')}>{busy==='grade'?'Grading securely…':'Submit quiz for grading'}</button>}
  </section>
  <section className={`ds03-next ${state?.module_04_unlocked?'unlocked':'locked'}`}><p>BEGINNER · MODULE 04</p><h2>{state?.module_04_unlocked?'UNLOCKED':'LOCKED'} — Exploratory Data Analysis</h2><span>{state?.module_04_unlocked?'All Module 03 competency gates have passed. Module 04 is unlocked and will be developed next.':'Complete all Module 03 gates to unlock Module 04.'}</span></section>
  <footer><Link href="/data-science/foundations/02">← Module 02</Link><Link href="/data-science/foundations/03/1">Open Lesson 03.1 →</Link></footer>
 </main>
}
