'use client'
import {useMemo,useState} from 'react'

type Lesson='1'|'2'|'3'
type Check={prompt:string;options:string[];answer:number;feedback:string}
const content={
 '1':{title:'System Architecture and Data Flow',duration:'50–60 minutes',outcomes:['Map data from source to decision.','Assign ownership, validation and approval at each hand-off.','Design access, retention, recovery and interoperability controls.']},
 '2':{title:'Reporting, Visualisation and Access',duration:'50–65 minutes',outcomes:['Match reporting products to decisions and users.','Choose visual forms that preserve denominators and uncertainty.','Specify accessible, secure and role-appropriate information access.']},
 '3':{title:'Specify a Useful Monitoring System',duration:'60–75 minutes',outcomes:['Integrate requirements, workflows, controls and reporting into one specification.','Define service levels, governance and change control.','Test whether the proposed system produces timely action rather than decorative reporting.']},
} as const
const checks:Record<Lesson,Check[]>={
 '1':[
  {prompt:'What is the strongest starting point for system architecture?',options:['A preferred dashboard colour','The decision, indicator definitions and accountable users','The most expensive software','Every field anyone might someday want'],answer:1,feedback:'Architecture should follow decisions, defined data requirements and accountable workflows.'},
  {prompt:'What should every data hand-off specify?',options:['Only the file name','Owner, format, timing, validation, approval and failure response','A verbal promise','Unlimited access'],answer:1,feedback:'Explicit hand-offs prevent silent gaps between collection, review, aggregation and use.'},
 ],
 '2':[
  {prompt:'A dashboard shows 80% without numerator, denominator or period. What is missing?',options:['A gradient','Essential interpretive context','More animation','A logo'],answer:1,feedback:'Users need the count, denominator, reference period and definition to interpret a percentage responsibly.'},
  {prompt:'Which access design is strongest?',options:['Everyone is an administrator','Least privilege with documented roles, review and revocation','One shared password','Public links for convenience'],answer:1,feedback:'Role-based least privilege reduces exposure while preserving authorised use.'},
 ],
 '3':[
  {prompt:'Which metric best tests whether a monitoring system is useful?',options:['Number of charts','Percentage of due decisions receiving accepted evidence on time','Database size','Number of colours'],answer:1,feedback:'Usefulness is demonstrated when reliable evidence reaches an accountable decision within the required window.'},
  {prompt:'How should a changed indicator definition be deployed?',options:['Overwrite history silently','Approve, version, communicate, migrate and document comparability','Let each county interpret it','Change only the chart title'],answer:1,feedback:'Controlled change protects historical comparability and ensures every producer applies the same definition.'},
 ],
}
const flow=[
 ['Source','Training register and follow-up interview','Programme and field teams','Capture at point of service; consent and validation'],
 ['Ingestion','Approved form/API import','Data manager','Schema, duplicate, malware and completeness checks'],
 ['Review','Exception and reconciliation queue','County MERL officer','Resolve queries with an auditable correction trail'],
 ['Repository','Versioned analytical dataset','System owner','Encryption, backups, retention and role-based access'],
 ['Reporting','Decision brief and dashboard','Analyst / accountable manager','Definitions, denominators, dates and uncertainty displayed'],
 ['Action','Assigned decision log','Programme director','Decision, owner, due date and follow-up result recorded'],
]
export default function LessonExperience({lesson}:{lesson:Lesson}){
 const info=content[lesson], [selected,setSelected]=useState<Record<number,number>>({})
 const score=useMemo(()=>checks[lesson].filter((item,index)=>selected[index]===item.answer).length,[lesson,selected])
 return <main className="lesson-shell">
  <nav aria-label="Breadcrumb"><a href="/merl/applied">MERL Level 2</a><span aria-hidden="true"> / </span><span>Module 10</span><span aria-hidden="true"> / </span><span>Lesson 10.{lesson}</span></nav>
  <header><div><p>LESSON 10.{lesson} · {info.duration}</p><h1>{info.title}</h1><span>County Youth Employment Programme · connect governed data flows to decisions, action and learning.</span></div><aside><b>MODULE 10</b><span>Lesson {lesson} of 3</span></aside></header>
  <div className="layout"><article>
   <section className="card"><h2>Learning outcomes</h2><ul>{info.outcomes.map(outcome=><li key={outcome}>{outcome}</li>)}</ul></section>
   {lesson==='1'&&<><section><h2>Map the complete evidence chain</h2><p>A monitoring system includes people, definitions, procedures, controls and decisions—not merely software. Map how a record moves, who is accountable at each hand-off, what can fail and how recovery works.</p><div className="table-wrap"><table><thead><tr><th>Layer</th><th>Example</th><th>Owner</th><th>Control</th></tr></thead><tbody>{flow.map(row=><tr key={row[0]}><th>{row[0]}</th><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td></tr>)}</tbody></table></div></section><section className="principle"><b>One source of governed truth</b><p>Define system-of-record ownership and reconciliation rules. Two dashboards agreeing with themselves can still disagree with reality.</p></section></>}
   {lesson==='2'&&<><section><h2>Design backwards from the decision</h2><p>Executives may need exceptions and trends; operational managers need named actions and deadlines; analysts need documented extracts and metadata. Every product should state source, definition, numerator, denominator, period, refresh time and limitations.</p><div className="concept-grid"><div><h3>Signal</h3><p>Show status, trend, target and material variation without visual distortion.</p></div><div><h3>Diagnosis</h3><p>Enable authorised disaggregation and comparison to locate the problem.</p></div><div><h3>Action</h3><p>Record the decision, owner, due date and later result.</p></div></div></section><section className="principle"><b>Accessible by design</b><p>Use semantic headings, keyboard operation, sufficient contrast, text alternatives and formats that work on small screens and low bandwidth. Access also means knowing who must not see identifiable data.</p></section></>}
   {lesson==='3'&&<><section><h2>A specification makes promises testable</h2><p>Define scope, users, decisions, data model, workflow, validation, integrations, roles, service levels, backups, incident response, retention, reporting, support and controlled change. Each requirement should have an owner and acceptance test.</p><div className="practice"><h3>Acceptance example</h3><p>“By 10:00 on the sixth working day, authorised county managers can view accepted monthly completeness by sex and disability status; every value exposes its numerator, denominator, period and last refresh time.” This can be tested. “Provide a modern dashboard” cannot.</p></div></section><section className="principle"><b>Close the learning loop</b><p>A monitoring system is incomplete until it records what decision followed, who acted and whether the result improved. Reporting without response is organised observation.</p></section></>}
   <section className="practice"><h2>Guided knowledge check</h2>{checks[lesson].map((item,index)=><fieldset key={item.prompt}><legend>{index+1}. {item.prompt}</legend>{item.options.map((option,optionIndex)=><label key={option}><input type="radio" name={`check-${index}`} checked={selected[index]===optionIndex} onChange={()=>setSelected(current=>({...current,[index]:optionIndex}))}/><span>{option}</span></label>)}{selected[index]!==undefined&&<p role="status" aria-live="polite" className={selected[index]===item.answer?'correct':'incorrect'}>{selected[index]===item.answer?'Correct. ':'Review this. '}{item.feedback}</p>}</fieldset>)}<p><b>Current score: {score}/{checks[lesson].length}</b></p></section>
   {lesson==='3'&&<section className="download"><h2>Professional submission standard</h2><p>Submit a monitoring-system specification covering decisions, data flow, ownership, quality, security, reporting, accessibility, service levels and acceptance tests. Use synthetic architecture and de-identified examples.</p><a href="/api/merl/level2/monitoring-system-template" download>Download monitoring-system specification (.csv)</a></section>}
   <section className="reflection"><h2>Reflection for practice</h2><p>{lesson==='1'?'At which hand-off does evidence most often become late, altered or orphaned in your current system?':lesson==='2'?'Which dashboard element looks informative but cannot support a defensible decision?':"What single acceptance test would expose whether your proposed monitoring system is genuinely useful?"}</p></section>
   <footer><a href={lesson==='1'?'/merl/applied':`/merl/applied/10/${Number(lesson)-1}`}>← {lesson==='1'?'Level 2 overview':'Previous lesson'}</a><a className="next" href={lesson==='3'?'/merl/applied':`/merl/applied/10/${Number(lesson)+1}`}>{lesson==='3'?'Return to Level 2 overview':'Continue to next lesson'} →</a></footer>
  </article><aside className="rail"><b>Progression standard</b><ol><li>Map governed data flow.</li><li>Design for decisions and access.</li><li>Specify measurable services.</li><li>Record action and learning.</li></ol><p>Module 10 feedback is formative until persistent Level 2 competency gates are deployed.</p></aside></div>
  <style jsx global>{`
   .lesson-shell{max-width:1160px;margin:auto;padding:32px 24px 60px;color:#0b2c4d;font-family:system-ui}.lesson-shell a{color:#1565c0}.lesson-shell a:focus-visible,.lesson-shell input:focus-visible{outline:3px solid #f4a261;outline-offset:3px}.lesson-shell>header{margin:24px 0 30px;padding:36px;background:#0b2c4d;color:white;display:grid;grid-template-columns:1fr auto;gap:30px;border-radius:14px}.lesson-shell>header p{color:#f4a261;font-size:12px;font-weight:800;letter-spacing:1.4px}.lesson-shell>header h1{font:700 42px/1.08 Georgia,serif;margin:10px 0}.lesson-shell>header span{color:#d7e0e8;line-height:1.5}.lesson-shell>header aside{border-left:1px solid #ffffff35;padding-left:24px;display:flex;flex-direction:column;justify-content:center}.lesson-shell>header aside span{margin-top:8px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:30px}.layout article>section{margin-bottom:25px}.card,.practice,.download,.reflection,.principle{padding:22px;border:1px solid #d7dee7;border-radius:12px}.card,.reflection{background:#f6f8fb}.principle{border-left:5px solid #f4a261;background:#fff4e8}.lesson-shell h2{font:700 28px Georgia,serif}.lesson-shell p,.lesson-shell li,.lesson-shell td{line-height:1.65}.concept-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.concept-grid>div{padding:18px;border-top:4px solid #f4a261;background:#f6f8fb}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border:1px solid #d7dee7;text-align:left;vertical-align:top}thead th{background:#0b2c4d;color:white}.practice fieldset{margin:16px 0;padding:16px;border:1px solid #d7dee7;border-radius:10px}.practice legend{font-weight:700}.practice label{display:flex;gap:9px;min-height:44px;align-items:center}.correct,.incorrect{padding:12px;border-radius:8px}.correct{background:#e8f5ee;color:#175d43}.incorrect{background:#fff4e8;color:#7a430d}.download a,.next{display:inline-flex;min-height:44px;align-items:center;padding:9px 14px;border-radius:6px;background:#f4a261;color:#081f33!important;font-weight:800;text-decoration:none}.rail{height:max-content;position:sticky;top:24px;padding:22px;border-radius:12px;background:#0b2c4d;color:white}.rail li,.rail p{color:#d7e0e8}.lesson-shell footer{display:flex;justify-content:space-between;gap:18px;padding-top:20px;border-top:1px solid #d7dee7}.lesson-shell footer a{min-height:44px;display:flex;align-items:center}
   @media(max-width:800px){.layout{grid-template-columns:1fr}.rail{position:static}.concept-grid{grid-template-columns:1fr}.lesson-shell>header{grid-template-columns:1fr}.lesson-shell>header aside{border-left:0;border-top:1px solid #ffffff35;padding:18px 0 0}}
   @media(max-width:520px){.lesson-shell{padding:20px 14px}.lesson-shell>header{padding:24px 18px}.lesson-shell>header h1{font-size:31px}.card,.practice,.download,.reflection,.principle{padding:16px}.lesson-shell footer{flex-direction:column}.lesson-shell footer a{justify-content:center}}
  `}</style>
 </main>
}
