import type { Metadata } from 'next'
import { createAdminClient } from '../../lib/supabase/admin'
import './exam-hub.css'

export const metadata: Metadata = {title:'Professional Exam Preparation | DatalytIQs Exam Hub',description:'Professional examination preparation with structured study, practical analytics, mocks and measurable readiness.',alternates:{canonical:'https://datalytiqs-analytics-lab.vercel.app/exam-hub'}}
type Programme={id:string;code:string;title:string;description:string|null;status:string;metadata:Record<string,any>;exam_bodies:{code:string;name:string}|Array<{code:string;name:string}>}
const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
const bodyOf=(p:Programme)=>Array.isArray(p.exam_bodies)?p.exam_bodies[0]:p.exam_bodies

export default async function ExamHubPage({searchParams}:{searchParams:Promise<{q?:string;body?:string;qualification?:string;status?:string}>}){
 const query=await searchParams; let data:Programme[]=[]; let unavailable=false
 try{const admin=createAdminClient();const r=await admin.from('exam_programmes').select('id,code,title,description,status,metadata,exam_bodies!inner(code,name)').order('code');if(r.error)throw r.error;data=(r.data||[]) as Programme[]}catch{unavailable=true}
 let programmes=[...data];const q=(query.q||'').trim().toLowerCase()
 if(q)programmes=programmes.filter(p=>[p.code,p.title,p.metadata?.qualification,bodyOf(p)?.name].some(v=>String(v||'').toLowerCase().includes(q)))
 if(query.body)programmes=programmes.filter(p=>bodyOf(p)?.code===query.body)
 if(query.qualification)programmes=programmes.filter(p=>p.metadata?.qualification===query.qualification)
 if(query.status)programmes=programmes.filter(p=>p.metadata?.implementation_status===query.status)
 const qualifications=[...new Set(data.map(p=>String(p.metadata?.qualification||'')).filter(Boolean))].sort(),statuses=[...new Set(data.map(p=>String(p.metadata?.implementation_status||'')).filter(Boolean))].sort(),bodies=[...new Map(data.map(p=>[bodyOf(p)?.code,bodyOf(p)])).values()].filter(Boolean)
 return <main className="exam-hub"><header className="exam-header"><a className="exam-brand" href="/"><span>D</span><b>DatalytIQs</b><small>Professional Exam Hub</small></a><nav><a href="/exam-hub">Catalogue</a><a href="/preview/pl300">PL-300 Preview</a><a href="/">Analytics Lab</a><a href="https://datalytiqsacademy.com/">Academy</a></nav></header>
 <section className="exam-hero"><div><span className="exam-kicker">DATALYTIQS EXAM HUB</span><h1>Prepare. Practise. Analyse. <em>Pass with Evidence.</em></h1><p>Structured professional examination preparation combining theory, practical analytics, examination-style exercises, timed mocks and measurable readiness.</p><div className="exam-actions"><a className="exam-button primary" href={unavailable?"/preview/pl300":"#catalogue"}>{unavailable?'Open PL-300 preview':'Explore professional papers'}</a></div></div><aside><div><b>{unavailable?'Preview':data.length}</b><span>{unavailable?'safe mode':'catalogued papers'}</span></div><div><b>{unavailable?'No secrets':bodies.length}</b><span>{unavailable?'privileged data stays protected':'examining bodies'}</span></div><div><b>Evidence</b><span>readiness model</span></div></aside></section>
 {unavailable?<section className="exam-section"><div className="exam-section-head"><div><span className="exam-kicker">PREVIEW ENVIRONMENT</span><h2>Catalogue data is intentionally unavailable here</h2></div><p>This branch preview does not receive the production Supabase service-role credential. The application now degrades safely instead of returning a server error.</p></div><div className="exam-notice"><strong>PL-300 Exam Hub 2.0 is available for review.</strong><p>Inspect the theory → quiz → assignment → practical → timed mock → evidence → readiness → remediation design without exposing production credentials.</p><a className="exam-button primary" href="/preview/pl300">Open PL-300 lifecycle preview</a></div></section>:
 <section className="exam-section" id="catalogue"><div className="exam-section-head"><div><span className="exam-kicker">PROFESSIONAL EXAMINATION CATALOGUE</span><h2>Find a paper</h2></div><p>Catalogue presence does not mean a preparation pathway is complete.</p></div><form method="get" className="study-plan-bar"><label>Search<input name="q" defaultValue={query.q||''}/></label><label>Examining body<select name="body" defaultValue={query.body||''}><option value="">All</option>{bodies.map((b:any)=><option key={b.code} value={b.code}>{b.name}</option>)}</select></label><label>Qualification<select name="qualification" defaultValue={query.qualification||''}><option value="">All</option>{qualifications.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>Status<select name="status" defaultValue={query.status||''}><option value="">All</option>{statuses.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><button>Apply filters</button></form><div className="competency-grid">{programmes.map(p=>{const b=bodyOf(p),qualification=String(p.metadata?.qualification||'Professional examination'),implementation=String(p.metadata?.implementation_status||'PLANNED'),route=p.code==='CA35P'?'/exam-hub/ca35p':`/exam-hub/papers/${slug(b?.code||'body')}/${slug(qualification)}/${p.code.toLowerCase()}`;return <article key={p.id}><span>{b?.code} · {qualification}</span><h3>{p.code} — {p.title}</h3><p>{p.description||'Structured examination preparation pathway.'}</p><p><b>{implementation.replaceAll('_',' ')}</b></p><a href={route}>Explore Paper →</a></article>})}</div></section>}
 <section className="unlock-panel"><div><span className="exam-kicker">INDEPENDENT PREPARATION PLATFORM</span><h2>Official requirements remain authoritative</h2><p>DatalytIQs is an independent professional learning and examination-preparation platform.</p></div><a className="exam-button primary" href="/preview/pl300">Review PL-300</a></section></main>
}