export type YALesson={
 code:string;track:string;module:string;title:string;minutes:number;
 objectives:string[];concepts:string[];workedExample:string;guidedPractice:string;
 challenge:string;qa:string[];reflection:string;
}
export const youngAnalystLessons:YALesson[]=[
 {code:'EDL-01.1',track:'excel-data-literacy',module:'EDL-01',title:'Rows, Columns and Meaning',minutes:40,objectives:['Identify observation and variable','Distinguish label from value'],concepts:['One row should represent one observational unit','A column should represent one variable','Headers describe meaning, not decoration'],workedExample:'In a club table, each row is one club-week observation; registered and attended are separate numeric variables.',guidedPractice:'Label the observation unit and variables in YA-D01.',challenge:'Reshape a poorly organised mini-table into tidy rows and columns.',qa:['Check every row has the same unit','Check each column has one meaning'],reflection:'What ambiguity did restructuring remove?'},
 {code:'EDL-02.1',track:'excel-data-literacy',module:'EDL-02',title:'Clean Without Losing Evidence',minutes:50,objectives:['Profile data defects','Document transformations'],concepts:['Preserve an original copy','Standardise equivalent categories','Do not silently delete inconvenient records'],workedExample:'Data, data and DATA can be mapped to one documented category while retaining all observations.',guidedPractice:'Create a defect log: field, issue, action, reason.',challenge:'Clean a synthetic attendance register and reconcile row counts.',qa:['Rows before = rows after unless exclusions are justified','Category counts reconcile'],reflection:'Which cleaning choice required judgement?'},
 {code:'EDL-03.1',track:'excel-data-literacy',module:'EDL-03',title:'Formulas as Transparent Rules',minutes:50,objectives:['Write auditable formulas','Verify calculations independently'],concepts:['A formula should encode the intended rule','Rates need explicit denominators','Spot-check formulas with hand calculations'],workedExample:'Attendance rate = attended/registered; 18/24 = 75%.',guidedPractice:'Calculate three YA-D01 rates by hand before entering formulas.',challenge:'Build rate and flag formulas and verify two rows independently.',qa:['Formula references correct cells','Percent formatting does not change underlying value'],reflection:'How do you know the formula is correct rather than merely plausible?'},
 {code:'EDL-05.1',track:'excel-data-literacy',module:'EDL-05',title:'Charts that Answer Questions',minutes:50,objectives:['Match chart to question','Detect misleading visual choices'],concepts:['Bars compare categories','Lines emphasise ordered change','Axes and denominators affect interpretation'],workedExample:'Compare club attendance rates with a bar chart rather than raw attendance counts.',guidedPractice:'Write the question above each proposed chart.',challenge:'Create one comparison chart and one time-pattern chart from YA-D01.',qa:['Title states measure','Rate chart uses comparable denominator'],reflection:'What visual choice could have changed the reader’s impression?'},

 {code:'STA-02.1',track:'statistics',module:'STA-02',title:'Mean, Median and Context',minutes:50,objectives:['Calculate centre','Choose a useful summary'],concepts:['Mean uses every value','Median is the ordered middle','Context determines usefulness'],workedExample:'For 2,4,9 the mean is 5 and median is 4; the larger value pulls the mean upward.',guidedPractice:'Calculate mean and median for YA-D02 study minutes.',challenge:'Add one extreme observation and compare the change in both summaries.',qa:['Recalculate total and count','Order values before median'],reflection:'Which summary changed more and why?'},
 {code:'STA-04.1',track:'statistics',module:'STA-04',title:'Fair Comparisons Need Denominators',minutes:50,objectives:['Calculate rates','Avoid raw-count comparison traps'],concepts:['A numerator needs its denominator','Percentages support comparison across unequal group sizes','Small denominators can produce unstable rates'],workedExample:'18 of 24 = 75%; 14 of 20 = 70%. The larger raw count and larger rate happen to agree here, but not always.',guidedPractice:'Construct an example where higher attendance count has lower attendance rate.',challenge:'Compare all YA-D01 club-week rates and write two bounded findings.',qa:['Show numerator and denominator','Check percentage calculation'],reflection:'Why can raw counts mislead?'},
 {code:'STA-05.1',track:'statistics',module:'STA-05',title:'Samples, Frames and Bias',minutes:55,objectives:['Identify target population and frame','Diagnose selection bias'],concepts:['A large biased sample can still mislead','Coverage matters','Random selection cannot fix a frame that excludes groups'],workedExample:'Surveying only analytics-club members cannot represent all learners if club membership relates to the topic.',guidedPractice:'Critique convenience, volunteer and broad-frame sampling scenarios.',challenge:'Redesign a biased synthetic school survey sample.',qa:['Population explicitly defined','Frame coverage checked'],reflection:'What group might still be missing?'},

 {code:'RES-01.1',track:'research',module:'RES-01',title:'Questions Built for Decisions',minutes:50,objectives:['Narrow a broad issue','Specify measurable outcome and period'],concepts:['Research starts with intended use','Questions should be answerable with feasible evidence','Avoid embedding the desired conclusion'],workedExample:'Replace “Why is the library bad?” with “What proportion of sampled learners used the library at least once last week?”',guidedPractice:'Rewrite three vague school questions.',challenge:'Create a question-purpose-decision triad.',qa:['Question has measurable concept','Decision use does not predetermine result'],reflection:'What evidence would change the eventual decision?'},
 {code:'RES-03.1',track:'research',module:'RES-03',title:'Questions that Do Not Push the Answer',minutes:55,objectives:['Detect leading and double-barrelled items','Design usable response options'],concepts:['Neutral wording reduces measurement error','One item should ask one thing','Options should fit the construct'],workedExample:'“How excellent was our helpful club?” is leading; ask a neutral satisfaction item instead.',guidedPractice:'Diagnose five flawed items.',challenge:'Repair a five-question mini-survey and justify each revision.',qa:['No loaded adjectives','No two constructs in one item'],reflection:'Which flaw was hardest to detect?'},
 {code:'RES-06.1',track:'research',module:'RES-06',title:'Pilot Before You Estimate',minutes:55,objectives:['Use pilot data to improve an instrument','Separate pilot findings from population estimates'],concepts:['Pilot tests process and measurement','Missing/odd responses are diagnostic evidence','Small pilot results should not be generalised'],workedExample:'YA-D03 has five synthetic responses: enough to inspect whether questions work, not to estimate all learners’ views.',guidedPractice:'List instrument defects suggested by YA-D03.',challenge:'Produce a pilot revision log with keep/change/remove decisions.',qa:['Every revision cites evidence','No population claim from pilot'],reflection:'What did the pilot teach about the instrument rather than the population?'},

 {code:'AIL-01.1',track:'ai-literacy',module:'AIL-01',title:'Generated Is Not Verified',minutes:45,objectives:['Separate fluency from evidence','Classify verification need'],concepts:['AI output can be plausible and wrong','Confidence is not provenance','Consequential claims need independent evidence'],workedExample:'A precise statistic without a traceable source remains unverified.',guidedPractice:'Classify ten outputs: creative, low-stakes factual, consequential factual.',challenge:'Annotate an AI answer as verified/unsupported/contradicted/opinion.',qa:['Claim matched to evidence','Unsupported precision flagged'],reflection:'Which claim initially sounded trustworthy but lacked evidence?'},
 {code:'AIL-03.1',track:'ai-literacy',module:'AIL-03',title:'Verification Workflow',minutes:55,objectives:['Trace claims to evidence','Check context and denominator'],concepts:['Verify the claim, not merely the topic','Check date, population and denominator','Independent evidence is stronger than model repetition'],workedExample:'If AI says “75% attended,” verify that 18/24 is the relevant numerator/denominator and period.',guidedPractice:'Verify three supplied claims against a synthetic source table.',challenge:'Create a claim-verification log for an intentionally flawed response.',qa:['Source actually supports claim','Population/time match'],reflection:'What kind of mismatch was easiest to overlook?'},
 {code:'AIL-05.1',track:'ai-literacy',module:'AIL-05',title:'Privacy and Responsible Assistance',minutes:50,objectives:['Minimise data in prompts','Disclose meaningful AI assistance'],concepts:['Do not expose credentials/private learner records','Transform or synthesise data when possible','Human remains responsible for submitted work'],workedExample:'Use synthetic rows to debug a formula instead of pasting identifiable learner records.',guidedPractice:'Sort sample information into safe / transform first / do not enter.',challenge:'Create a responsible-use checklist for a school analytics task.',qa:['Purpose requires each field','Disclosure states meaningful AI role'],reflection:'What information could be removed without reducing usefulness?'},

 {code:'DAT-01.1',track:'data-analytics-teens',module:'DAT-01',title:'Start with the Decision',minutes:55,objectives:['Frame an analytical question','Define unit and success criteria'],concepts:['Question precedes tool','Define intended user','State non-goals to control scope'],workedExample:'“Where might resource availability constrain club participation?” is narrower than “Analyse the school.”',guidedPractice:'Write decision, user, question, unit, measure and non-goal for YA-D04.',challenge:'Produce a one-page analysis charter.',qa:['Measures answer question','Non-goal prevents overreach'],reflection:'What tempting analysis did you deliberately exclude?'},
 {code:'DAT-02.1',track:'data-analytics-teens',module:'DAT-02',title:'Profile, Clean, Reconcile',minutes:60,objectives:['Profile structure and quality','Maintain a reproducible QA log'],concepts:['Count before changing','Document derived fields','Reconcile after transformations'],workedExample:'Before calculating devices/member, verify members is non-zero and preserve original columns.',guidedPractice:'Profile YA-D04 fields and possible validation rules.',challenge:'Create a cleaning/QA log and two derived measures.',qa:['Row count reconciled','Derived formulas documented'],reflection:'Which quality check protects interpretation most?'},
 {code:'DAT-04.1',track:'data-analytics-teens',module:'DAT-04',title:'Compare without Overclaiming',minutes:60,objectives:['Compare rates fairly','Separate observation from explanation'],concepts:['Use appropriate denominators','Pattern is not mechanism','Alternative explanations matter'],workedExample:'Clubs with fewer devices/member may show lower completion in YA-D04, but this does not establish device causation.',guidedPractice:'Calculate completion and devices/member for every row.',challenge:'Write observation, possible explanation, alternative explanation and next evidence needed.',qa:['Numbers verified','Causal language avoided'],reflection:'What additional evidence would strengthen the explanation?'},
 {code:'DAT-06.1',track:'data-analytics-teens',module:'DAT-06',title:'Decision Brief',minutes:65,objectives:['Synthesize evidence','Recommend proportionate action'],concepts:['Lead with decision question','Separate finding from recommendation','State uncertainty and next evidence need'],workedExample:'A recommendation can propose a limited pilot rather than claiming an unproven cause.',guidedPractice:'Turn three findings into a finding-limit-action matrix.',challenge:'Write a one-page brief and prepare a five-minute evidence presentation.',qa:['Every recommendation links to evidence','Limitations visible'],reflection:'What would make you change the recommendation?'},
]
