export type YAQuestion={id:string;track:string;module:string;type:'concept'|'calculation'|'interpret'|'debug'|'test-design'|'responsible-practice';prompt:string;options:string[];answer:number;rationale:string}
export const youngAnalystQuestionBank:YAQuestion[]=[
 {id:'EDL-Q01',track:'excel-data-literacy',module:'EDL-02',type:'debug',prompt:'A category appears as Data, data and DATA. What is the best cleaning action?',options:['Delete two spellings','Standardise to one documented category while preserving the records','Convert all values to numbers'],answer:1,rationale:'Cleaning should correct representation without discarding valid observations.'},
 {id:'EDL-Q02',track:'excel-data-literacy',module:'EDL-03',type:'calculation',prompt:'Registered=24 and attended=18. What attendance rate should a formula return?',options:['42%','75%','133%'],answer:1,rationale:'18/24 = 0.75 = 75%.'},
 {id:'EDL-Q03',track:'excel-data-literacy',module:'EDL-05',type:'interpret',prompt:'Which chart is usually clearest for comparing attendance rates across three named clubs?',options:['Bar chart','Decorative 3-D pie','Scatter plot with no numeric x variable'],answer:0,rationale:'A bar chart supports direct categorical comparison.'},
 {id:'STA-Q01',track:'statistics',module:'STA-02',type:'calculation',prompt:'What is the mean of 2, 4 and 9?',options:['4','5','6'],answer:1,rationale:'(2+4+9)/3 = 5.'},
 {id:'STA-Q02',track:'statistics',module:'STA-03',type:'interpret',prompt:'One extreme value raises the mean sharply but leaves the median similar. What does this show?',options:['The mean can be sensitive to outliers','The median is always wrong','The dataset has no variation'],answer:0,rationale:'Extreme values can disproportionately affect the arithmetic mean.'},
 {id:'STA-Q03',track:'statistics',module:'STA-05',type:'responsible-practice',prompt:'A survey about all students samples only members of the analytics club. Main concern?',options:['Selection bias','Too many variables','The mean cannot be calculated'],answer:0,rationale:'The sampling process systematically excludes much of the target population.'},
 {id:'RES-Q01',track:'research',module:'RES-01',type:'concept',prompt:'Which is the most answerable research question?',options:['Why is school life bad?','What proportion of sampled learners used the library at least once last week?','Are students good?'],answer:1,rationale:'It defines a measurable outcome, population context and period.'},
 {id:'RES-Q02',track:'research',module:'RES-03',type:'debug',prompt:'“How excellent was our helpful new club?” is problematic mainly because it is…',options:['Leading','Too numerical','Anonymous'],answer:0,rationale:'The wording pushes respondents toward a positive evaluation.'},
 {id:'RES-Q03',track:'research',module:'RES-05',type:'responsible-practice',prompt:'A survey needs preferred study location. Which field is unnecessary?',options:['Study location category','Full home address','Broad response option such as home/library'],answer:1,rationale:'A full address is disproportionate to the stated purpose.'},
 {id:'AIL-Q01',track:'ai-literacy',module:'AIL-01',type:'concept',prompt:'An AI gives a confident factual answer. What follows?',options:['Confidence proves accuracy','The claim still requires verification','The answer becomes a primary source'],answer:1,rationale:'Fluent output is not evidence of factual reliability.'},
 {id:'AIL-Q02',track:'ai-literacy',module:'AIL-03',type:'test-design',prompt:'Best way to check an AI-generated statistic?',options:['Ask the same model to repeat it','Trace it to a suitable source and verify context/denominator','Use it if it sounds precise'],answer:1,rationale:'Verification requires evidence independent of the generated assertion.'},
 {id:'AIL-Q03',track:'ai-literacy',module:'AIL-05',type:'responsible-practice',prompt:'Which should not be pasted into a general AI prompt for a class exercise?',options:['Synthetic sample rows','A public definition','A learner password and private record'],answer:2,rationale:'Credentials and private learner information should not be exposed.'},
 {id:'DAT-Q01',track:'data-analytics-teens',module:'DAT-01',type:'concept',prompt:'What should come before choosing a chart?',options:['Define the decision question','Pick the brightest colours','Write the conclusion'],answer:0,rationale:'Analytical choices should follow the question and intended use.'},
 {id:'DAT-Q02',track:'data-analytics-teens',module:'DAT-04',type:'calculation',prompt:'Club A: 18/24 attend. Club B: 14/20 attend. Which has the higher rate?',options:['A: 75% vs B: 70%','B: 78% vs A: 70%','They are equal'],answer:0,rationale:'18/24=75%; 14/20=70%.'},
 {id:'DAT-Q03',track:'data-analytics-teens',module:'DAT-05',type:'interpret',prompt:'Device availability and completed sessions move together across five clubs. Strongest defensible statement?',options:['Devices caused every difference','There is an observed association worth investigating; other explanations remain possible','No analysis is possible'],answer:1,rationale:'Observational association alone does not establish causality.'},
]
