export type YAQuestion={id:string;track:string;module:string;type:'concept'|'calculation'|'interpret'|'debug'|'test-design'|'responsible-practice';prompt:string;options:string[]}
export const youngAnalystQuestionBank:YAQuestion[]=[
 {id:'EDL-Q01',track:'excel-data-literacy',module:'EDL-02',type:'debug',prompt:'A category appears as Data, data and DATA. What is the best cleaning action?',options:['Delete two spellings','Standardise to one documented category while preserving the records','Convert all values to numbers']},
 {id:'EDL-Q02',track:'excel-data-literacy',module:'EDL-03',type:'calculation',prompt:'Registered=24 and attended=18. What attendance rate should a formula return?',options:['42%','75%','133%']},
 {id:'EDL-Q03',track:'excel-data-literacy',module:'EDL-05',type:'interpret',prompt:'Which chart is usually clearest for comparing attendance rates across three named clubs?',options:['Bar chart','Decorative 3-D pie','Scatter plot with no numeric x variable']},
 {id:'STA-Q01',track:'statistics',module:'STA-02',type:'calculation',prompt:'What is the mean of 2, 4 and 9?',options:['4','5','6']},
 {id:'STA-Q02',track:'statistics',module:'STA-03',type:'interpret',prompt:'One extreme value raises the mean sharply but leaves the median similar. What does this show?',options:['The mean can be sensitive to outliers','The median is always wrong','The dataset has no variation']},
 {id:'STA-Q03',track:'statistics',module:'STA-05',type:'responsible-practice',prompt:'A survey about all students samples only members of the analytics club. Main concern?',options:['Selection bias','Too many variables','The mean cannot be calculated']},
 {id:'RES-Q01',track:'research',module:'RES-01',type:'concept',prompt:'Which is the most answerable research question?',options:['Why is school life bad?','What proportion of sampled learners used the library at least once last week?','Are students good?']},
 {id:'RES-Q02',track:'research',module:'RES-03',type:'debug',prompt:'“How excellent was our helpful new club?” is problematic mainly because it is…',options:['Leading','Too numerical','Anonymous']},
 {id:'RES-Q03',track:'research',module:'RES-05',type:'responsible-practice',prompt:'A survey needs preferred study location. Which field is unnecessary?',options:['Study location category','Full home address','Broad response option such as home/library']},
 {id:'AIL-Q01',track:'ai-literacy',module:'AIL-01',type:'concept',prompt:'An AI gives a confident factual answer. What follows?',options:['Confidence proves accuracy','The claim still requires verification','The answer becomes a primary source']},
 {id:'AIL-Q02',track:'ai-literacy',module:'AIL-03',type:'test-design',prompt:'Best way to check an AI-generated statistic?',options:['Ask the same model to repeat it','Trace it to a suitable source and verify context/denominator','Use it if it sounds precise']},
 {id:'AIL-Q03',track:'ai-literacy',module:'AIL-05',type:'responsible-practice',prompt:'Which should not be pasted into a general AI prompt for a class exercise?',options:['Synthetic sample rows','A public definition','A learner password and private record']},
 {id:'DAT-Q01',track:'data-analytics-teens',module:'DAT-01',type:'concept',prompt:'What should come before choosing a chart?',options:['Define the decision question','Pick the brightest colours','Write the conclusion']},
 {id:'DAT-Q02',track:'data-analytics-teens',module:'DAT-04',type:'calculation',prompt:'Club A: 18/24 attend. Club B: 14/20 attend. Which has the higher rate?',options:['A: 75% vs B: 70%','B: 78% vs A: 70%','They are equal']},
 {id:'DAT-Q03',track:'data-analytics-teens',module:'DAT-05',type:'interpret',prompt:'Device availability and completed sessions move together across five clubs. Strongest defensible statement?',options:['Devices caused every difference','There is an observed association worth investigating; other explanations remain possible','No analysis is possible']},
]
