'use client'

import Link from 'next/link'
import {useMemo,useState} from 'react'
import './lesson.css'

type Lesson='1'|'2'|'3';type Check={prompt:string;options:string[];answer:number;feedback:string}
const lessonInfo={
 '1':{title:'Choose Data Sources and Establish Provenance',duration:'45–60 minutes',outcomes:['Distinguish primary, secondary, administrative and open data sources.','Evaluate sources for relevance, authority, coverage, timeliness and access conditions.','Create a provenance record that supports reproducibility and audit.']},
 '2':{title:'Design Collection Instruments and Field Controls',duration:'55–70 minutes',outcomes:['Translate defined variables into neutral, answerable questions and observation fields.','Align the target population, sampling frame, unit and respondent.','Specify identifiers, skip logic, validation, training, piloting and field supervision controls.']},
 '3':{title:'Govern Privacy, Ethics, Security and Data Use',duration:'55–70 minutes',outcomes:['Apply purpose limitation, minimisation and proportionality.','Classify data and assign least-privilege access, retention and disposal controls.','Recognise consent, fairness, safeguarding, sharing and accountability obligations.']},
} as const
const checks:Record<Lesson,Check[]>={
 '1':[{prompt:'A ministry database created to administer payments is later used for policy analysis. What kind of source is it for that analysis?',options:['Primary experimental data','Administrative secondary data','Synthetic data','Unstructured observation'],answer:1,feedback:'The records arose from administration, not specifically for the later question; their definitions and coverage must be assessed.'},{prompt:'Which record most adequately establishes provenance?',options:['“Downloaded online”','Publisher, title, version, extraction date, query or URL, licence and transformations','A screenshot','The analyst’s initials only'],answer:1,feedback:'Provenance must let a qualified reviewer identify and reconstruct the exact data used.'}],
 '2':[{prompt:'Which question is least likely to introduce response bias?',options:['You agree the programme was excellent, do you not?','How satisfied were you with the service? Very dissatisfied to very satisfied','Why did staff fail you?','Was the excellent training useful?'],answer:1,feedback:'Neutral wording and balanced response options reduce leading pressure, though the item must still be piloted.'},{prompt:'What should happen before full field deployment?',options:['Remove validation rules','Pilot the instrument and workflow with realistic respondents and devices','Collect names just in case','Change questions daily without version control'],answer:1,feedback:'A pilot tests comprehension, routing, timing, device behaviour, transfer and supervision before defects scale.'}],
 '3':[{prompt:'What does data minimisation require?',options:['Collect every available field','Collect only data necessary and proportionate for the stated purpose','Delete all metadata','Permit unrestricted internal access'],answer:1,feedback:'Possible future usefulness is not sufficient justification for collecting personal or sensitive information.'},{prompt:'Which access design is most defensible?',options:['One shared administrator password','Named role-based access, multifactor authentication and auditable activity logs','Public links for convenience','Permanent access for former staff'],answer:1,feedback:'Least privilege, individual accountability and prompt lifecycle changes reduce accidental and deliberate misuse.'}],
}
const sourceTypes=[['Primary','Collected specifically for the current study or decision.','Survey, interview, sensor or experiment'],['Administrative','Produced while delivering a service or enforcing a process.','Enrolment, payroll, health or tax records'],['Secondary research','Previously collected and documented by another study.','Survey microdata or research repository'],['Open / external','Published for reuse under stated terms.','Official statistics, geospatial or market data']]
const lifecycle=[['1','Purpose','Define the decision, necessity and lawful purpose.'],['2','Acquire','Approve the source, instrument, sample and protocol.'],['3','Protect','Classify, encrypt and restrict data from capture.'],['4','Use','Analyse only for approved purposes and record transformations.'],['5','Share','Apply agreements, disclosure controls and recipient conditions.'],['6','Retain or dispose','Keep only for an approved period; verify secure disposal.']]

export default function ModuleThreeLesson({lesson}:{lesson:Lesson}){
 const[selected,setSelected]=useState<Record<number,number>>({});const score=useMemo(()=>checks[lesson].filter((q,i)=>selected[i]===q.answer).length,[lesson,selected]),info=lessonInfo[lesson]
 return <main className="ds3-lesson"><nav aria-label="Breadcrumb"><Link href="/data-science">Data Science</Link><span aria-hidden="true"> / </span><Link href="/data-science/foundations/03">Module 03</Link><span aria-hidden="true"> / </span><span>Lesson 03.{lesson}</span></nav>
  <header><div><p>LESSON 03.{lesson} · {info.duration}</p><h1>{info.title}</h1><span>Beginner pathway · ethical, reproducible data acquisition.</span></div><aside><b>MODULE 03</b><span>Lesson {lesson} of 3</span></aside></header>
  <div className="ds3-layout"><article><section className="ds3-card"><h2>Learning outcomes</h2><ul>{info.outcomes.map(x=><li key={x}>{x}</li>)}</ul></section>
   {lesson==='1'&&<><section><h2>A source is suitable only in relation to a purpose</h2><p>Authority does not guarantee fitness. Assess whether the source measures the required concept, covers the relevant population and period, uses stable definitions, has known exclusions, is current enough and may lawfully be reused.</p><div className="ds3-grid">{sourceTypes.map(([title,meaning,example])=><div key={title}><h3>{title}</h3><p>{meaning}</p><small>{example}</small></div>)}</div></section><section className="ds3-callout"><h2>Provenance is the chain of custody for data</h2><p>Record the publisher or system owner, title, version, extraction timestamp, query or location, licence, approvals, transformations and responsible analyst. “Found in Downloads” is a location, not a lineage record.</p></section><section><h2>Source evaluation matrix</h2><ul><li><b>Relevance:</b> Does it measure the required construct?</li><li><b>Coverage:</b> Who, where and when is included or excluded?</li><li><b>Authority:</b> Who created the record, under which process?</li><li><b>Timeliness:</b> Will its lag permit the intended decision?</li><li><b>Linkability:</b> Are identifiers lawful, stable and usable?</li><li><b>Access:</b> What licence, consent or agreement governs reuse?</li></ul></section></>}
   {lesson==='2'&&<><section><h2>Move from construct to captured field</h2><p>Every field should trace to a defined variable and decision need. Specify the respondent, recall period, response format, allowed values, missing codes and validation rules. Avoid double-barrelled, leading, ambiguous and needlessly sensitive questions.</p><div className="ds3-compare"><div><b>Weak item</b><span>Are lessons engaging and well organised?</span></div><div><b>Improved items</b><span>Ask engagement and organisation separately, using balanced defined scales and a stated period.</span></div></div></section><section><h2>Field controls form a system</h2><ol><li>Approve instrument specifications and versions.</li><li>Train and assess enumerators using standard protocols.</li><li>Pilot questions, routing, timing, devices and transfer.</li><li>Use stable identifiers, range checks and controlled categories.</li><li>Review daily completeness, duration, location and enumerator patterns.</li><li>Document corrections, refusals, non-response and deviations.</li></ol></section><section className="ds3-callout"><h2>Sampling alignment</h2><p>Distinguish the target population from the frame and selected sample. Record inclusion probabilities, clustering, stratification, replacements and non-response. A large convenience sample remains a convenience sample; volume does not cure selection bias.</p></section></>}
   {lesson==='3'&&<><section><h2>Govern the full lifecycle</h2><p>Governance begins when a purpose is proposed—not after a spreadsheet has been emailed. Controls should follow data from justification and capture through analysis, disclosure, archiving and verified disposal.</p><ol className="ds3-lifecycle">{lifecycle.map(([n,title,text])=><li key={n}><b>{n}</b><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section><section><h2>Minimum governance controls</h2><div className="ds3-grid"><div><h3>Necessity</h3><p>Document purpose, lawful basis, proportionality and approval.</p></div><div><h3>Protection</h3><p>Classify data, encrypt transfers and apply least privilege.</p></div><div><h3>Fairness</h3><p>Assess exclusion, coercion, subgroup harm and downstream misuse.</p></div><div><h3>Accountability</h3><p>Name owners, log access, manage incidents and verify disposal.</p></div></div></section><section className="ds3-callout"><h2>De-identification is not a magic spell</h2><p>Removing names may leave rare combinations, precise locations or linked records that identify people. Assess re-identification risk in context and share the minimum detail needed under enforceable conditions.</p><a className="ds3-download" href="/api/data-science/module-03/data-acquisition-governance-template" download>Download acquisition and governance template (.csv)</a></section></>}
   <section className="ds3-practice"><h2>Guided knowledge check</h2><p>Select an answer and use the feedback to examine the governing principle.</p>{checks[lesson].map((q,i)=><fieldset key={q.prompt}><legend>{i+1}. {q.prompt}</legend>{q.options.map((o,j)=><label key={o}><input type="radio" name={`q-${i}`} checked={selected[i]===j} onChange={()=>setSelected(v=>({...v,[i]:j}))}/><span>{o}</span></label>)}{selected[i]!==undefined&&<p role="status" className={selected[i]===q.answer?'correct':'review'}>{selected[i]===q.answer?'Correct. ':'Review this. '}{q.feedback}</p>}</fieldset>)}<p><b>Current score: {score}/{checks[lesson].length}</b></p></section>
   <section className="ds3-apply"><h2>Apply it</h2><p>{lesson==='1'?'Choose one proposed dataset and assess its purpose, coverage, authority, timeliness, provenance, licence and limitations.':lesson==='2'?'Draft five collection fields. Specify wording, response type, allowed values, missing code, validation rule and pilot test.':'Map a genuine data flow from collection to disposal. Identify purpose, sensitivity, roles, storage, sharing conditions, retention and incident ownership.'}</p></section>
   <footer><Link href={lesson==='1'?'/data-science/foundations/03':`/data-science/foundations/03/${Number(lesson)-1}`}>← {lesson==='1'?'Module overview':'Previous lesson'}</Link><Link className="ds3-next" href={lesson==='3'?'/data-science/foundations/03':`/data-science/foundations/03/${Number(lesson)+1}`}>{lesson==='3'?'Return and record Lesson 03.3':'Continue to next lesson'} →</Link></footer>
  </article><aside className="ds3-rail"><b>Progression standard</b><ol><li>Read the concepts.</li><li>Examine the controls.</li><li>Complete the guided check.</li><li>Apply the method to a genuine workflow.</li></ol><p>Return to the module overview after the lesson to record the persistent competency gate.</p></aside></div></main>
}
