create table if not exists public.merl_level2_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null check (module_id in ('06','07','08','09','10')),
  lesson_evidence jsonb not null default '{}'::jsonb,
  quiz_score numeric(5,2),
  quiz_passed boolean not null default false,
  quiz_attempts integer not null default 0 check (quiz_attempts between 0 and 2),
  module_completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id,module_id)
);
create table if not exists public.merl_level2_evidence (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null check (module_id in ('06','07','08','09','10')),
  evidence_type text not null,
  content text not null check (char_length(content) between 20 and 20000),
  status text not null default 'submitted' check (status in ('submitted','accepted','revision_required')),
  submitted_at timestamptz not null default now(),
  unique(user_id,module_id)
);
create table if not exists public.merl_level2_quiz_items (
  module_id text not null check (module_id in ('06','07','08','09','10')),
  question_id text not null,
  question_order integer not null,
  stem text not null,
  options jsonb not null check (jsonb_typeof(options)='array'),
  correct_option integer not null check (correct_option>=0),
  active boolean not null default true,
  primary key(module_id,question_id)
);
create table if not exists public.merl_level2_quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null check (module_id in ('06','07','08','09','10')),
  answers jsonb not null,
  score numeric(5,2) not null,
  passed boolean not null,
  attempted_at timestamptz not null default now()
);
create index if not exists merl_level2_evidence_user_idx on public.merl_level2_evidence(user_id);
create index if not exists merl_level2_attempts_user_module_idx on public.merl_level2_quiz_attempts(user_id,module_id);

alter table public.merl_level2_progress enable row level security;
alter table public.merl_level2_evidence enable row level security;
alter table public.merl_level2_quiz_items enable row level security;
alter table public.merl_level2_quiz_attempts enable row level security;
revoke all on public.merl_level2_progress,public.merl_level2_evidence,public.merl_level2_quiz_items,public.merl_level2_quiz_attempts from public,anon,authenticated;
grant select on public.merl_level2_progress,public.merl_level2_evidence,public.merl_level2_quiz_attempts to authenticated;
create policy "Learners read own Level 2 progress" on public.merl_level2_progress for select to authenticated using ((select auth.uid())=user_id);
create policy "Learners read own Level 2 evidence" on public.merl_level2_evidence for select to authenticated using ((select auth.uid())=user_id);
create policy "Learners read own Level 2 attempts" on public.merl_level2_quiz_attempts for select to authenticated using ((select auth.uid())=user_id);

create or replace function public.merl_level2_previous_complete(p_user uuid,p_module text)
returns boolean language sql stable security definer set search_path='' as $$
 select case p_module
  when '06' then (select count(*)=5 from public.merl_level1_progress where user_id=p_user and module_completed_at is not null)
  when '07' then exists(select 1 from public.merl_level2_progress where user_id=p_user and module_id='06' and module_completed_at is not null)
  when '08' then exists(select 1 from public.merl_level2_progress where user_id=p_user and module_id='07' and module_completed_at is not null)
  when '09' then exists(select 1 from public.merl_level2_progress where user_id=p_user and module_id='08' and module_completed_at is not null)
  when '10' then exists(select 1 from public.merl_level2_progress where user_id=p_user and module_id='09' and module_completed_at is not null)
  else false end
$$;

create or replace function public.get_merl_level2_progress()
returns table(module_id text,lesson_evidence jsonb,evidence_submission jsonb,quiz_score numeric,quiz_passed boolean,quiz_attempts integer,module_completed_at timestamptz)
language sql stable security definer set search_path='' as $$
 with modules(module_id) as (values ('06'),('07'),('08'),('09'),('10'))
 select m.module_id,coalesce(p.lesson_evidence,'{}'::jsonb),
  (select jsonb_build_object('id',e.id,'evidence_type',e.evidence_type,'content',e.content,'status',e.status,'submitted_at',e.submitted_at)
   from public.merl_level2_evidence e where e.user_id=auth.uid() and e.module_id=m.module_id),
  p.quiz_score,coalesce(p.quiz_passed,false),coalesce(p.quiz_attempts,0),p.module_completed_at
 from modules m left join public.merl_level2_progress p on p.user_id=auth.uid() and p.module_id=m.module_id order by m.module_id
$$;

create or replace function public.mark_merl_level2_lesson(p_module_id text,p_lesson_index integer)
returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid(); v_key text;
begin
 if v_user is null then raise exception 'Authentication required'; end if;
 if p_module_id not in ('06','07','08','09','10') or p_lesson_index not between 0 and 2 then raise exception 'Invalid lesson'; end if;
 if not public.merl_level2_previous_complete(v_user,p_module_id) then raise exception 'Previous module must be completed first'; end if;
 v_key:=p_module_id||'-'||p_lesson_index;
 insert into public.merl_level2_progress(user_id,module_id,lesson_evidence,updated_at)
 values(v_user,p_module_id,jsonb_build_object(v_key,true),now())
 on conflict(user_id,module_id) do update set lesson_evidence=public.merl_level2_progress.lesson_evidence||excluded.lesson_evidence,updated_at=now();
end $$;

create or replace function public.submit_merl_level2_evidence(p_module_id text,p_evidence_type text,p_content text)
returns bigint language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid(); v_id bigint;
begin
 if v_user is null then raise exception 'Authentication required'; end if;
 if p_module_id not in ('06','07','08','09','10') then raise exception 'Invalid module'; end if;
 if not public.merl_level2_previous_complete(v_user,p_module_id) then raise exception 'Previous module must be completed first'; end if;
 if char_length(trim(p_content))<20 or char_length(trim(p_content))>20000 then raise exception 'Evidence must contain 20 to 20000 characters'; end if;
 if (select count(*) from public.merl_level2_progress p,jsonb_each(p.lesson_evidence) item where p.user_id=v_user and p.module_id=p_module_id and item.value='true'::jsonb)<3 then raise exception 'Complete all lesson evidence first'; end if;
 insert into public.merl_level2_evidence(user_id,module_id,evidence_type,content) values(v_user,p_module_id,trim(p_evidence_type),trim(p_content)) returning id into v_id;
 return v_id;
end $$;

create or replace function public.get_merl_level2_quiz(p_module_id text)
returns table(question_id text,question_order integer,stem text,options jsonb)
language plpgsql stable security definer set search_path='' as $$
declare v_user uuid:=auth.uid();
begin
 if v_user is null then raise exception 'Authentication required'; end if;
 if p_module_id not in ('06','07','08','09','10') then raise exception 'Invalid module'; end if;
 if not public.merl_level2_previous_complete(v_user,p_module_id) then raise exception 'Previous module must be completed first'; end if;
 if not exists(select 1 from public.merl_level2_evidence where user_id=v_user and module_id=p_module_id) then raise exception 'Professional evidence must be submitted before the quiz'; end if;
 return query select q.question_id,q.question_order,q.stem,q.options from public.merl_level2_quiz_items q where q.module_id=p_module_id and q.active order by q.question_order;
end $$;

create or replace function public.grade_merl_level2_quiz(p_module_id text,p_answers jsonb)
returns table(score numeric,passed boolean,attempts integer)
language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_score numeric(5,2);v_questions integer;v_answers integer;v_correct integer;v_attempts integer;v_passed boolean;v_now timestamptz:=now();
begin
 if v_user is null then raise exception 'Authentication required'; end if;
 if p_module_id not in ('06','07','08','09','10') then raise exception 'Invalid module'; end if;
 if not public.merl_level2_previous_complete(v_user,p_module_id) then raise exception 'Previous module must be completed first'; end if;
 perform 1 from public.merl_level2_progress where user_id=v_user and module_id=p_module_id for update;
 if (select count(*) from public.merl_level2_progress p,jsonb_each(p.lesson_evidence) item where p.user_id=v_user and p.module_id=p_module_id and item.value='true'::jsonb)<3 then raise exception 'Complete all lesson evidence first'; end if;
 if not exists(select 1 from public.merl_level2_evidence where user_id=v_user and module_id=p_module_id and status in ('submitted','accepted')) then raise exception 'Professional evidence must be submitted before the quiz'; end if;
 select count(*) into v_attempts from public.merl_level2_quiz_attempts where user_id=v_user and module_id=p_module_id;
 if v_attempts>=2 then raise exception 'Maximum quiz attempts reached'; end if;
 select count(*) into v_questions from public.merl_level2_quiz_items where module_id=p_module_id and active;
 select count(*) into v_answers from jsonb_object_keys(coalesce(p_answers,'{}'::jsonb));
 if v_questions=0 then raise exception 'Quiz is not configured'; end if;
 if v_answers<>v_questions then raise exception 'Every active quiz question must be answered exactly once'; end if;
 if exists(select 1 from jsonb_object_keys(p_answers) a where not exists(select 1 from public.merl_level2_quiz_items q where q.module_id=p_module_id and q.active and q.question_id=a)) then raise exception 'Answers contain an invalid question'; end if;
 select count(*) into v_correct from public.merl_level2_quiz_items q where q.module_id=p_module_id and q.active and p_answers?q.question_id and p_answers->>q.question_id=q.correct_option::text;
 v_score:=round((v_correct::numeric/v_questions)*100,2);v_passed:=v_score>=70;
 insert into public.merl_level2_quiz_attempts(user_id,module_id,answers,score,passed) values(v_user,p_module_id,p_answers,v_score,v_passed);
 update public.merl_level2_progress set quiz_score=greatest(coalesce(quiz_score,0),v_score),quiz_passed=quiz_passed or v_passed,quiz_attempts=v_attempts+1,module_completed_at=case when v_passed then coalesce(module_completed_at,v_now) else module_completed_at end,updated_at=v_now where user_id=v_user and module_id=p_module_id;
 return query select v_score::numeric,v_passed,v_attempts+1;
end $$;

revoke all on function public.merl_level2_previous_complete(uuid,text),public.get_merl_level2_progress(),public.mark_merl_level2_lesson(text,integer),public.submit_merl_level2_evidence(text,text,text),public.get_merl_level2_quiz(text),public.grade_merl_level2_quiz(text,jsonb) from public,anon;
revoke all on function public.merl_level2_previous_complete(uuid,text) from authenticated;
grant execute on function public.get_merl_level2_progress(),public.mark_merl_level2_lesson(text,integer),public.submit_merl_level2_evidence(text,text,text),public.get_merl_level2_quiz(text),public.grade_merl_level2_quiz(text,jsonb) to authenticated;

insert into public.merl_level2_quiz_items(module_id,question_id,question_order,stem,options,correct_option) values
('06','06-q1',1,'What should determine a data-collection frequency?','["Software capacity","The decision window and rate of meaningful change","A universal monthly rule","The number of indicators"]',1),
('06','06-q2',2,'Which plan is operationally complete?','["Source only","Indicator, variables, source, method, frequency, owner, quality and protection controls","A blank spreadsheet","A dashboard screenshot"]',1),
('07','07-q1',1,'What should happen when consent is withdrawn?','["Continue collection","Stop and follow the approved withdrawal procedure","Offer payment","Complete answers from memory"]',1),
('07','07-q2',2,'How should a released tool be changed?','["Silent overwrite","Controlled version, approval and change log","Enumerator discretion","After analysis only"]',1),
('08','08-q1',1,'What is frame undercoverage?','["Eligible units missing from the selection frame","A sample larger than expected","Too many variables","A high response rate"]',0),
('08','08-q2',2,'A required 240 completes at 80% response needs how many issued cases?','["192","240","300","320"]',2),
('09','09-q1',1,'What does source verification establish?','["The value matches authorised evidence","The chart uses brand colours","Every field is numeric","The report is long"]',0),
('09','09-q2',2,'What must a correction trail retain?','["Only the new value","Original value, correction, reason, actor and time","A verbal explanation","Nothing after approval"]',1),
('10','10-q1',1,'What is the strongest starting point for system design?','["Dashboard colour","Decisions, definitions and accountable users","Vendor preference","Unlimited fields"]',1),
('10','10-q2',2,'Which measure best tests system usefulness?','["Number of charts","Evidence reaching due decisions on time","Database size","Login count"]',1)
on conflict(module_id,question_id) do update set question_order=excluded.question_order,stem=excluded.stem,options=excluded.options,correct_option=excluded.correct_option,active=true;
