-- Remove overlapping SELECT policies and cover creator foreign keys.
drop policy if exists "executives manage organisation metrics" on public.ceo_metrics;
drop policy if exists "executives manage priorities" on public.ceo_strategic_priorities;
drop policy if exists "ceo manages direction statements" on public.ceo_direction_statements;
create policy "authorised users insert metrics" on public.ceo_metrics for insert to authenticated with check(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_metrics.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive','analyst')));
create policy "authorised users update metrics" on public.ceo_metrics for update to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_metrics.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive','analyst')))with check(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_metrics.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive','analyst')));
create policy "authorised users delete metrics" on public.ceo_metrics for delete to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_metrics.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive','analyst')));
create policy "executives insert priorities" on public.ceo_strategic_priorities for insert to authenticated with check(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_strategic_priorities.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive')));
create policy "executives update priorities" on public.ceo_strategic_priorities for update to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_strategic_priorities.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive')))with check(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_strategic_priorities.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive')));
create policy "executives delete priorities" on public.ceo_strategic_priorities for delete to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_strategic_priorities.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive')));
create policy "ceo inserts direction statements" on public.ceo_direction_statements for insert to authenticated with check(created_by=(select auth.uid()) and exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_direction_statements.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role='ceo'));
create policy "ceo updates direction statements" on public.ceo_direction_statements for update to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_direction_statements.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role='ceo'))with check(created_by=(select auth.uid()) and exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_direction_statements.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role='ceo'));
create policy "ceo deletes direction statements" on public.ceo_direction_statements for delete to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_direction_statements.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role='ceo'));
create index if not exists ceo_metrics_creator_idx on public.ceo_metrics(created_by);
create index if not exists ceo_priorities_creator_idx on public.ceo_strategic_priorities(created_by);
create index if not exists ceo_statements_creator_idx on public.ceo_direction_statements(created_by);
