-- CEO Workspace v0.1: premium organisation tenancy and strategic decision records.
create table if not exists public.ceo_organisations(
  id uuid primary key default gen_random_uuid(),
  name text not null check(char_length(trim(name)) between 2 and 160),
  sector text not null default 'General',
  country_code text not null default 'KE' check(country_code ~ '^[A-Z]{2}$'),
  reporting_currency text not null default 'KES' check(reporting_currency ~ '^[A-Z]{3}$'),
  premium_status text not null default 'trial' check(premium_status in('trial','active','suspended','cancelled')),
  premium_expires_at timestamptz,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.ceo_memberships(
  organisation_id uuid not null references public.ceo_organisations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'ceo' check(role in('ceo','executive','analyst','viewer')),
  display_name text not null check(char_length(trim(display_name)) between 2 and 120),
  job_title text not null default 'Chief Executive Officer',
  active boolean not null default true,
  created_at timestamptz not null default now(),primary key(organisation_id,user_id)
);
create table if not exists public.ceo_metrics(
  id bigint generated by default as identity primary key,
  organisation_id uuid not null references public.ceo_organisations(id) on delete cascade,
  metric_key text not null,metric_name text not null,metric_value numeric not null,
  unit text not null default 'number',period_label text not null,
  comparison_value numeric,comparison_label text,data_source text,
  status text not null default 'neutral' check(status in('positive','watch','critical','neutral')),
  measured_at timestamptz not null default now(),created_by uuid references auth.users(id),
  unique(organisation_id,metric_key,period_label)
);
create table if not exists public.ceo_strategic_priorities(
  id bigint generated by default as identity primary key,
  organisation_id uuid not null references public.ceo_organisations(id) on delete cascade,
  title text not null,objective text not null,owner text,target_date date,
  progress numeric(5,2) not null default 0 check(progress between 0 and 100),
  status text not null default 'on_track' check(status in('on_track','watch','off_track','complete')),
  next_decision text,updated_at timestamptz not null default now(),created_by uuid references auth.users(id)
);
create table if not exists public.ceo_direction_statements(
  id bigint generated by default as identity primary key,
  organisation_id uuid not null references public.ceo_organisations(id) on delete cascade,
  title text not null,strategic_context text not null,evidence_summary text not null,
  direction_statement text not null,decisions text not null,assumptions text,
  review_date date,status text not null default 'draft' check(status in('draft','approved','archived')),
  version integer not null default 1 check(version>0),created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index if not exists ceo_memberships_user_idx on public.ceo_memberships(user_id) where active;
create index if not exists ceo_metrics_org_date_idx on public.ceo_metrics(organisation_id,measured_at desc);
create index if not exists ceo_priorities_org_idx on public.ceo_strategic_priorities(organisation_id,status);
create index if not exists ceo_statements_org_idx on public.ceo_direction_statements(organisation_id,updated_at desc);
alter table public.ceo_organisations enable row level security;alter table public.ceo_memberships enable row level security;alter table public.ceo_metrics enable row level security;alter table public.ceo_strategic_priorities enable row level security;alter table public.ceo_direction_statements enable row level security;
create policy "members read own organisation" on public.ceo_organisations for select to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=id and m.user_id=(select auth.uid()) and m.active));
create policy "members read own membership" on public.ceo_memberships for select to authenticated using(user_id=(select auth.uid()));
create policy "members read organisation metrics" on public.ceo_metrics for select to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_metrics.organisation_id and m.user_id=(select auth.uid()) and m.active));
create policy "executives manage organisation metrics" on public.ceo_metrics for all to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_metrics.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive','analyst')))with check(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_metrics.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive','analyst')));
create policy "members read priorities" on public.ceo_strategic_priorities for select to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_strategic_priorities.organisation_id and m.user_id=(select auth.uid()) and m.active));
create policy "executives manage priorities" on public.ceo_strategic_priorities for all to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_strategic_priorities.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive')))with check(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_strategic_priorities.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role in('ceo','executive')));
create policy "members read direction statements" on public.ceo_direction_statements for select to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_direction_statements.organisation_id and m.user_id=(select auth.uid()) and m.active));
create policy "ceo manages direction statements" on public.ceo_direction_statements for all to authenticated using(exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_direction_statements.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role='ceo'))with check(created_by=(select auth.uid()) and exists(select 1 from public.ceo_memberships m where m.organisation_id=ceo_direction_statements.organisation_id and m.user_id=(select auth.uid()) and m.active and m.role='ceo'));
grant select on public.ceo_organisations,public.ceo_memberships,public.ceo_metrics,public.ceo_strategic_priorities,public.ceo_direction_statements to authenticated;
grant insert,update,delete on public.ceo_metrics,public.ceo_strategic_priorities,public.ceo_direction_statements to authenticated;
grant usage,select on sequence public.ceo_metrics_id_seq,public.ceo_strategic_priorities_id_seq,public.ceo_direction_statements_id_seq to authenticated;
revoke all on public.ceo_organisations,public.ceo_memberships from anon;revoke insert,update,delete on public.ceo_organisations,public.ceo_memberships from authenticated;
