-- Immutable credential lifecycle audit and governed revocation.
create table public.credential_events(
  id bigint generated by default as identity primary key,
  credential_id uuid not null references public.credentials(id) on delete restrict,
  event_type text not null check(event_type in('issued','revoked','superseded')),
  previous_status text,
  new_status text not null,
  reason text,
  actor_user_id uuid references auth.users(id),
  occurred_at timestamptz not null default now()
);
create index credential_events_credential_idx on public.credential_events(credential_id,occurred_at desc);
create index credential_events_actor_idx on public.credential_events(actor_user_id);
alter table public.credential_events enable row level security;
create policy credential_events_authorised_read on public.credential_events for select to authenticated
using(exists(select 1 from public.credentials c where c.id=public.credential_events.credential_id and (c.learner_user_id=(select auth.uid()) or public.is_certification_admin())));
grant select on public.credential_events to authenticated;

create or replace function private.record_credential_event()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if tg_op='INSERT' then
    insert into public.credential_events(credential_id,event_type,new_status,actor_user_id)
    values(new.id,'issued',new.status,new.issued_by);
  elsif new.status is distinct from old.status then
    insert into public.credential_events(credential_id,event_type,previous_status,new_status,reason,actor_user_id)
    values(new.id,new.status,old.status,new.status,new.revocation_reason,auth.uid());
  end if;
  return new;
end $$;
revoke all on function private.record_credential_event() from public,anon,authenticated;
create trigger credential_lifecycle_audit after insert or update of status on public.credentials
for each row execute function private.record_credential_event();

create or replace function public.revoke_credential(p_credential_id text,p_reason text)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_count integer;
begin
  if auth.uid() is null or not public.is_certification_admin() then
    raise exception 'Certification administrator required' using errcode='42501';
  end if;
  if char_length(trim(coalesce(p_reason,'')))<10 then raise exception 'A substantive revocation reason is required'; end if;
  update public.credentials set status='revoked',revoked_at=now(),revocation_reason=trim(p_reason)
  where upper(credential_id)=upper(trim(p_credential_id)) and status='valid';
  get diagnostics v_count=row_count;
  if v_count<>1 then raise exception 'A valid credential matching that identifier was not found'; end if;
  return true;
end $$;
revoke all on function public.revoke_credential(text,text) from public,anon;
grant execute on function public.revoke_credential(text,text) to authenticated;
