create schema if not exists private;

create table if not exists public.data_science_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null check (module_id in ('01')),
  lesson_records jsonb not null default '{}'::jsonb,
  quiz_score numeric(5,2),
  quiz_passed boolean not null default false,
  quiz_attempts integer not null default 0 check (quiz_attempts between 0 and 2),
  module_completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id,module_id)
);

create table if not exists public.data_science_evidence (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null check (module_id in ('01')),
  evidence_type text not null,
  content text not null check (char_length(content) between 100 and 20000),
  status text not null default 'submitted' check (status in ('submitted','accepted','revision_required')),
  submitted_at timestamptz not null default now(),
  unique (user_id,module_id)
);

create table if not exists public.data_science_quiz_items (
  module_id text not null check (module_id in ('01')),
  question_id text not null,
  question_order integer not null,
  stem text not null,
  options jsonb not null check (jsonb_typeof(options)='array'),
  correct_option integer not null check (correct_option>=0),
  active boolean not null default true,
  primary key (module_id,question_id)
);

create table if not exists public.data_science_quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id text not null check (module_id in ('01')),
  answers jsonb not null,
  score numeric(5,2) not null,
  passed boolean not null,
  attempted_at timestamptz not null default now()
);

create index if not exists data_science_evidence_user_module_idx on public.data_science_evidence(user_id,module_id);
create index if not exists data_science_attempts_user_module_idx on public.data_science_quiz_attempts(user_id,module_id);

alter table public.data_science_progress enable row level security;
alter table public.data_science_evidence enable row level security;
alter table public.data_science_quiz_items enable row level security;
alter table public.data_science_quiz_attempts enable row level security;

revoke all on public.data_science_progress, public.data_science_evidence,
  public.data_science_quiz_items, public.data_science_quiz_attempts
  from public, anon, authenticated;

create or replace function private.data_science_require_user()
returns uuid language plpgsql stable security definer set search_path='' as $$
declare v_user uuid := auth.uid();
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  return v_user;
end $$;

create or replace function private.data_science_lessons_complete(p_user uuid)
returns boolean language sql stable security definer set search_path='' as $$
  select coalesce((lesson_records->>'01-0')::boolean,false)
     and coalesce((lesson_records->>'01-1')::boolean,false)
     and coalesce((lesson_records->>'01-2')::boolean,false)
  from public.data_science_progress where user_id=p_user and module_id='01'
$$;

create or replace function private.get_data_science_module1_state()
returns table(module_id text,lesson_records jsonb,evidence_submission jsonb,quiz_score numeric,
  quiz_passed boolean,quiz_attempts integer,module_completed_at timestamptz,module_02_unlocked boolean)
language sql stable security definer set search_path='' as $$
  select '01'::text,coalesce(p.lesson_records,'{}'::jsonb),
    (select jsonb_build_object('id',e.id,'evidence_type',e.evidence_type,'content',e.content,
      'status',e.status,'submitted_at',e.submitted_at)
     from public.data_science_evidence e where e.user_id=auth.uid() and e.module_id='01'),
    p.quiz_score,coalesce(p.quiz_passed,false),coalesce(p.quiz_attempts,0),p.module_completed_at,
    (p.module_completed_at is not null)
  from (values (1)) seed(n)
  left join public.data_science_progress p on p.user_id=auth.uid() and p.module_id='01'
$$;

create or replace function public.get_data_science_module1_state()
returns table(module_id text,lesson_records jsonb,evidence_submission jsonb,quiz_score numeric,
  quiz_passed boolean,quiz_attempts integer,module_completed_at timestamptz,module_02_unlocked boolean)
language sql stable security invoker set search_path='' as $$
  select * from private.get_data_science_module1_state()
$$;

create or replace function private.mark_data_science_lesson(p_lesson_index integer)
returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=private.data_science_require_user(); v_key text;
begin
  if p_lesson_index not between 0 and 2 then raise exception 'Invalid lesson'; end if;
  v_key:='01-'||p_lesson_index;
  insert into public.data_science_progress(user_id,module_id,lesson_records,updated_at)
  values(v_user,'01',jsonb_build_object(v_key,true),now())
  on conflict(user_id,module_id) do update set
    lesson_records=public.data_science_progress.lesson_records||excluded.lesson_records,updated_at=now();
end $$;

create or replace function public.mark_data_science_module1_lesson(p_lesson_index integer)
returns void language sql security invoker set search_path='' as $$
  select private.mark_data_science_lesson(p_lesson_index)
$$;

create or replace function private.submit_data_science_evidence(p_evidence_type text,p_content text)
returns bigint language plpgsql security definer set search_path='' as $$
declare v_user uuid:=private.data_science_require_user(); v_id bigint;
begin
  if not coalesce(private.data_science_lessons_complete(v_user),false) then
    raise exception 'Complete all three lesson records first';
  end if;
  if char_length(trim(p_content)) not between 100 and 20000 then
    raise exception 'Professional evidence must contain 100 to 20000 characters';
  end if;
  insert into public.data_science_evidence(user_id,module_id,evidence_type,content)
  values(v_user,'01',trim(p_evidence_type),trim(p_content)) returning id into v_id;
  return v_id;
end $$;

create or replace function public.submit_data_science_module1_evidence(p_evidence_type text,p_content text)
returns bigint language sql security invoker set search_path='' as $$
  select private.submit_data_science_evidence(p_evidence_type,p_content)
$$;

create or replace function private.get_data_science_module1_quiz()
returns table(question_id text,question_order integer,stem text,options jsonb)
language plpgsql stable security definer set search_path='' as $$
declare v_user uuid:=private.data_science_require_user();
begin
  if not coalesce(private.data_science_lessons_complete(v_user),false) then raise exception 'Complete all lesson records first'; end if;
  if not exists(select 1 from public.data_science_evidence where user_id=v_user and module_id='01') then
    raise exception 'Submit professional evidence before loading the quiz';
  end if;
  return query select q.question_id,q.question_order,q.stem,q.options
    from public.data_science_quiz_items q where q.module_id='01' and q.active order by q.question_order;
end $$;

create or replace function public.get_data_science_module1_quiz()
returns table(question_id text,question_order integer,stem text,options jsonb)
language sql stable security invoker set search_path='' as $$
  select * from private.get_data_science_module1_quiz()
$$;

create or replace function private.grade_data_science_module1(p_answers jsonb)
returns table(score numeric,passed boolean,attempts integer,module_02_unlocked boolean)
language plpgsql security definer set search_path='' as $$
declare
  v_user uuid:=private.data_science_require_user(); v_questions integer; v_answer_count integer;
  v_correct integer; v_attempts integer; v_score numeric(5,2); v_passed boolean; v_now timestamptz:=now();
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_user::text||':data-science:01',0));
  if not coalesce(private.data_science_lessons_complete(v_user),false) then raise exception 'Complete all lesson records first'; end if;
  if not exists(select 1 from public.data_science_evidence where user_id=v_user and module_id='01' and status in ('submitted','accepted')) then
    raise exception 'Submit professional evidence before attempting the quiz';
  end if;
  select count(*) into v_attempts from public.data_science_quiz_attempts where user_id=v_user and module_id='01';
  if v_attempts>=2 then raise exception 'Maximum quiz attempts reached'; end if;
  select count(*) into v_questions from public.data_science_quiz_items where module_id='01' and active;
  select count(*) into v_answer_count from jsonb_object_keys(coalesce(p_answers,'{}'::jsonb));
  if v_questions=0 then raise exception 'Quiz is not configured'; end if;
  if v_answer_count<>v_questions then raise exception 'Every active quiz question must be answered exactly once'; end if;
  if exists(select 1 from jsonb_object_keys(p_answers) a where not exists(
    select 1 from public.data_science_quiz_items q where q.module_id='01' and q.active and q.question_id=a)) then
    raise exception 'Answers contain an invalid question';
  end if;
  select count(*) into v_correct from public.data_science_quiz_items q
    where q.module_id='01' and q.active and p_answers?q.question_id and p_answers->>q.question_id=q.correct_option::text;
  v_score:=round((v_correct::numeric/v_questions)*100,2); v_passed:=v_score>=70;
  insert into public.data_science_quiz_attempts(user_id,module_id,answers,score,passed)
    values(v_user,'01',p_answers,v_score,v_passed);
  insert into public.data_science_progress(user_id,module_id,quiz_score,quiz_passed,quiz_attempts,module_completed_at,updated_at)
    values(v_user,'01',v_score,v_passed,v_attempts+1,case when v_passed then v_now end,v_now)
  on conflict(user_id,module_id) do update set
    quiz_score=greatest(coalesce(public.data_science_progress.quiz_score,0),excluded.quiz_score),
    quiz_passed=public.data_science_progress.quiz_passed or excluded.quiz_passed,
    quiz_attempts=excluded.quiz_attempts,
    module_completed_at=case when excluded.quiz_passed then coalesce(public.data_science_progress.module_completed_at,v_now)
      else public.data_science_progress.module_completed_at end,updated_at=v_now;
  return query select v_score::numeric,v_passed,v_attempts+1,v_passed;
end $$;

create or replace function public.grade_data_science_module1_quiz(p_answers jsonb)
returns table(score numeric,passed boolean,attempts integer,module_02_unlocked boolean)
language sql security invoker set search_path='' as $$
  select * from private.grade_data_science_module1(p_answers)
$$;

revoke all on schema private from public,anon,authenticated;
grant usage on schema private to authenticated;
revoke all on all functions in schema private from public,anon,authenticated;
grant execute on function private.data_science_require_user(),private.data_science_lessons_complete(uuid),
  private.get_data_science_module1_state(),private.mark_data_science_lesson(integer),
  private.submit_data_science_evidence(text,text),private.get_data_science_module1_quiz(),
  private.grade_data_science_module1(jsonb) to authenticated;

revoke all on function public.get_data_science_module1_state(),public.mark_data_science_module1_lesson(integer),
  public.submit_data_science_module1_evidence(text,text),public.get_data_science_module1_quiz(),
  public.grade_data_science_module1_quiz(jsonb) from public,anon;
grant execute on function public.get_data_science_module1_state(),public.mark_data_science_module1_lesson(integer),
  public.submit_data_science_module1_evidence(text,text),public.get_data_science_module1_quiz(),
  public.grade_data_science_module1_quiz(jsonb) to authenticated;

insert into public.data_science_quiz_items(module_id,question_id,question_order,stem,options,correct_option) values
('01','ds01-q1',1,'What is the strongest starting point for a data science assignment?',
 '["Choose a model","Clarify the decision, decision owner and evidence need","Collect every available field","Build a dashboard"]',1),
('01','ds01-q2',2,'Which statement best distinguishes data from evidence?',
 '["They are synonyms","Evidence is data assessed against a specific claim or question","Evidence must be qualitative","Data become evidence after visualisation"]',1),
('01','ds01-q3',3,'A validation problem reveals that the analytical question is infeasible. What should happen?',
 '["Hide the limitation","Document the finding and return to problem framing","Use a more complex algorithm","Publish the preliminary result"]',1),
('01','ds01-q4',4,'Which record most improves reproducibility?',
 '["A screenshot of the final chart","Source, extraction date, transformations, code, assumptions and validation results","A verbal explanation","Only the cleaned dataset"]',1)
on conflict(module_id,question_id) do update set question_order=excluded.question_order,stem=excluded.stem,
 options=excluded.options,correct_option=excluded.correct_option,active=true;
