-- Original DatalytIQs CA35P mock. No historical examination text is reproduced.
-- Keys remain in private schema; learner attempts are written through authenticated RPCs.
update public.exam_assessments set title='CA35P Full Online Mock · Evidence and Decision Case',max_attempts=2,metadata=metadata || '{"total_marks":100,"delivery":"timed online assignment with assessor-reviewed practicals"}'::jsonb where assessment_type='mock' and programme_id=(select id from public.exam_programmes where code='CA35P') and status='published';
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','The 12 sales rows sum to KES 958,750. A PivotTable shows KES 882,500 after a new row was appended. Which control should be checked first?','[{"value": "a", "label": "Change the rate assumption"}, {"value": "b", "label": "Refresh and verify the PivotTable source range"}, {"value": "c", "label": "Hide the missing row"}, {"value": "d", "label": "Overwrite the PivotTable total"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M01'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='1.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M01');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','b'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M01' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,1,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M01' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','Western revenue is KES 330,250 and Nairobi revenue is KES 325,000. What is the difference?','[{"value": "a", "label": "KES 5,250"}, {"value": "b", "label": "KES 25,000"}, {"value": "c", "label": "KES 55,250"}, {"value": "d", "label": "KES 655,250"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M02'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='1.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M02');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','a'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M02' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,2,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M02' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','Six transactions have margin below target. Which Excel expression flags a row when actual margin is less than target?','[{"value": "a", "label": "=IF([@Margin_Percent]<[@Target_Margin_Percent],\"Below\",\"On target\")"}, {"value": "b", "label": "=SUM([@Margin_Percent]:[@Target_Margin_Percent])"}, {"value": "c", "label": "=COUNTBLANK([@Revenue])"}, {"value": "d", "label": "=IFERROR([@Region],\"Below\")"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M03'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='1.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M03');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','a'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M03' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,3,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M03' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','The model has fixed cost KES 820,000 and contribution KES 1,050 per unit. What is the minimum whole-unit break-even volume?','[{"value": "a", "label": "780"}, {"value": "b", "label": "781"}, {"value": "c", "label": "820"}, {"value": "d", "label": "1,050"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M04'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='1.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M04');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','b'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M04' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,4,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M04' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','A school fee-support team has not agreed what successful support means. What should CRISP-DM resolve before modelling?','[{"value": "a", "label": "The dashboard colour"}, {"value": "b", "label": "The business decision, outcome and success measure"}, {"value": "c", "label": "The final chart export"}, {"value": "d", "label": "The modelling library"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M05'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='2.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M05');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','b'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M05' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,5,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M05' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','Organic traffic recorded 744 conversions from 12,400 visits in January. What is its conversion rate?','[{"value": "a", "label": "4.0%"}, {"value": "b", "label": "5.0%"}, {"value": "c", "label": "6.0%"}, {"value": "d", "label": "7.44%"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M06'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='2.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M06');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','c'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M06' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,6,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M06' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','April Organic visits rose to 15,300 but conversions fell to 704. Which claim is justified?','[{"value": "a", "label": "Conversion improved because visits rose"}, {"value": "b", "label": "The campaign caused every lost conversion"}, {"value": "c", "label": "Conversion rate fell to about 4.60%"}, {"value": "d", "label": "Revenue must have increased"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M07'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='2.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M07');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','c'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M07' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,7,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M07' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','A continuously arriving clickstream includes duplicate event IDs. Which 5V directly concerns the duplicate records?','[{"value": "a", "label": "Value"}, {"value": "b", "label": "Velocity"}, {"value": "c", "label": "Volume"}, {"value": "d", "label": "Veracity"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M08'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='2.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M08');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','d'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M08' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,8,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M08' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','2025 revenue is KES 23,184,000 and cost of sales KES 14,374,000. What is gross profit?','[{"value": "a", "label": "KES 8,810,000"}, {"value": "b", "label": "KES 9,740,000"}, {"value": "c", "label": "KES 14,374,000"}, {"value": "d", "label": "KES 37,558,000"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M09'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='3.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M09');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','a'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M09' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,9,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M09' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','Trade receivables grew from KES 2.13m in 2023 to KES 4.47m in 2025 while revenue grew more slowly. What should be investigated?','[{"value": "a", "label": "Only rounding conventions"}, {"value": "b", "label": "Collection timing, ageing and credit terms"}, {"value": "c", "label": "The font used in the report"}, {"value": "d", "label": "A guaranteed profit increase"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M10'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='3.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M10');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','b'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M10' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,10,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M10' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','A project invests KES 4.5m at year 0. Which Excel pattern treats the initial outflow correctly?','[{"value": "a", "label": "=NPV(rate,year1:year5)+year0"}, {"value": "b", "label": "=NPV(rate,year0:year5)"}, {"value": "c", "label": "=year0/NPV(rate,year1:year5)"}, {"value": "d", "label": "=SUM(year0:year5)"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M11'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='3.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M11');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','a'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M11' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,11,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M11' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','Base NPV is positive at 12%; downside NPV is negative at its 14% rate. Which recommendation is defensible?','[{"value": "a", "label": "Accept unconditionally"}, {"value": "b", "label": "Reject every project with positive base NPV"}, {"value": "c", "label": "Report both cases and the drivers of reversal"}, {"value": "d", "label": "Ignore the downside discount rate"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M12'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='3.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M12');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','c'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M12' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,12,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M12' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','Direct materials budget is KES 3.2m for 8,000 units. At 8,600 units, what is the flexed allowance?','[{"value": "a", "label": "KES 3,200,000"}, {"value": "b", "label": "KES 3,440,000"}, {"value": "c", "label": "KES 3,698,000"}, {"value": "d", "label": "KES 4,000,000"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M13'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='4.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M13');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','b'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M13' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,13,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M13' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','T002 invoices KES 490,000 against a KES 475,000 receipt. What is the exception amount?','[{"value": "a", "label": "KES 15,000"}, {"value": "b", "label": "KES 25,000"}, {"value": "c", "label": "KES 475,000"}, {"value": "d", "label": "KES 965,000"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M14'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='4.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M14');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','a'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M14' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,14,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M14' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','Alpha Supplies invoice AS-1042 appears in T001 and T003. What is the sound conclusion?','[{"value": "a", "label": "Fraud is proven"}, {"value": "b", "label": "The duplicate indicator requires document and payment checks"}, {"value": "c", "label": "Both invoices must be deleted"}, {"value": "d", "label": "No investigation is needed"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M15'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='4.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M15');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','b'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M15' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,15,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M15' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','A revised budget is KES 10m and actual spending KES 9m for the same period. What is execution against the revised budget?','[{"value": "a", "label": "9%"}, {"value": "b", "label": "10%"}, {"value": "c", "label": "90%"}, {"value": "d", "label": "110%"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M16'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='4.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M16');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','c'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M16' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,16,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M16' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','Risk R01 has likelihood 4 and impact 5. What is its simple risk score?','[{"value": "a", "label": "9"}, {"value": "b", "label": "15"}, {"value": "c", "label": "20"}, {"value": "d", "label": "45"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M17'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='5.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M17');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','c'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M17' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,17,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M17' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','A regional dashboard only needs counts but its source has national IDs. What is the appropriate design?','[{"value": "a", "label": "Publish all identifiers"}, {"value": "b", "label": "Remove unneeded identifiers and restrict source access"}, {"value": "c", "label": "Copy IDs into chart labels"}, {"value": "d", "label": "Keep the source indefinitely"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M18'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='5.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M18');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','b'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M18' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,18,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M18' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','A daily customer model has 780,000 rows, sensitive data and eight users. What should guide tool selection?','[{"value": "a", "label": "Popularity alone"}, {"value": "b", "label": "Constrained workbook colours"}, {"value": "c", "label": "Governed processing, access, auditability and recovery"}, {"value": "d", "label": "Maximum number of charts"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M19'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='5.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M19');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','c'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M19' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,19,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M19' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,options,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'single_choice','A late correction changes a published KPI. Which record preserves custody?','[{"value": "a", "label": "Overwrite the old report silently"}, {"value": "b", "label": "Keep source version, reason, approver, recalculation and notice"}, {"value": "c", "label": "Delete the previous value"}, {"value": "d", "label": "Hide the correction until year-end"}]'::jsonb,'intermediate','original',jsonb_build_object('mock_code','M20'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='5.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M20');
insert into private.exam_question_keys(question_id,answer_key,explanation) select q.id,jsonb_build_object('correct_option','b'),'Review the source figures and reasoning in the case before retrying.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='M20' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,20,1 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='M20' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'practical','Using the 12-row sales CSV, describe a workbook with Source, Controls, Analysis and Output sheets. Calculate total revenue, all three regional totals, the six below-target transaction IDs, and a formula-level check. Reconcile every subtotal and recommend one management action. Include exact formulas or pseudocode, units, assumptions and any exception.','advanced','original',jsonb_build_object('mock_code','P1','title','Controlled workbook and reconciliation'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='1.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='P1');
insert into private.exam_question_keys(question_id,answer_key,rubric,explanation) select q.id,'{}'::jsonb,'{"method":5,"accuracy":5,"interpretation":5,"recommendation":5}'::jsonb,'Sales total KES 958,750; Western 330,250, Nairobi 325,000, Nyanza 303,500; below-target T002 T004 T007 T008 T011 T012. Assess traceability, correct figures, reconciliation and justified recommendation.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='P1' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,21,20 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='P1' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'practical','A channel manager sees Organic visits rise from 12,400 in January to 15,300 in April while conversions fall from 744 to 704. Calculate both conversion rates, design two labelled charts and a quality-control check. Define a CRISP-DM decision and explain why the trend alone does not prove a cause.','advanced','original',jsonb_build_object('mock_code','P2','title','Decision method and visual evidence'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='2.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='P2');
insert into private.exam_question_keys(question_id,answer_key,rubric,explanation) select q.id,'{}'::jsonb,'{"method":5,"accuracy":5,"interpretation":5,"recommendation":5}'::jsonb,'January Organic 6.00%, April Organic about 4.60%. Explain denominator, date and source controls; separate observation from causal inference.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='P2' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,22,20 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='P2' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'practical','Using the financial statement and investment CSVs, calculate 2025 gross profit and receivables/revenue. Calculate base NPV at 12% and downside NPV at 14%, keeping the initial KES 4.5m at time zero. Recommend whether to proceed, defer or revise, with two controls and limitations.','advanced','original',jsonb_build_object('mock_code','P3','title','Investment and financial-risk memorandum'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='3.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='P3');
insert into private.exam_question_keys(question_id,answer_key,rubric,explanation) select q.id,'{}'::jsonb,'{"method":5,"accuracy":5,"interpretation":5,"recommendation":5}'::jsonb,'Gross profit KES 8.81m; receivables/revenue 19.28%; base NPV about +KES 366,448; downside NPV about -KES 328,807. Penalise discounting time-zero outflow twice or using 12% for both scenarios.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='P3' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,23,20 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='P3' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'practical','Analyse the audit and budget CSVs. Identify duplicate supplier-invoice IDs, calculate T002 and T007 invoice-receipt differences and the flexed Direct materials allowance for 8,600 units assuming the KES 3.2m static budget covers 8,000 units. Specify three follow-up procedures; avoid claiming a flag proves fraud.','advanced','original',jsonb_build_object('mock_code','S-FIN','title','Specialisation: audit and budget exceptions'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='4.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='S-FIN');
insert into private.exam_question_keys(question_id,answer_key,rubric,explanation) select q.id,'{}'::jsonb,'{"method":5,"accuracy":5,"interpretation":5,"recommendation":5}'::jsonb,'T001/T003 duplicate; T002 KES 15,000; T007 KES 17,000; flexed materials KES 3,440,000, actual KES 3,698,000, adverse KES 258,000. Require evidence follow-up and period assumptions.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='S-FIN' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,24,20 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='S-FIN' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;
insert into public.exam_questions(programme_id,syllabus_version_id,topic_id,question_type,stem,difficulty,provenance,rights_metadata,status) select a.programme_id,a.syllabus_version_id,t.id,'practical','Using the risk register and tool assessment CSVs, score R01–R05, identify the highest two risks and recommend a controlled platform for the sensitive daily customer-risk model. Specify owners, release gates, monitoring measures and incident response. Explain why a simple risk product does not establish residual safety.','advanced','original',jsonb_build_object('mock_code','S-GOV','title','Specialisation: governed model release'),'published' from public.exam_assessments a join public.exam_topics t on t.syllabus_version_id=a.syllabus_version_id and t.code='5.0' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') and not exists(select 1 from public.exam_questions q where q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='S-GOV');
insert into private.exam_question_keys(question_id,answer_key,rubric,explanation) select q.id,'{}'::jsonb,'{"method":5,"accuracy":5,"interpretation":5,"recommendation":5}'::jsonb,'R01=20, R02=15, R03=20, R04=12, R05=12. Highest R01 and R03. Governed platform with purpose, access, audit, recovery, fairness and owner sign-off; measure residual control performance.' from public.exam_questions q where q.programme_id=(select id from public.exam_programmes where code='CA35P') and q.rights_metadata->>'mock_code'='S-GOV' on conflict(question_id) do nothing;
insert into public.exam_assessment_items(assessment_id,question_id,sequence_no,points) select a.id,q.id,25,20 from public.exam_assessments a join public.exam_questions q on q.programme_id=a.programme_id and q.rights_metadata->>'mock_code'='S-GOV' where a.assessment_type='mock' and a.programme_id=(select id from public.exam_programmes where code='CA35P') on conflict do nothing;

create or replace function public.start_ca35p_mock()
returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=(select auth.uid()); v_assessment public.exam_assessments%rowtype; v_enrollment uuid; v_attempt uuid; v_count integer;
begin
 if v_user is null then raise exception 'Sign in required'; end if;
 select a.* into v_assessment from public.exam_assessments a join public.exam_programmes p on p.id=a.programme_id where p.code='CA35P' and a.assessment_type='mock' and a.status='published' limit 1;
 if v_assessment.id is null or (select count(*) from public.exam_assessment_items where assessment_id=v_assessment.id)<>25 then raise exception 'Mock assignment is unavailable'; end if;
 select e.id into v_enrollment from public.exam_enrollments e where e.user_id=v_user and e.programme_id=v_assessment.programme_id and e.status='active';
 if v_enrollment is null or not exists(select 1 from public.exam_access_grants g where g.user_id=v_user and g.programme_id=v_assessment.programme_id and g.access_level='full' and g.revoked_at is null and g.starts_at<=now() and (g.expires_at is null or g.expires_at>now())) then raise exception 'Active full programme access required'; end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(v_user::text||v_assessment.id::text));
 select id into v_attempt from public.exam_assessment_attempts where assessment_id=v_assessment.id and user_id=v_user and status='in_progress' order by started_at desc limit 1;
 if v_attempt is not null then
   if exists(select 1 from public.exam_assessment_attempts where id=v_attempt and started_at+make_interval(mins=>v_assessment.time_limit_minutes)<=now()) then
     perform public.submit_ca35p_mock(v_attempt); v_attempt:=null;
   else return v_attempt; end if;
 end if;
 select count(*) into v_count from public.exam_assessment_attempts where assessment_id=v_assessment.id and user_id=v_user;
 if v_assessment.max_attempts is not null and v_count>=v_assessment.max_attempts then raise exception 'Maximum attempts reached'; end if;
 insert into public.exam_assessment_attempts(assessment_id,enrollment_id,user_id,attempt_no,integrity_metadata) values(v_assessment.id,v_enrollment,v_user,v_count+1,jsonb_build_object('version','ca35p-original-2026-09')) returning id into v_attempt;
 return v_attempt;
end $$;

create or replace function public.save_ca35p_mock(p_attempt_id uuid,p_responses jsonb)
returns integer language plpgsql security definer set search_path='' as $$
declare v_user uuid:=(select auth.uid()); v_attempt public.exam_assessment_attempts%rowtype; v_item record; v_value text; v_saved integer:=0;
begin
 if v_user is null then raise exception 'Sign in required'; end if;
 select * into v_attempt from public.exam_assessment_attempts where id=p_attempt_id and user_id=v_user and status='in_progress' for update;
 if v_attempt.id is null or not exists(select 1 from public.exam_assessments a join public.exam_programmes p on p.id=a.programme_id where a.id=v_attempt.assessment_id and a.assessment_type='mock' and p.code='CA35P') then raise exception 'Mock attempt not found or already submitted'; end if;
 if now() >= v_attempt.started_at+interval '180 minutes' then raise exception 'Time has expired. Submit the saved draft.'; end if;
 if not exists(select 1 from public.exam_access_grants g join public.exam_assessments a on a.programme_id=g.programme_id where a.id=v_attempt.assessment_id and g.user_id=v_user and g.access_level='full' and g.revoked_at is null and g.starts_at<=now() and (g.expires_at is null or g.expires_at>now())) then raise exception 'Full access is no longer active'; end if;
 if pg_catalog.jsonb_typeof(p_responses)<>'object' or (select count(*) from pg_catalog.jsonb_object_keys(p_responses))>25 then raise exception 'Invalid response set'; end if;
 for v_item in select i.question_id,q.question_type,q.rights_metadata->>'mock_code' as code from public.exam_assessment_items i join public.exam_questions q on q.id=i.question_id where i.assessment_id=v_attempt.assessment_id loop
   if p_responses ? v_item.code then
     v_value:=p_responses->>v_item.code;
     if length(v_value)>5000 then raise exception 'Response too long'; end if;
     if v_item.question_type='single_choice' and v_value not in ('a','b','c','d','') then raise exception 'Invalid choice'; end if;
     insert into public.exam_assessment_responses(attempt_id,question_id,response,answered_at) values(p_attempt_id,v_item.question_id,jsonb_build_object('value',v_value),now()) on conflict(attempt_id,question_id) do update set response=excluded.response,answered_at=now();
     v_saved:=v_saved+1;
   end if;
 end loop;
 if (select count(*) from pg_catalog.jsonb_object_keys(p_responses))<>v_saved then raise exception 'Unknown question code'; end if;
 return v_saved;
end $$;

create or replace function public.submit_ca35p_mock(p_attempt_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=(select auth.uid()); v_attempt public.exam_assessment_attempts%rowtype; v_mc integer; v_core integer; v_special integer; v_missing integer;
begin
 if v_user is null then raise exception 'Sign in required'; end if;
 select * into v_attempt from public.exam_assessment_attempts where id=p_attempt_id and user_id=v_user and status='in_progress' for update;
 if v_attempt.id is null or not exists(select 1 from public.exam_assessments a join public.exam_programmes p on p.id=a.programme_id where a.id=v_attempt.assessment_id and a.assessment_type='mock' and p.code='CA35P') then raise exception 'Mock attempt not found or already submitted'; end if;
 select count(*) into v_missing from public.exam_assessment_items i join public.exam_questions q on q.id=i.question_id left join public.exam_assessment_responses r on r.attempt_id=p_attempt_id and r.question_id=i.question_id where i.assessment_id=v_attempt.assessment_id and (q.rights_metadata->>'mock_code' ~ '^M[0-9]{2}$' or q.rights_metadata->>'mock_code' in ('P1','P2','P3')) and (r.id is null or length(trim(r.response->>'value'))<case when q.question_type='practical' then 250 else 1 end);
 select count(*) into v_special from public.exam_assessment_responses r join public.exam_questions q on q.id=r.question_id where r.attempt_id=p_attempt_id and q.rights_metadata->>'mock_code' in ('S-FIN','S-GOV') and length(trim(r.response->>'value'))>=250;
 if now()<v_attempt.started_at+interval '180 minutes' and (v_missing>0 or v_special<>1) then raise exception 'Complete all 20 questions, three practicals and exactly one specialisation before submission'; end if;
 if now()>=v_attempt.started_at+interval '180 minutes' then
   insert into public.exam_assessment_responses(attempt_id,question_id,response) select p_attempt_id,q.id,jsonb_build_object('value','') from public.exam_assessment_items i join public.exam_questions q on q.id=i.question_id where i.assessment_id=v_attempt.assessment_id and q.rights_metadata->>'mock_code' in ('P1','P2','P3') on conflict(attempt_id,question_id) do nothing;
   if v_special=0 then insert into public.exam_assessment_responses(attempt_id,question_id,response) select p_attempt_id,q.id,jsonb_build_object('value','') from public.exam_assessment_items i join public.exam_questions q on q.id=i.question_id where i.assessment_id=v_attempt.assessment_id and q.rights_metadata->>'mock_code'='S-FIN' on conflict(attempt_id,question_id) do nothing; end if;
 end if;
 update public.exam_assessment_responses r set awarded_points=case when r.response->>'value'=k.answer_key->>'correct_option' then 1 else 0 end,grader_feedback=case when r.response->>'value'=k.answer_key->>'correct_option' then 'Correct' else 'Review the source data and method' end from private.exam_question_keys k, public.exam_questions q where r.attempt_id=p_attempt_id and k.question_id=r.question_id and q.id=r.question_id and q.question_type='single_choice';
 select coalesce(sum(r.awarded_points),0)::integer into v_mc from public.exam_assessment_responses r join public.exam_questions q on q.id=r.question_id where r.attempt_id=p_attempt_id and q.question_type='single_choice';
 update public.exam_assessment_attempts set status='submitted',submitted_at=now(),score=v_mc,percentage=v_mc,integrity_metadata=integrity_metadata || jsonb_build_object('mc_score',v_mc,'expired',now()>=started_at+interval '180 minutes') where id=p_attempt_id;
 return jsonb_build_object('status','submitted','mc_score',v_mc,'practical_pending',true);
end $$;

create or replace function public.review_ca35p_mock(p_attempt_id uuid,p_scores jsonb,p_feedback text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_reviewer uuid:=(select auth.uid()); v_attempt public.exam_assessment_attempts%rowtype; v_item record; v_score integer; v_total integer:=0; v_mc integer; v_count integer:=0;
begin
 if v_reviewer is null then raise exception 'Sign in required'; end if;
 select * into v_attempt from public.exam_assessment_attempts where id=p_attempt_id and status='submitted' for update;
 if v_attempt.id is null or not exists(select 1 from public.exam_assessments a join public.exam_programmes p on p.id=a.programme_id where a.id=v_attempt.assessment_id and a.assessment_type='mock' and p.code='CA35P') then raise exception 'Pending mock attempt not found'; end if;
 if v_attempt.user_id=v_reviewer then raise exception 'A reviewer cannot grade their own attempt'; end if;
 if not exists(select 1 from public.exam_assessment_attempts at join public.exam_assessments a on a.id=at.assessment_id join public.exam_programme_staff s on s.programme_id=a.programme_id and s.user_id=v_reviewer where at.id=p_attempt_id and s.active and s.role in ('reviewer','instructor','administrator')) then raise exception 'Reviewer role required'; end if;
 if length(trim(p_feedback))<30 or length(trim(p_feedback))>3000 or pg_catalog.jsonb_typeof(p_scores)<>'object' then raise exception 'Meaningful feedback and scores required'; end if;
 for v_item in select r.id,q.rights_metadata->>'mock_code' as code from public.exam_assessment_responses r join public.exam_questions q on q.id=r.question_id where r.attempt_id=p_attempt_id and q.question_type='practical' and (q.rights_metadata->>'mock_code' in ('P1','P2','P3') or (q.rights_metadata->>'mock_code' in ('S-FIN','S-GOV') and r.id=(select r2.id from public.exam_assessment_responses r2 join public.exam_questions q2 on q2.id=r2.question_id where r2.attempt_id=p_attempt_id and q2.rights_metadata->>'mock_code' in ('S-FIN','S-GOV') order by case when length(trim(r2.response->>'value'))>0 then 0 else 1 end, q2.rights_metadata->>'mock_code' limit 1))) loop
   if not (p_scores ? v_item.code) or (p_scores->>v_item.code) !~ '^(0|[1-9]|1[0-9]|20)$' then raise exception 'Every submitted practical needs a score from 0 to 20'; end if;
   v_score:=(p_scores->>v_item.code)::integer;
   update public.exam_assessment_responses set awarded_points=v_score,grader_feedback=trim(p_feedback),graded_by=v_reviewer where id=v_item.id;
   v_total:=v_total+v_score;v_count:=v_count+1;
 end loop;
 if v_count<>4 or (select count(*) from pg_catalog.jsonb_object_keys(p_scores))<>4 then raise exception 'Exactly four practical scores required'; end if;
 v_mc:=coalesce((v_attempt.integrity_metadata->>'mc_score')::integer,0);
 update public.exam_assessment_attempts set status='graded',graded_at=now(),score=v_mc+v_total,percentage=v_mc+v_total,passed=v_mc+v_total>=(select pass_mark from public.exam_assessments where id=v_attempt.assessment_id),integrity_metadata=integrity_metadata || jsonb_build_object('reviewed_by',v_reviewer,'practical_score',v_total,'reviewer_feedback',trim(p_feedback)) where id=p_attempt_id;
 return jsonb_build_object('score',v_mc+v_total,'passed',v_mc+v_total>=(select pass_mark from public.exam_assessments where id=v_attempt.assessment_id));
end $$;

revoke all on function public.start_ca35p_mock() from public,anon;
revoke all on function public.save_ca35p_mock(uuid,jsonb) from public,anon;
revoke all on function public.submit_ca35p_mock(uuid) from public,anon;
revoke all on function public.review_ca35p_mock(uuid,jsonb,text) from public,anon;
grant execute on function public.start_ca35p_mock() to authenticated;
grant execute on function public.save_ca35p_mock(uuid,jsonb) to authenticated;
grant execute on function public.submit_ca35p_mock(uuid) to authenticated;
grant execute on function public.review_ca35p_mock(uuid,jsonb,text) to authenticated;
