import type { Metadata } from 'next'
import Link from 'next/link'
import '../young-analysts.css'

export const metadata: Metadata={title:'Young Analysts Club for Schools | DatalytIQs',description:'A structured coding, data and AI club with curriculum, challenges, instructor materials, assessment and progress analytics.'}

export default function SchoolsPage(){
 const features=[['CURRICULUM','A staged competency framework instead of disconnected computer-club activities.'],['CHALLENGES','Reusable coding, data and research tasks that require an evidence product and explanation.'],['FACILITATION','Session plans, learner briefs, datasets, review criteria and model guidance for instructors.'],['EVIDENCE','Private learner submissions support feedback, reflection and progression decisions.'],['ANALYTICS','Cohort-level instructional signals without public child ranking or high-stakes automated judgement.'],['SHOWCASE','Optional school or inter-school challenge work using reviewed, consent-aware presentation rules.']]
 const implementation=[['1','Readiness','Confirm coordinator, instructor capacity, devices, connectivity and safeguarding responsibilities.'],['2','Set-up','Create institution, club and cohort roles; enrol only the minimum learner information required.'],['3','Baseline','Use a low-stakes diagnostic task to identify an appropriate starting point.'],['4','Delivery','Run guided sessions and challenges; store private evidence against competencies.'],['5','Review','Use instructor feedback, learner reflection and cohort signals to target support.'],['6','Report','Share useful progress summaries without public ranking or unnecessary personal data.']]
 return <main id="main-content" className="ya-shell"><a className="ya-skip" href="#main-content">Skip to content</a><header className="ya-nav"><Link href="/young-analysts" className="ya-brand"><b>D</b><span><strong>Young Analysts Club</strong><small>DatalytIQs Academy · For schools</small></span></Link><nav aria-label="School programme navigation"><Link href="/young-analysts">Academy</Link><a href="#model">Club model</a><a href="#implementation">Implementation</a><a href="#access">Access</a></nav></header>
 <section className="ya-hero ya-school-hero"><div><span className="ya-kicker">SCHOOL PROGRAMME</span><h1>Build durable data and digital capability <em>inside the school.</em></h1><p>The club model combines a curriculum, practical challenges, instructor support, evidence review and progress reporting. Technology supports teaching; it does not replace professional judgement.</p></div><aside><span>INSTITUTION MODEL</span>{['Institution','Club','Cohort','Instructor','Learner','Evidence'].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><strong>{x}</strong></div>)}</aside></section>
 <section id="model" className="ya-section"><header><span className="ya-kicker">WHAT THE SCHOOL RECEIVES</span><h2>One operating model, reusable across cohorts.</h2><p>The model separates curriculum, evidence and role access so a school can scale without turning learner progress into a public competition.</p></header><div className="ya-grid products">{features.map(([t,d])=><article key={t}><span>PROGRAMME COMPONENT</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section id="implementation" className="ya-section ya-courses"><header><span className="ya-kicker">IMPLEMENTATION CYCLE</span><h2>From readiness to useful reporting.</h2><p>A school deployment should establish people, safeguarding and instructional routines before adding real learner data.</p></header><div className="ya-grid products">{implementation.map(([n,t,d])=><article key={n}><span>STEP {n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section id="access" className="ya-school"><div><span className="ya-kicker">LICENSING & ACCESS ARCHITECTURE</span><h2>School access is an institutional entitlement.</h2><p>The intended hierarchy is Institution → Club → Cohort → authorised role → learner evidence. Real deployment still requires technical role enforcement and verified guardian relationships; this page does not claim those controls are already live.</p></div><div className="ya-school-flow">{['Institution licence','Coordinator','Cohort','Instructor','Private evidence','Progress report'].map((x,i)=><p key={x}><b>{i+1}</b>{x}</p>)}</div></section>
 </main>
}