'use client'

import {useMemo,useState} from 'react'

type Lesson='1'|'2'|'3'
type Check={prompt:string;options:string[];answer:number;feedback:string}

const content={
 '1':{title:'From Indicator to Data Requirement',duration:'40–50 minutes',outcomes:['Decompose an indicator into variables, population, unit and reference period.','Distinguish a data requirement from a source, method, tool or report.','Specify disaggregation, verification and protection requirements before collection.']},
 '2':{title:'Select Sources, Methods and Frequency',duration:'45–55 minutes',outcomes:['Match evidence sources and methods to a decision and indicator.','Set collection frequency from decision timing, volatility and burden.','Triangulate proportionately without collecting duplicate data.']},
 '3':{title:'Build and Review a Data-Collection Plan',duration:'50–65 minutes',outcomes:['Integrate indicators, methods, schedules, roles and safeguards.','Diagnose feasibility, quality and ethical weaknesses before deployment.','Produce an operational plan ready for technical review.']},
} as const

const checks:Record<Lesson,Check[]>={
 '1':[
  {prompt:'Which statement is a data requirement?',options:['Use KoboToolbox','Employment status six months after verified completion','Administer a telephone survey','Publish a quarterly dashboard'],answer:1,feedback:'The requirement defines what must be known and when. The other options describe a tool, method or reporting product.'},
  {prompt:'What should happen before choosing a questionnaire?',options:['Select a dashboard colour','Define the decision, indicator and required variables','Recruit enumerators','Export the beneficiary list'],answer:1,feedback:'The decision and measurement requirements determine whether a questionnaire is needed and what it should contain.'},
 ],
 '2':[
  {prompt:'A monthly management meeting can still change outreach deployment. When should outreach coverage data normally be available?',options:['Every five years','Only at final evaluation','Before each monthly decision meeting','Whenever a donor requests it'],answer:2,feedback:'Frequency should match a realistic decision cycle and the rate at which the measure can change.'},
  {prompt:'Which approach is strongest for verifying employment quality?',options:['Use enrolment records alone','Accept every self-report without definitions','Combine a standard tracer interview with proportionate verification','Call every employer every day'],answer:2,feedback:'Proportionate triangulation improves confidence while controlling cost, burden and privacy risk.'},
 ],
 '3':[
  {prompt:'Who should be named in an operational collection plan?',options:['Only the donor','A responsible role for collection, quality review and decision use','Every citizen in the county','Nobody; responsibility should remain flexible'],answer:1,feedback:'Named roles make collection, review, escalation and use accountable without relying on vague institutional ownership.'},
  {prompt:'What is the best response to an indicator whose data cost exceeds its decision value?',options:['Collect it because it is in the logframe','Hide the cost','Redesign, reduce frequency or replace it through documented governance','Increase the sample automatically'],answer:2,feedback:'Data requirements should be governed. Redesign must be documented so that comparability and accountability are not quietly lost.'},
 ],
}

const scenarios=[
 {indicator:'Monthly training attendance by centre',source:'Signed attendance register plus learner identifier validation',method:'Routine administrative extraction',frequency:'Monthly, before operations review',risk:'Duplicate or proxy attendance',control:'Unique identifier checks and supervisor spot verification'},
 {indicator:'Completion rate by disability status',source:'Verified enrolment and completion records',method:'Cohort reconciliation',frequency:'At cohort close, with monthly exception checks',risk:'Non-disclosure or inconsistent disability classification',control:'Voluntary Washington Group-aligned questions, restricted access and documented missingness'},
 {indicator:'Decent employment six months after graduation',source:'Graduate tracer responses with proportionate employer/document verification',method:'Structured follow-up',frequency:'Six months after each cohort completes',risk:'Attrition and social-desirability bias',control:'Multiple consented contact routes, non-response analysis and standard criteria'},
]

export default function LessonExperience({lesson}:{lesson:Lesson}){
 const info=content[lesson]
 const[selected,setSelected]=useState<Record<number,number>>({})
 const score=useMemo(()=>checks[lesson].filter((item,index)=>selected[index]===item.answer).length,[lesson,selected])
 return <main className="lesson-shell">
  <nav aria-label="Breadcrumb"><a href="/merl/applied">MERL Level 2</a><span aria-hidden="true"> / </span><span>Module 06</span><span aria-hidden="true"> / </span><span>Lesson 06.{lesson}</span></nav>
  <header><div><p>LESSON 06.{lesson} · {info.duration}</p><h1>{info.title}</h1><span>County Youth Employment Programme · operationalise measurement before collecting data.</span></div><aside><b>MODULE 06</b><span>Lesson {lesson} of 3</span></aside></header>
  <div className="layout"><article>
   <section className="card"><h2>Learning outcomes</h2><ul>{info.outcomes.map(outcome=><li key={outcome}>{outcome}</li>)}</ul></section>
   {lesson==='1'&&<><section><h2>Begin with the decision—not the questionnaire</h2><p>A data requirement states exactly what information is needed, about whom or what, for which period and decision. A source identifies where that information may exist. A method explains how it will be obtained. A tool records it.</p><div className="principle"><b>Indicator → decision → required variables → source → method → tool → quality control</b></div></section><section><h2>Worked decomposition</h2><p>For “percentage of programme graduates in decent employment six months after completion,” define the eligible cohort, completion date, follow-up date, employment criteria, verification rule, non-response treatment and required disaggregation. None should be improvised after data collection.</p></section></>}
   {lesson==='2'&&<><section><h2>Choose evidence proportionately</h2><div className="concept-grid"><div><h3>Source fitness</h3><p>Assess coverage, timeliness, accessibility, definitions, incentives and known error—not merely whether data exist.</p></div><div><h3>Method fitness</h3><p>Match routine extraction, observation, interview, survey or record linkage to the question and population.</p></div><div><h3>Frequency fitness</h3><p>Collect often enough to support action, but not faster than the indicator changes or the organisation can respond.</p></div></div><p className="principle"><b>More frequent data are not automatically better data; sometimes they are simply the same error delivered faster.</b></p></section><section><h2>Worked source-and-method choices</h2><div className="table-wrap"><table><thead><tr><th>Indicator</th><th>Source and method</th><th>Frequency</th></tr></thead><tbody>{scenarios.map(item=><tr key={item.indicator}><th>{item.indicator}</th><td>{item.source}; {item.method.toLowerCase()}.</td><td>{item.frequency}</td></tr>)}</tbody></table></div></section></>}
   {lesson==='3'&&<><section><h2>Operational plan standard</h2><p>A usable plan connects each indicator to its decision, population, variables, source, method, schedule, accountable roles, verification rule, data flow and protection controls. It also states what happens when data are late, incomplete or implausible.</p><div className="table-wrap"><table><thead><tr><th>Risk</th><th>Control</th></tr></thead><tbody>{scenarios.map(item=><tr key={item.risk}><th>{item.risk}</th><td>{item.control}</td></tr>)}</tbody></table></div></section><section className="practice"><h2>Plan review exercise</h2><ol><li>Confirm that every field supports a named indicator or decision.</li><li>Test definitions against the Level 1 indicator reference sheet.</li><li>Check feasibility against staffing, timing, systems and budget.</li><li>Document validation, correction, escalation and version-control rules.</li><li>Minimise personal data and assign access and retention controls.</li></ol></section></>}
   <section className="practice"><h2>Guided knowledge check</h2>{checks[lesson].map((item,index)=><fieldset key={item.prompt}><legend>{index+1}. {item.prompt}</legend>{item.options.map((option,optionIndex)=><label key={option}><input type="radio" name={`check-${index}`} checked={selected[index]===optionIndex} onChange={()=>setSelected(current=>({...current,[index]:optionIndex}))}/><span>{option}</span></label>)}{selected[index]!==undefined&&<p role="status" aria-live="polite" className={selected[index]===item.answer?'correct':'incorrect'}>{selected[index]===item.answer?'Correct. ':'Review this. '}{item.feedback}</p>}</fieldset>)}<p><b>Current score: {score}/{checks[lesson].length}</b></p></section>
   {lesson==='3'&&<section className="download"><h2>Professional submission standard</h2><p>Complete the template for at least five indicators. Include decisions, populations, variables, periods, disaggregation, sources, methods, verification, quality risks and safeguards. Remove personal and confidential records from the learning copy.</p><a href="/api/merl/level2/data-requirements-template" download>Download data-requirements template (.csv)</a></section>}
   <section className="reflection"><h2>Reflection for practice</h2><p>{lesson==='1'?'Which routinely collected variable in your organisation has no clear decision use?':lesson==='2'?'Where could a less burdensome source or frequency provide adequate evidence?':'Which part of your plan is most likely to fail under real field conditions, and what control would detect that failure early?'}</p></section>
   <footer><a href={lesson==='1'?'/merl/applied':`/merl/applied/06/${Number(lesson)-1}`}>← {lesson==='1'?'Level 2 overview':'Previous lesson'}</a><a className="next" href={lesson==='3'?'/merl/applied':`/merl/applied/06/${Number(lesson)+1}`}>{lesson==='3'?'Return to Module 06':'Continue to next lesson'} →</a></footer>
  </article><aside className="rail"><b>Progression standard</b><ol><li>Connect the indicator to a decision.</li><li>Specify the required data.</li><li>Select proportionate sources and methods.</li><li>Document quality and protection controls.</li></ol><p>Formative feedback is active. Persistent Level 2 evidence and quiz gates will be introduced through a separately tested database migration.</p></aside></div>
  <style jsx global>{`
   .lesson-shell{max-width:1160px;margin:auto;padding:32px 24px 60px;color:#0b2c4d;font-family:system-ui}.lesson-shell a{color:#1565c0}.lesson-shell a:focus-visible,.lesson-shell input:focus-visible{outline:3px solid #f4a261;outline-offset:3px}.lesson-shell>header{margin:24px 0 30px;padding:36px;background:#0b2c4d;color:white;display:grid;grid-template-columns:1fr auto;gap:30px;border-radius:14px}.lesson-shell>header p{color:#f4a261;font-size:12px;font-weight:800;letter-spacing:1.4px}.lesson-shell>header h1{font:700 42px/1.08 Georgia,serif;margin:10px 0}.lesson-shell>header span{color:#d7e0e8;line-height:1.5}.lesson-shell>header aside{border-left:1px solid #ffffff35;padding-left:24px;display:flex;flex-direction:column;justify-content:center}.lesson-shell>header aside span{margin-top:8px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:30px}.layout article>section{margin-bottom:25px}.card,.practice,.download,.reflection{padding:22px;border:1px solid #d7dee7;border-radius:12px}.card,.reflection{background:#f6f8fb}.lesson-shell h2{font:700 28px Georgia,serif}.lesson-shell p,.lesson-shell li,.lesson-shell td{line-height:1.65}.principle{padding:18px;border-left:5px solid #f4a261;background:#fff4e8}.concept-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.concept-grid>div{padding:18px;border-top:4px solid #f4a261;background:#f6f8fb}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border:1px solid #d7dee7;text-align:left;vertical-align:top}thead th{background:#0b2c4d;color:white}.practice fieldset{margin:16px 0;padding:16px;border:1px solid #d7dee7;border-radius:10px}.practice legend{font-weight:700}.practice label{display:flex;gap:9px;min-height:44px;align-items:center}.correct,.incorrect{padding:12px;border-radius:8px}.correct{background:#e8f5ee;color:#175d43}.incorrect{background:#fff4e8;color:#7a430d}.download a,.next{display:inline-flex;min-height:44px;align-items:center;padding:9px 14px;border-radius:6px;background:#f4a261;color:#081f33!important;font-weight:800;text-decoration:none}.rail{height:max-content;position:sticky;top:24px;padding:22px;border-radius:12px;background:#0b2c4d;color:white}.rail li,.rail p{color:#d7e0e8}.lesson-shell footer{display:flex;justify-content:space-between;gap:18px;padding-top:20px;border-top:1px solid #d7dee7}.lesson-shell footer a{min-height:44px;display:flex;align-items:center}
   @media(max-width:800px){.layout{grid-template-columns:1fr}.rail{position:static}.concept-grid{grid-template-columns:1fr}.lesson-shell>header{grid-template-columns:1fr}.lesson-shell>header aside{border-left:0;border-top:1px solid #ffffff35;padding:18px 0 0}}
   @media(max-width:520px){.lesson-shell{padding:20px 14px}.lesson-shell>header{padding:24px 18px}.lesson-shell>header h1{font-size:31px}.card,.practice,.download,.reflection{padding:16px}.lesson-shell footer{flex-direction:column}.lesson-shell footer a{justify-content:center}}
  `}</style>
 </main>
}
